### PR TITLE
Add support for 'linux/arm64' platforms

### PR DESCRIPTION
**Pull request by lucydodo**
## What type of PR is this? 

- [x] Other

## Description

When we take a snapshot, it also creates a Docker image for the ARM64 platform.

## How is this tested?

- [x] Manually

- Docker Hub: https://hub.docker.com/layers/seongtaejg/preview/24.07.0-dev/images/sha256-9370a73741542571e8787cc3c7ae807be9c8fb5e4a5ff15d6f162619f76a7763?context=repo
- GitHub Actions CI log: https://github.com/lucydodo/redash/actions/runs/10190456427
- I confirmed it can run via the `setup` script on Ubuntu 24.04 installed on ARM64-based processor 

## Related Tickets & Documents

#5765

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
Not applicable.

## Notes
Currently, it takes about **3h** to build a docker image.
Of course, I have a new ways in mind to improve this speed(cache, matrix, etc.). But PRs can get too complicated,
so I'm going to make changes to the core functionality first, and then improve the speed with additional PRs.

Any comments or review are welcome. Thank you.

### CODE REVIEW

**Comment by lucydodo** [comment]
This month's snapshot has already been created, so once this PR is approved and merged,
we can consider the new snapshot (`24.08.1-dev`)

**Review by justinclift — APPROVED** [review]

**Comment by justinclift** [comment]
This PR is a lot simpler than I was expecting for adding ARM64 support.

I kind of imagined it'd be some super complicated thing, so I'm glad it didn't need to be. :smile:

**Comment by zachliu** [comment]
after adding `.../poetry cache clear pypi --all`, my gha build would spend hours on `[stage-2 10/13] RUN /etc/poetry/bin/poetry install --only main,all_ds,dev --no-root --no-interaction --no-ansi` and got random errors:
* ``ModuleNotFoundError: No module named 'setuptools.command.install'`
* `gcc: internal compiler error: Segmentation fault signal terminated program collect2`
* `Error: The operation was canceled.` (a timeout after 6 hours)

:crying_cat_face: :crying_cat_face: :crying_cat_face:

**Comment by justinclift** [comment]
What's a "gha"? :smile:

**Comment by zachliu** [comment]
github actions :stuck_out_tongue: 

> What's a "gha"? 😄

**Comment by zachliu** [comment]
now i'm 90% sure that `poetry cache clear...` has nothing to do with my build issue :sweat_smile: 
the culprit is probably the `setuptools` version bump https://github.com/getredash/redash/pull/7060

**Comment by justinclift** [comment]
> the culprit is probably the setuptools version bump https://github.com/getredash/redash/pull/7060

Oh.  Any idea what that version of setuptools breaks?

Bear in mind that one of the even newer versions of setuptools caused breakage and needed to be updated with a follow up point release: https://github.com/getredash/redash/pull/7084

**Comment by zachliu** [comment]
The old `69.0.3` works. The newer `72.1.0` seems to work. I only tried one build using `72.1.0` though. I’ll do more tomorrow.

**Comment by zachliu** [comment]
@justinclift my gut feeling was wrong, the culprit is poetry version mis-match https://github.com/getredash/redash/pull/7122

**Pull request merged**
