### PR TITLE
[WIP+Feedback] Query Page Layout and UX improvements

### PR DESCRIPTION
**Pull request by kocsmy**
In order to improve our query editor, we're experimenting with a couple of changes. Sharing some ideas and progress in this PR. Comments and feedback is much appreciated.

- [x] Discuss: https://sketch.cloud/s/PGjEQ/all/query/query based on @arikfr wireframes
- [x] Move metadata out of page-title to a separate tile
- [x] Fix Hide/Show source positioning with flexbox
- [x] Freely expanding schema browser @arikfr (I think this is pretty cool, but I need feedback on it): https://www.dropbox.com/s/ioyu4bk87xm3vcp/Screenshot%202017-12-12%2022.35.22.png?dl=0
- [x] Experiment in Sketch with fullscreen (single screen) design
- [ ] Show/Hide source now show/hides the entire section below due to massive layout changes. This should only hide/show the query editor and the schema section
- [x] Result Metadata is gets too below the fold when the schema browser gets bigger. This isn't optimal: it's more important to place it so far.
- [ ] Query Metadata breaks into multiple lines: 2 minutes ago -> 2 mins ago, text-overflow:ellipsis; for .name, Hide Created/Updated on smaller screens (add title="Created" for the entire p)
- [ ] Add max-height (40-80vh) to the schema browser so it cannot expand infinitely.

## New Query Editor
screenshot 2017-12-13 20 52 09

### CODE REVIEW

**Comment by kocsmy** [comment]
Adding 2 fullscreen directions here: 

https://sketch.cloud/s/PGjEQ/all/query/query-fullscreen

https://sketch.cloud/s/PGjEQ/all/query/query-fullscreen-white

**Comment by kocsmy** [comment]
Adding new GIF about how it is working currently:

redash-query-flexible

**Comment by arikfr** [comment]
@kocsmy can you push your latest changes? 👍

**Comment by kocsmy** [comment]
I merged the 2 tasks I was working on in 2 branch and this can be found here now: https://github.com/getredash/redash/pull/2157

**Pull request closed without merging**
