### PR TITLE
Fix multiple alert subscription detached

### PR DESCRIPTION
**Pull request by danielerapati**
references #1725 

When a triggered Alert had more than 1 AlertSubscription it could fail
firing the second subscription (and subsequent) due to the
`alert.subscriptions` being detached from the `models.db.session`.

We avoid the problem by explicitely loading the subscriptions by id.

Also implemented a safeguard for alerts when the query result is empty (it assumes alert state is unchanged).

### CODE REVIEW

**Comment by arikfr** [comment]
Thanks!

Did you manage to reproduce #1725 reliably before fixing?

**Comment by danielerapati** [comment]
Hi,
I did reproduce it very reliably on our installation.
I'm working on replicating in a test: the issue clearly depends on the order of database operations and I'm not sure how mock objects will behave after doing [`models.db.session.commit()`](https://github.com/getredash/redash/blob/master/redash/tasks/alerts.py#L51).

Maybe upgrading SQLalchemy would solve the issue more cleanly (rather than hacking how we list AlertSubscriptions).

**Comment by arikfr** [comment]
> I did reproduce it very reliably on our installation.

Can you elaborate on how you reproduce it? I tried to reproduce it in code and in tests (while removing mocks) and failed :( Also had this reproduce at times on demo.redash.io, but now it stopped.

> Maybe upgrading SQLalchemy would solve the issue more cleanly

Why?

I don't mind upgrading, but did you see anything in the changelog that might be related?

**Comment by danielerapati** [comment]
> Can you elaborate on how you reproduce it?
It happens on our installation whenever an alert with more than one subscription fires. I deployed a `scheduler` container with this patch and it would notify all alert subscriptions without failing. 

I agree that there should be a test for this patch to be considered complete.
It almost seems like there is a bit of information missing to reliably reproduce.

> did you see anything in the changelog that might be related?
I'm going through them now.

**Comment by arikfr** [comment]
> It happens on our installation whenever an alert with more than one subscription fires. I deployed a scheduler container with this patch and it would notify all alert subscriptions without failing.

I see it happen on a query with a single subscriber 🤔

> I agree that there should be a test for this patch to be considered complete.
It almost seems like there is a bit of information missing to reliably reproduce.

The reason I want to reproduce this before merging is that I'm worried we're burying a bigger issue here that we better understand and fix. Meanwhile spent almost a day on this and still no reliable reproduction or understanding of the problem 😞 .

**Comment by arikfr** [comment]
I think I found it 🎉  the call to `app.app_context()` [here](https://github.com/getredash/redash/blob/master/redash/destinations/email.py#L43) is not needed and probably closes the previous session.

Going to verify this properly now, but wanted to share so you don't waste any more time.

**Comment by danielerapati** [comment]
Wow, awesome job.
This would answer why tests with mock alert subscriptions don't replicate the problem and why it seems to depend on the order in which the alert subscriptions are notified.
Thank you

**Comment by arikfr** [comment]
@danielerapati mind giving #1792 test on your environment? 

Also, can you revert the change to the way we fetch subscriptions we have in this pull request so I can merge it for the other fix? 

Thanks.

**Comment by danielerapati** [comment]
Tested, it works as expected :+1:

I have opened #1793  for the safeguard against empty results.

**Comment by arikfr** [comment]
thanks!

**Pull request closed without merging**
