### PR TITLE
Changed checkout commit

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
## What type of PR is this? 
changed checkout commit in github actions

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [x] Manually
- [ ] N/A

### CODE REVIEW

**Review by justinclift — APPROVED** [review]
Sounds sensible to me. :smile:

**Comment by justinclift** [comment]
Hmmm, this *should* be passing the frontend CI tests shouldn't it?

**Comment by AndrewChubatiuk** [comment]
nope, it relies on config in master

**Comment by justinclift** [comment]
Ahhh, no worries.  Merged.

**Pull request merged**
