### PR TITLE
replaced numeral-js with native numbers and percent formatting

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
## What type of PR is this? 
replaced numeral js with a native numbers formatting

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

### CODE REVIEW

**Comment by justinclift** [comment]
With this "native numbers" approach, does that mean it'll handle numbers larger than `MAX_SAFE_INTEGER`?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by AndrewChubatiuk** [comment]
> With this "native numbers" approach, does that mean it'll handle numbers larger than `MAX_SAFE_INTEGER`?
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

it parses numbers from string, it has more powerful functionality than numeral-js
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat

**Comment by justinclift** [comment]
@eradman What do you reckon?  You're our resident front end expert. :smile:

**Comment by justinclift** [comment]
I can't review this with my current skill set, as I don't know Typescript at all (yet), and it's not likely in the near future.

So, it'll need someone else to look over it.

**Pull request closed without merging**
