### PR TITLE
Search dropdown parameters

### PR DESCRIPTION
**Pull request by fmy**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source)
- [ ] New Alert Destination
- [ ] Other

## Description
I added props of antd `Select` so that I can search dropdown list.
Some query-based dropdown lists may have too many options which are hard to be selected.

## Related Tickets & Documents

Docs of antd `Select`
https://ant.design/components/select/

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
スクリーンショット 2019-05-14 12 29 38

スクリーンショット 2019-05-14 12 21 20

### CODE REVIEW

**Comment by fmy** [comment]
Related #3014

**Comment by rauchy** [comment]
Thanks @fmy, LGTM!

Is `minWidth` required for this?

**Comment by tiagoajacobi** [comment]
Hi Guys. Do you have any Idea when this is going to be released?
I updated yesterday to the V7, as the component changed from SELECT to the new one, the users can not type anymore, to find a match on the field.

Is there any estimation for releasing it?
Thanks.

**Comment by gabrieldutra** [comment]
> Is `minWidth` required for this?

This is what happens without it:
search-without-min-width

**Comment by ranbena** [comment]
Also, let's add `notFoundContent={null}` so that "No Data" message doesn't appear when there's no search results.

**Comment by fmy** [comment]
Address comments.
`minWidth: 60`
スクリーンショット 2019-07-20 16 57 44

`notFoundContent={null}`
スクリーンショット 2019-07-20 16 58 20

**Comment by fmy** [comment]
@ranbena Please take another look.

**Pull request merged**
