### PR TITLE
add databricks logo to assets

### PR DESCRIPTION
**Pull request by alison985**
Adding this logo based on @arikfr's comment [here](https://github.com/getredash/redash/pull/2747#issuecomment-424763478).

### CODE REVIEW

**Comment by alison985** [comment]
FYI @jezdez

**Comment by jezdez** [comment]
The other images are all 256x256 AFAIK, could you please update it to match the other formats? If possible by taking the same transparent border distance into account?

**Comment by alison985** [comment]
I'm gonna be honest, that's above my graphics ability.

**Comment by kocsmy** [comment]
Here's the 256x256 version :)

databricks

**Comment by jezdez** [comment]
Huzzah @kocsmy!

**Pull request closed without merging**
