### PR TITLE
SAML: use NameID value, if SAML Assertion is missing

### PR DESCRIPTION
**Pull request by zoetrope**
I want to use NameID value instead of Assertion Attribute.

### CODE REVIEW

**Comment by jeffwidman** [comment]
Any reason this was never merged? It seems straightforward

**Comment by arikfr** [comment]
@jeffwidman mainly because I never had the time to verify that it's "safe" or correct :-( For example this line: `email = authn_response.ava['EmailAddress'][0]` -- I don't know if it's guaranteed to be a list every time :\

**Comment by arikfr** [comment]
Hi,

(This is a template message, but I mean every word of it. Also you're welcome to reply)

Thank you for making this contribution. While we couldn't bring it to completion and merge, it's still very much appreciated. 🙇

In the past year the Redash code base gone under massive updates: on the backend we moved to Python 3 & RQ instead of Celery and on the frontend we replaced Angular with React. It's very likely this makes this PR irrelevant without significant changes. :-( 

I'm closing this PR now. But if you're still interested in making it happen, let me know and I will reopen.

Thanks.

**Comment by jeffwidman** [comment]
@arikfr I'm surprised you haven't had customers ask for this?

**Comment by arikfr** [comment]
This is not related to the Pull Request directly, but I assume that the author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.

**Pull request closed without merging**
