### PR TITLE
Refactor dialog wrapper component

### PR DESCRIPTION
**Pull request by kravets-levko**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature
- [x] Other

## Description

- [x] Stop using promises to get dialog result; use callback instead.
- [x] Handle async operations on dialog close/dismiss: show spinner on corresponding button (depending on action - close or dismiss) and wait until operation completes; if operation fails - keep modal visible. This pattern was used in a lot of dialogs, so now this feature is "built-in" and makes dialogs UX more consistent.
- [x] Refactor: update some dialogs to be function-based components (reduced amount of code and simplified code a bit). Updated only dialogs that needed feature from [2]. 

Also fixed some minor bugs found during working on these changes.

## Related Tickets & Documents

Closes getredash/redash#4566

### CODE REVIEW

**Comment by kravets-levko** [comment]
@gabrieldutra 

>  One single thing I would review: the onClose name can be a bit confusing, wdyt about using something else? (e.g: onOk - the same Antd uses)

I see your point, but there's one thing that may be confusing in this case: there are two methods to close dialog: `dialog.close(...)` to accept it and `dialog.dismiss(...)` to dismiss. And I tried to keep naming consistent. If we'll decide to rename `onClose` to something else (e.g. `onAccept`) - then we have to rename `dialog.close()` method as well (`dialog.accept(...)` - ?). So WDYT?

**Comment by gabrieldutra** [comment]
For the dialog commands it does feels better to have `close` and `dismiss` (those look more like actual actions). So I think we can leave as is and just rename it in case it becomes confusing.

**Comment by kravets-levko** [comment]
So you offer to keep `dialog.close()/.dismiss()` methods names, but rename handlers to `onAccept/onDismiss`, right? Looks a bit weird, but why not :slightly_smiling_face:

**Comment by gabrieldutra** [comment]
> So you offer to keep `dialog.close()/.dismiss()` methods names, but rename handlers to `onAccept/onDismiss`, right? Looks a bit weird, but why not slightly_smiling_face

I actually meant to leave all names as they are :sweat_smile:, but I'm good with any of those options.

**Comment by kravets-levko** [comment]
> I actually meant to leave all names as they are , but I'm good with any of those options.

So okay then, let's keep it as is (does this mean that I'm too lazy? :thinking:) I addressed other comments and resolved conflicts - can you please take one more look before I merge it?

**Pull request merged**
