### PR TITLE
Automatic database upgrades upon services start-up

### PR DESCRIPTION
**Pull request by zachliu**
## What type of PR is this? 

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description

Automatically upgrade the database upon services start-up. So that we don't need to do it manually using cli tools on the server.

I started the discussion https://github.com/getredash/redash/discussions/7005 on automated db migration mechanisms.

Further discussing: https://github.com/getredash/redash/pull/7161#issuecomment-2352747467

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [x] Manually
- [ ] N/A

### CODE REVIEW

**Comment by justinclift** [comment]
Ahhh.  This looks like it's causing a CI failure by attempting a database upgrade even before the database has been initialised.

@zachliu Are you ok to investigate and get it working? :smile:

**Comment by zachliu** [comment]
@justinclift we probably need a "wait" in `ci.yml' between these two commands

https://github.com/getredash/redash/blob/c42b15125c1af991998f7602e0c2a7449a397b25/.github/workflows/ci.yml#L162-L163

do you prefer a blunt `sleep 35` or a smarter `.ci/wait-for-it.sh localhost:5001 --strict --timeout=35 -- echo "Server is ready."`?

**Comment by justinclift** [comment]
Hmmm, I wonder why we're skipping the database seed on one line, then running it manually on the next line?  At some point I probably knew the answer to that. :wink:

That being said, of your two options we should probably take the smarter :smile: approach and wait for the previous step to actually be complete.

**Comment by zachliu** [comment]
actually, redash has been using a simple `sleep` in the `ci.yml` file:
https://github.com/getredash/redash/blob/c42b15125c1af991998f7602e0c2a7449a397b25/.github/workflows/ci.yml#L50-L52
i figure i'll just keep it simple and consistent with the existing code :grin: 

dumb question: i'll need another PR to update the CI right? otherwise it won't take effect

**Comment by gaecoli** [comment]
Is this change too dangerous?

**Comment by justinclift** [comment]
> Is this change too dangerous?

In theory (!) it shouldn't be, at least for not-big-version-jumps (of Redash version).

People trying to run the development code directly against a Redash database from prior-to-version-10 *might* have issues though (am guessing).

But that would be a *very* unexpected situation for someone to try unless intentionally getting creative for some reason. :wink:

**Comment by justinclift** [comment]
> i figure i'll just keep it simple and consistent with the existing code 😁

No worries.

> dumb question: i'll need another PR to update the CI right? otherwise it won't take effect

Nah.  In theory the CI runs from the state of the repo as it is presented by the PR itself.

ie it'll make a `git clone -b [PR branch]` onto the chosen CI server and then run the CI from the files there.

At least, that's my present understanding of things.

Does that help? :smile:

**Comment by gaecoli** [comment]
> > Is this change too dangerous?
> 
> In theory (!) it shouldn't be, at least for not-big-version-jumps (of Redash version).
> 
> People trying to run the development code directly against a Redash database from prior-to-version-10 _might_ have issues though (am guessing).
> 
> But that would be a _very_ unexpected situation for someone to try unless intentionally getting creative for some reason. 😉

OK!

**Comment by zachliu** [comment]
> > i figure i'll just keep it simple and consistent with the existing code 😁
> 
> No worries.
> 
> > dumb question: i'll need another PR to update the CI right? otherwise it won't take effect
> 
> Nah. In theory the CI runs from the state of the repo as it is presented by the PR itself.
> 
> ie it'll make a `git clone -b [PR branch]` onto the chosen CI server and then run the CI from the files there.
> 
> At least, that's my present understanding of things.
> 
> Does that help? 😄

interesting, then it's very odd that the `sleep 30` is ineffective and didn't show up in the log at all :thinking: 

```
yarn cypress start -- --skip-db-seed
sleep 30
docker compose run cypress yarn cypress db-seed
```

**Comment by justinclift** [comment]
Well, that's weird then. :confused:

Maybe do some test PR's in a different fork or something along those lines?

**Comment by zachliu** [comment]
did some tests in my own fork and found the problem(s):
1. when updating the `.github/workflows/ci.yml`, the changes don't take effect until they are merged to master (they will be effective for future PRs)
2. the issue is not because we need a `sleep` between these two commands
    ```
    yarn cypress start -- --skip-db-seed
    docker compose run cypress yarn cypress db-seed
    ```
    it's because we are upgrading the db before creating it
    https://github.com/getredash/redash/blob/c42b15125c1af991998f7602e0c2a7449a397b25/client/cypress/cypress.js#L49-L53

**Comment by justinclift** [comment]
> the changes don't take effect until they are merged to master

Cool. :smile:

Heh Heh Heh, I really thought it was whatever the state of the PR branch was that controlled it.  But something every day I guess. :smile:

> we are upgrading the db before creating it

Makes sense.  Not a race condition then, just an order-of-operation thing.

Good stuff @zachliu, I'll take a look at those when I'm at the co-working space later on today. :grin:

**Comment by justinclift** [comment]
> I'll take a look at those when I'm at the co-working space later on today.

It's going to have to be tomorrow instead.  Today I went through the investigation of broken embeds instead (finding a good enough workaround), and now I'm mentally brain drained.

I've finished the embeds investigation now though, so this will be the first thing to look at tomorrow (unless something urgent pops up overnight). :smile:

**Pull request closed without merging**
