### PR TITLE
Add: rate limit the login page

### PR DESCRIPTION
**Pull request by AntoineAugusti**
This is related to https://github.com/getredash/redash/issues/115

Straightforward use of Flask limiter https://flask-limiter.readthedocs.io

### CODE REVIEW

**Comment by AntoineAugusti** [comment]
Added a test + squashed

**Comment by AntoineAugusti** [comment]
Added a conf variable

**Comment by AntoineAugusti** [comment]
@arikfr Anything blocking this PR for being merged?

**Comment by arikfr** [comment]
Sorry for not mentioning earlier -- I'm no longer merging stuff until I finish with the 0.12 release (#1378). Once it's out, I will merge it.

**Comment by arikfr** [comment]
Hi, @AntoineAugusti - because I removed the `docs` folder, you need to rebase. Thanks.

**Comment by AntoineAugusti** [comment]
@arikfr Rebased and squashed 👍

**Comment by arikfr** [comment]
Thanks!

**Pull request merged**
