### PR TITLE
fixes query pagination alignment

### LINKED ISSUE #2569: navigation displayed in the query source page is not centered
Details: https://github.com/mozilla/redash/issues/320

Opening issue to submit PR against.

### PR DESCRIPTION
**Pull request by alison985**
fixes #2569

Same as https://github.com/mozilla/redash/pull/413/ which fixes https://github.com/mozilla/redash/issues/320

### CODE REVIEW

**Comment by arikfr** [comment]
I'm not sure about this one actually. Because the pagination is in the same "container" element as the table itself, if the table is wide enough, it might make the pagination not visible without scrolling.

Maybe the paginator needs its own container (which is 100% width of the parent), and then we can center it?

@kocsmy wdyt?

**Comment by kocsmy** [comment]
I'm not sure either about the center position. The table can be very wide + the left alignment kinda makes sense here for me.

If you implement this, make sure it gets its own container as @arikfr was suggesting.

**Comment by alison985** [comment]
This is related to #2584.

**Comment by arikfr** [comment]
Thanks!

**Pull request merged**
