### PR TITLE
Fix full screen botton on a dashboard isn't working problem

### LINKED ISSUE #2094: Full screen button on a dashboard isn't working
Probably a forgotten CSS style issue.

### PR DESCRIPTION
**Pull request by kyoshidajp**
Fix #2094.

It seems like a typo.

### CODE REVIEW

**Comment by arikfr** [comment]
@kocsmy is this the same as you did on your branch?

**Comment by kocsmy** [comment]
Yes, this is the same issue which is getting fixed in the next PR.

**Comment by kyoshidajp** [comment]
@arikfr Basically, is this PR no longer needed? If so, please close this PR. Thanks.

**Comment by kocsmy** [comment]
My PR will come next week so if you want to address this sooner feel free to accept this PR and I'll also merge into my branch.

**Comment by arikfr** [comment]
I'm closing this as Zsolt had a bit of a different implementation in #2113 and I prefer to avoid merge conflicts. But thank you for @kyoshidajp for the effort 🙏

**Pull request closed without merging**
