### PR TITLE
Show dashboard creator on dashboard page

### PR DESCRIPTION
**Pull request by kocsmy**
46878258-18436200-ce43-11e8-99fb-2f500a496b1a

- I think this opens up some space for other details for example last edited time.
- I tried it without a background but I kind alike having this slight grey tone / this might be not the best choice though as it looks very similar to our secondary button design. Might need to make it less grey.

### CODE REVIEW

**Comment by arikfr** [comment]
1. Can you show an example without the background?
2. How about aligning to the left?

**Comment by arikfr** [comment]
Something I just thought about -- it will look really awkward on an empty dashboard, no?

**Comment by kocsmy** [comment]
Hmm, it will indeed look awkward on an empty dashboard :) 

Another idea: maybe put it on the top right header (left to the refresh schedule) and only show it on header hover (just like add tags)?

**Comment by kocsmy** [comment]
I'm not convinced this is better. It is not such an important information to show it there.

image

**Comment by kocsmy** [comment]
How about adding an extra item here that opens a modal with extra details:
image

**Comment by kocsmy** [comment]
Regarding empty dashboards / adding below the widgets: we could attach it to the bottom, similarly to our footer. That way it would be okay there. I think I like that idea the most.

**Comment by arikfr** [comment]
> How about adding an extra item here that opens a modal with extra details:

Feels like too buried. 

> Regarding empty dashboards / adding below the widgets: we could attach it to the bottom, similarly to our footer. That way it would be okay there. I think I like that idea the most.

So far it's the best idea.

But how about showing the profile picture next to the dashboard title? Hovering on it, will show a text saying "Last edit 2 days ago by Zsolt Kocsmarszky (created 2 years ago)"?

**Comment by kocsmy** [comment]
Here's how it'll look.

image

First, I though it'll be strange that we'll have the favorite and this sandwiching the title. But this could actually work fine.

I'm fine with both this and above the footer.

**Comment by kocsmy** [comment]
Here's a version with tags next to it:
image

**Comment by kocsmy** [comment]
I was so confident that I made the change in the markup and css and moved it next to the title.

If you are happy, it just needs implementation: actual user image, tooltip.

**Comment by jezdez** [comment]
@kocsmy @arikfr Is there anything I can help move this along?

**Comment by arikfr** [comment]
@jezdez it was missing the binding to the actual data. Fixed and merged.

**Comment by jezdez** [comment]
@arikfr Thank you 😻

**Pull request merged**
