### PR TITLE
fix:New ElasticSearch Query Runner

### PR DESCRIPTION
**Pull request by wwl717195673**
## What type of PR is this? (check all applicable)

- Other: fix other PR that not be merged

### 1.fix Schema refresh failed.
relevant code(elasticsearch2: line 86-90):
```python
for index_name in mappings_data:
            mappings[index_name] = {}
            index_mappings = mappings_data[index_name]
            for m in index_mappings.get("mappings",{}):
                _parse_properties('', index_mappings['mappings'][m]['properties'])
```
It finally looks like this:
scheme

### 2.fix X-Pack Sql bug
1. changed X-Pack Sql query url from "/_sql" to "/_xpack/sql"
2. rewrote the run_query method for XPackSql
3. fixed error that raise Exception

relevant code:
1.elasticsearch2: line 257-262
```python
def _build_query(self, query: str) -> Tuple[dict, str, Optional[list]]:
        sql_query = {
            'query': query
        }
        sql_query_url = '/_xpack/sql'
        return sql_query, sql_query_url, None
```
2.elasticsearch2: line 264-275
```python
def run_query(self, query, user):
        query, url, result_fields = self._build_query(query)
        response, error = self.get_response(
            url,
            http_method='POST',
            json=query
        )
        query_results = response.json()
        data = self._parse_results(result_fields, query_results)
        error = None
        json_data = json_dumps(data)
        return json_data, error
```
3.elasticsearch2: line 281
```python
def _parse_results(cls, result_fields, raw_result):
        error = raw_result.get('error')
        if error:
            raise Exception(error)
```
***
At last,Our team have used this feature for months.So far, it seems to be working properly.
**X-Pack Sql Editor:**
image

**ES Alert:**
(ps: Actually,our main purpose is using alert for es.)
image
image

Our ES Version is 6.8.If u wanna use this,please check ur ES Version(must not be oss version).
## Related Tickets & Documents

https://www.elastic.co/guide/en/elasticsearch/reference/6.8/sql-spec.html

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
null

### CODE REVIEW

**Comment by susodapop** [comment]
Thank you so much for this effort. Looking forward to merging this. Can you clarify the following?

> Our ES Version is 6.8. If u wanna use this, please check ur ES Version(must not be OSS version).

I'm not familiar with ES versions, but is this a common limitation? Is it something another member of the open source community could add in a follow-up PR?

**Comment by wwl717195673** [comment]
> Thank you so much for this effort. Looking forward to merging this. Can you clarify the following?
> 
> > Our ES Version is 6.8. If u wanna use this, please check ur ES Version(must not be OSS version).
> 
> I'm not familiar with ES versions, but is this a common limitation? Is it something another member of the open source community could add in a follow-up PR?

ES started supporting XPack-SQL from Version 6.3.

And from 6.3 TO 6.8，SQL REST APIs are all same,which is POST Method and "/_xpack/sql"  url.This commit is based on this.

You can check ES Docs about sql supporting below:

version 6.3:https://www.elastic.co/guide/en/elasticsearch/reference/6.3/sql-getting-started.html

version 6.4:https://www.elastic.co/guide/en/elasticsearch/reference/6.4/sql-getting-started.html

version 6.5:https://www.elastic.co/guide/en/elasticsearch/reference/6.5/sql-getting-started.html

version 6.6:https://www.elastic.co/guide/en/elasticsearch/reference/6.6/sql-getting-started.html

version 6.7:https://www.elastic.co/guide/en/elasticsearch/reference/6.7/sql-getting-started.html

version 6.8:https://www.elastic.co/guide/en/elasticsearch/reference/6.8/sql-getting-started.html

But ES Version 6 ended with 6.8.



From Version 7,in the ES docs,they updated sql REST API's url to "/_sql",but still POST Method.

You can check ES Docs about sql supporting below:

version 7.0:https://www.elastic.co/guide/en/elasticsearch/reference/7.0/sql-getting-started.html

From version 7.0 to version 7.17(current version),SQL REST APIs are all same,too.So i dont give the other version 7 docs here.

If u stiil wanan have a check,just go to this [[link](https://www.elastic.co/guide/en/elasticsearch/reference/index.html)](https://www.elastic.co/guide/en/elasticsearch/reference/index.html)  and choose a version. 



But this thing is not ended,Guess What?

I tested Version 6's SQL REST API on the Version 7 success,which means "/_xpack/sql" url still works on version 7.

image-20220210154153303

image-20220210154224834
Then I tested this commit with Version 7 in real redash enviroment.SQL query still works,but scheme refresh failed.

What make this?

Version 6 AND Version 7，they have different "/_mapping" response.

Version 6(have anther filed between mapping and properties):

image-20220211143841696


version 7:

image-20220211143939225


So,I changed the scheme refresh code

from

```python
for index_name in mappings_data:
            mappings[index_name] = {}
            index_mappings = mappings_data[index_name]
            for m in index_mappings.get("mappings",{}):
                _parse_properties('', index_mappings['mappings'][m]['properties'])
```

to

```python
for index_name in mappings_data:
            mappings[index_name] = {}
            index_mappings = mappings_data[index_name]
            try:
            	for m in index_mappings.get("mappings",{}):
                	_parse_properties('', index_mappings['mappings'][m]['properties'])
            except KeyError:
            	_parse_properties('', index_mappings['mappings']['properties'])
```

Then Version7 can refresh scheme:

image-20220211144525613

Finally,this change will cover ElasticSearch 6 and 7,which are mainly used in industry.

**Comment by wwl717195673** [comment]
@susodapop Any question else?Does this still need some other modify?

**Comment by NgZiming** [comment]
Is this compatible with opensearch or opensearch 2.0?

**Comment by susodapop** [comment]
Sorry for the late reponse @NgZiming.  Opensearch is a hard fork of a an old version of Elastic Search ([context](https://www.elastic.co/what-is/opensearch)). This query runner _may_ support OpenSearch, but it's not guaranteed. If there is significant demand for an OpenSearch query runner we would certainly review a pull request implementing one.

This query runner will merge in the next couple of weeks and you can try it for yourself.

**Review by susodapop — CHANGES_REQUESTED** [review]
This looks great and I'm planning to merge by way of #5794 to make sure everyone's commit history is retained in the PR. I will ping you there. Planning to merge this ASAP.

**Pull request closed without merging**
