### PR TITLE
WIP: Add Compare Query Versions Feature Upstream

### PR DESCRIPTION
**Pull request by alison985**
This is a port from the Mozilla fork. Issue to port it upstream: https://github.com/mozilla/redash/issues/583

This PR adds the Compare Query Version feature to getredash. That includes:
1. Saving each saved version of the query.
2. Allowing folks to compare query versions and revert back to a previous query version.

This is listed as a WIP because of a rendering issue with the query editor textarea. I would like help with this part please.

### CODE REVIEW

**Comment by alison985** [comment]
Specifically, the textarea issue is confusing me because:
a) it works fine in Chrome 70.0.3538.77
b) when it shows up in Firefox 60.0.2 (64-bit) the way to fix it isn't code based but instead to re-size your browser window.

If you do a normal load of the page (or refresh), the screen looks like this, not showing the entire query string: 
screenshot 2018-10-28 19 02 39

If you resize the browser window, it will correctly render like this: 
screenshot 2018-10-28 19 02 51

**Comment by alison985** [comment]
@jezdez & @rafrombrc - This is a Firefox specific issue. Pointers on next steps would be appreciated.

**Comment by alison985** [comment]
@arikfr Here are screenshots of the compare query feature.

The menu on the edit query page:
screenshot 2018-11-25 21 52 50

Compare Query dialog when initially opened:
screenshot 2018-11-25 21 52 43

Compare Query dialog with a specific version chosen for comparison.
screenshot 2018-11-25 21 53 17

**Comment by kocsmy** [comment]
We'll need to modernise this interface so it fits our design.

- Can we use code coloring like it's in the editor?
- I have some ideas to improve the layout, too, I will provide a design later this week.

**Comment by fjcero** [comment]
What about this?

**Comment by arikfr** [comment]
Hi,

(This is a template message, but I mean every word of it. Also you're welcome to reply)

Thank you for making this contribution. While we couldn't bring it to completion and merge, it's still very much appreciated. 🙇

In the past year the Redash code base gone under massive updates: on the backend we moved to Python 3 & RQ instead of Celery and on the frontend we replaced Angular with React. It's very likely this makes this PR irrelevant without significant changes. :-( 

I'm closing this PR now. But if you're still interested in making it happen, let me know and I will reopen.

Thanks.

**Comment by jezdez** [comment]
Hey, can you elaborate if this is something you'd take?

**Comment by arikfr** [comment]
Would we want a version history feature? Sure. But we should probably discuss UX & implementation before.

**Comment by jezdez** [comment]
Okay, great, I'll chat with the others soon and get back to you about it.

**Comment by fjcero** [comment]
@jezdez @arikfr If PRs are welcome, I will like to contrib!

**Pull request closed without merging**
