### PR TITLE
Add limit option for MSSQL query runner

### PR DESCRIPTION
**Pull request by dvandonkelaar**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description

The limit query adds ` LIMIT 1000` to the end of the query, but this isn't working for MSSQL queries.
This change adds the possibility to add the query runner specified limit text after the `SELECT` statement, based on the `limit_after_select` variable.

## How is this tested?

- [X] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

## Related Tickets & Documents

This issue is also discussed in #5773. No other issues 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
N/A

### CODE REVIEW

**Comment by justinclift** [comment]
Thanks for this @dvandonkelaar.  It looks like this needs some formatting tweaks in order to pass the CI testing though.

Are you ok to get that fixed?

**Comment by dvandonkelaar** [comment]
Thanks for the quick reply! My apologies, apparently I ignored the non-installed linter errors.
Commint 7e630f fixes the errors.

**Review by justinclift — APPROVED** [review]
Looks good to me, and we can ignore the minor codecov problem in this instance. :smile:

**Comment by justinclift** [comment]
@dvandonkelaar Thanks for getting this done, it fixes an important bug with the MSSQL driver. :smile:

**Pull request merged**
