### PR TITLE
Text visualization

### PR DESCRIPTION
**Pull request by vokimon**
## What type of PR is this? (check all applicable)

- [x] Other: New visualization

## Description

This pull request adds a new kind of visualization: Markdown formatted text which may include data from the query by means of template parameters. The module uses existing handlebars and markdown dependencies and it is based on the Details visualization.

I PR'ed it as soon as i got the first minimal useful version. I guess that testing. documentation and more configuration options would be nice to be added.

## Related Tickets & Documents

None.

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

image

image

### CODE REVIEW

**Comment by kravets-levko** [comment]
Related to (replaces?) getredash/redash#3776

**Comment by vokimon** [comment]
> Related to (replaces?) #3776

Ooops, i really missed it, not really tying to replace it. The approach is slightly different (paging vs mustache iteration) but indeed i do like more mustache iteration in #3776 . So why the other PR didn't get into master? It seems to be working as well? Anything missing i could help?

**Comment by ned-kelly** [comment]
Is there any way we can get this added and included before the official v10 release?

**Comment by susodapop** [comment]
This won't be included in the V10 release (in the next few days). After the V10 release we'll clean up our open PR list.

**Comment by guidopetri** [comment]
@vokimon , thanks for the PR! We've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI?

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Comment by vokimon** [comment]
I am not using redash anymore, for a while. Neither my former team, who is now replacing the redash system we built back then 2years and a half. So i currently have no particular interest on having this PR merged.

Even thought, there is some work done here and i will be very glad if eventually someone takes over and gets some use of it. I won't.

I loved redash modular and extensible design, so best wishes.

**Pull request closed without merging**
