### PR TITLE
Refresh when changing (global) parameters

### PR DESCRIPTION
**Pull request by seenivasanp**
Whenever parameters changed in the dashboard or query page,Url is changing but page reload is not happening.Here is the code for reloading the page when focus lost(parameters changed) in dashboard(only for global params).

### CODE REVIEW

**Comment by timwis** [comment]
Woohoo! thanks :)

**Comment by awm33** [comment]
@arikfr Any chance this could be merged? This is the biggest complaint I get from people using our dashboards, that they have to hit refresh,or forget to and end up misinterpreting dashboard numbers.

**Comment by oren-icx** [comment]
This would be great improvement!
Any plan to merge this?

**Comment by arikfr** [comment]
Thanks, @seenivasanp, but we're going to solve this with better UI for parameters both on dashboards and queries. See the discussion in #2316, specifically the last comment: https://github.com/getredash/redash/issues/2316#issuecomment-403484425 for details on how we're going to address this.

Closing this now.

**Pull request closed without merging**
