### PR TITLE
Fix: date type values are displayed as int type

### PR DESCRIPTION
**Pull request by iwakiriK**
## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Description
For values of date type, if `moment.utc()` is executed and columnType is string, it will be displayed as int type.

image

This PR will fix this problem.

## Related Tickets & Documents
https://momentjs.com/docs/#/parsing/utc/

### CODE REVIEW

**Comment by guidopetri** [comment]
@iwakiriK , thanks for the PR! Same story here, we've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI?

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Comment by justinclift** [comment]
Looks like it's failing our frontend lint tests. :frowning:

**Comment by eradman** [comment]
@iwakiriK can you illustrate the problem this PR solves using a simpler query?

Datetimes are interpreted correctly on 10.1.0 (which uses numeral.js) and 23.09.0-dev (which uses numbro.js)

datetime

**Comment by eradman** [comment]
Re-tested this with 24.07.0-dev and have not observed a problem. Closing, but feel free to re-open with more information

**Pull request closed without merging**
