### PR TITLE
Tagging and favorites for Queries and Dashboards

### LINKED ISSUE #2265: Query search improvement
- [ ] Remove current separate search tab from Queries page
- [ ] Search should be included in each query tab and should search as you type

### PR DESCRIPTION
**Pull request by arikfr**
As mentioned in the [latest Redash Monthly](https://www.getrevue.co/profile/redash/issues/introducing-redash-monthly-117376), we (@kravets-levko, @kocsmy and myself) had our first in person team meeting last month 🤩We used some of the time to travel, but most of it we decided to devote to tackle something that's been annoying Redash users for a long time -- better queries and dashboards discovery in Redash.

This pull request introduces proper tagging for queries and dashboards along with the ability to mark queries/dashboards as favorites for quicker access.

Dashboards List

TODO:
- [x] Limit the number of favorites we show in the dropdown / apply pagination @arikfr
- [x] Make Cmd/Shift+Click work as intended on queries/dashboards list @kravets-levko 
- [x] Change the API to filter by tags @arikfr
- [x] Move imports to their correct location (func in tags calls) @arikfr
- [x] Record usage events @arikfr
- [x] `UniqueConstraint` (or `primary_key=True`) for favorites table @arikfr
- [x] Rebase with latest master and replace underscore with lodash
- [x] Remove N+1 queries @arikfr
  - [x] users in dashboards API call
  - [x] dashboards favorites

NTH (probably won't be implemented in this pull request):

- [ ] Mobile: when we have a lot of tags, the top section will get lengthy @kocsmy 
- [ ] Filter queries by data source.
- [ ] Filter queries by schedule status.
- [ ] Tags should be clickable on Dashboard/Query pages (not in lists). Clicking on them should take you to a page showing all other queries/dashboards related to this tag.

Closes #2265.

### CODE REVIEW

**Comment by alison985** [comment]
Hi. @jezdez requested I bring up the fact that it is hard for a user to find archived queries. Is there a way that tagging could be used to find these?

**Comment by kocsmy** [comment]
I found a weird bug on Dashboard/Query listings on the nav: 
weird-bug-with-dashboard-dropdown

**Comment by arikfr** [comment]
@kocsmy 
> I found a weird bug on Dashboard/Query listings on the nav:

Fix.ed

**Comment by arikfr** [comment]
Merged. 🥂

**Comment by jezdez** [comment]
@arikfr Huzzah! 🍾

**Pull request merged**
