### PR TITLE
Revert "Switch from numeral to numbro (#6344)"

### PR DESCRIPTION
**Pull request by eradman**
This reverts commit f8934b83126261ae5639d35843518e7ceabaae87.

## What type of PR is this? 

- [x] Bug fix

## Description

Using a format string of `0` does not round to the nearest integer in Numbro 

## Related Tickets & Documents

[numbro/issues/745](https://github.com/BenjaminVanRyseghem/numbro/issues/745)

### CODE REVIEW

**Review by justinclift — APPROVED** [review]
Well damn.  Oh well, if you reckon this is the best approach for now, then I'm ok with it. :smile:

**Comment by masayuki038** [comment]
Oh my god... But you realized it now. Nice catch !

**Comment by justinclift** [comment]
Looking at the issue @eradman filed on the numbro repo, they might be able to suggest a workaround or fix the problem themselves.

So, we're probably best to leave this for a few days and see how that issue goes.  If nothing substantial turns up by then, we can merge this to revert back to numeral.

**Comment by eradman** [comment]
Agreed; we should wait and see if there is a workaround we can use.

**Comment by eradman** [comment]
A build from top of tree (392b930f2dde5f05033e459983b6cb8656672de7) shows that the previous behavior was restored

value_percent

Perhaps there is a delay in updating the docker image?

**Comment by masayuki038** [comment]
@eradman Thanks for your confirmation!
It may be something wrong in my env. I will check it again. thank you.

**Comment by masayuki038** [comment]
Indeed, the image created with `make compose_build` gave the expected value...
I will check `redash/redash:preview` later.

**Comment by guidopetri** [comment]
@masayuki038 it might be a caching issue, where docker didn't pull the latest image.

**Comment by masayuki038** [comment]
@guidopetri Thanks for your comment.
I ran `docker rmi redash/redash:preview`... I'll try it on another machine. thank you.

**Comment by masayuki038** [comment]
Today, I tried `redash/redash:preview` again and it is fine. It seemed to be a cache issue. thank you.

**Pull request merged**
