### PR TITLE
Speed up BigQuery get schema operation in massively tables environment

### PR DESCRIPTION
**Pull request by katsugeneration**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature

## Description

This implementation enable to speed up get_schema operation in BigQuery environments which have massively tables (about over 1k tables).

In the environment which has about 1k tables , it takes about **10 minutes** by current implementation. Very slow operation caused the operation timeout at default timeout settings. 

The cause of the slow operation is calling get table's column list api per table in current implementation. 
New implementation improve operation time to **10 seconds** in same environment by improving to call one api to get all table's column list.

## Related Tickets & Documents
- [BigQuery  Information Schema Reference](https://cloud.google.com/bigquery/docs/information-schema-tables)

New implementation uses every dataset's INFORMATION_SCHEMA. COLUMNS view to get table's column list in dataset.

### CODE REVIEW

**Comment by probably-not** [comment]
Any word on this? This can be a gigantic speedup in order to get schema information in huge BQ datasets.

**Review by susodapop — COMMENTED** [review]
This looks brilliant. Thank you for the contribution.

Since I'm not familiar with BigQuery I have a few questions before we merge it in. First, is this a drop-in replacement for the current implementation? Does it require any different settings or permissions for the service account Redash uses to connect? 

If it's exactly the same but faster that's ideal.

**Comment by katsugeneration** [comment]
@susodapop Thank you for your review. I answered your question.

> First, is this a drop-in replacement for the current implementation?

Yes. New implementation can get same schema information in same format as before about permitted datasets.

> Does it require any different settings or permissions for the service account Redash uses to connect?

No. New implementation require same permissions and settings to get bigquery schema and to run bigquery queries in redash now.
User who only get schema in redash need to add permission 'bigquery.jobs.create' , but this permmission is used for running bigquery queries even now.
So, I think no user changes settings in cause of new implementation.

**Comment by susodapop** [comment]
Sounds like we can change our guidance in our [documentation](https://redash.io/help/data-sources/querying/bigquery)

> If your database schema exceeds 5000 tokens, untick the Load Schema box to stop Redash from loading it to the Query Editor screen. Many browsers will slow down or crash if the schema is too big.

This is huge. Thank you!

**Pull request merged**
