### PR TITLE
Cleaner pytest results

### PR DESCRIPTION
**Pull request by rauchy**
## What type of PR is this? (check all applicable)
- [x] Refactor

## Description
Currently there's a lot of noise when running backend tests (which includes some deprecation warnings introduced by 3rd party packages, and the default pytest result renderer, which is basic)

This PR silences deprecations and includes [pytest-sugar](https://github.com/Teemu/pytest-sugar).

image

### CODE REVIEW

**Comment by arikfr** [comment]
I'm not sure about this one. While the warnings generate a lot of noise, we should consider if it will be feasible to address them instead of suppressing.

If we addressed some of them in time, we could've avoided the Werkzeug upgrade issue _(#4617)._

**Comment by rauchy** [comment]
@arikfr solid point, but are unit test executions really the place to raise these? The constant visual noise around these deprecation warnings isn't really pushing for developer happiness.

**Comment by arikfr** [comment]
Most of these warnings are repeating themselves. Any idea if there is a way to get an aggregated report about number and types of warnings raised during tests?

**Comment by rauchy** [comment]
Not sure, but we can hide third-party depreciation warnings in dev (while keeping direct deprecations) and only show them in CI. WDYT?

**Comment by arikfr** [comment]
If it's only in CI we can just disable it. We never look at the output there :-) That's why I thought of collecting aggregated numbers that we can show somewhere, so it's more on our mind.

**Comment by justinclift** [comment]
@guidopetri I've just fixed the merge conflict that was showing up, which might make this a bit easier for you.  Note that I just used the same version of `pytest-sugar` (so `0.9.2`) that was in the original PR, even though the other pytest related stuff uses newer versions.  It might be better to update the pytest-sugar package to a newer release as well (no idea personally). :smile:

**Comment by guidopetri** [comment]
I think we can set the warnings filter to `once` instead of `ignore` ([ref](https://docs.python.org/3/library/warnings.html#the-warnings-filter)). As for the `pytest-sugar` library, it seems recently revived and at `0.9.7` so we may as well update if we're going to add it in. I don't particularly care for it personally.

Let me try making those changes.

**Comment by guidopetri** [comment]
Wow, that's a lot of warnings. I'm going to try running this locally a few times to compare what it looks like with/without the `once` setting and with/without pytest-sugar, but I'll have to do this later.

**Comment by guidopetri** [comment]
Ok, so I'm not convinced that `pytest-sugar` makes any real difference (plus it's an additional dep), and switching from `ignore` -> `once` reduced the number of lines but not really by much. I'll remove the deps change and merge in the `once` change but I don't feel strongly either way.

**Review by guidopetri — APPROVED** [review]

**Comment by guidopetri** [comment]
I think this isn't passing codecov because it's 39 commits behind master, since it doesn't make sense for this change to change codecov. So once the e2e tests pass I'll merge in.

**Pull request merged**
