### PR TITLE
Bar chart with second y axis overlaps data series

### PR DESCRIPTION
**Pull request by kravets-levko**
## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Description

Assign `offsetgroup` for bar series so Plotly will offset them properly.

## Related Tickets & Documents

Fixes getredash/redash#2292

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

Before:
image

After (the same chart settings and data, but with `offsetgroup`):
image

### CODE REVIEW

**Comment by ranbena** [comment]
+556 −1,708  😲😛

**Comment by kravets-levko** [comment]
> Noticed in demo that some of the widget visualizations changed.

Yeah, I suppose it's because of `plotly.js` upgrade. Need to test it properly before merging.

> +556 −1,708

That's lockfile

**Comment by kravets-levko** [comment]
> Group Scatter (x axis labels hidden),  Labels (same)

I see x-axis labels there:

image
image

Bubble axis offset - yeah, that's quite interesting, considering that on both https://deploy-preview-4150--redash-preview.netlify.com/dashboard/demo and https://redash-preview.netlify.com/dashboard/demo it looks wrong :thinking: 

image
image

Heatmap difference may be related to my recent refactor, I'll check.

Also, seems there is a very subtle difference in plot inner paddings - they are a bit larger on this branch :thinking:

**Comment by ranbena** [comment]
I think it has to do with my screen resolution (width 1400px) so it now looks like this:

Screen Shot 2019-09-19 at 10 49 51
Screen Shot 2019-09-19 at 10 49 23


> Also, seems there is a very subtle difference in plot inner paddings

I noticed it but don't mind it. Not a dramatic change.

**Comment by kravets-levko** [comment]
@gabrieldutra @arikfr (@ranbena if you're still interested in this :smile:) I updated this PR and now it contains only changes related to the bug it's fixing (no more Plotly upgrade - we did it separately). I kindly ask you to review it once more :bowing_man: 

@arikfr If v9 will contain upgraded Plotly - maybe it makes some sense to include this fix as well? WDYT?

**Comment by orenpai** [comment]
+1 for pulling this one in, affected by this issue too. Thanks for your contribution!

**Pull request merged**
