### PR TITLE
Revert "Removed unused configuration class (#6682)"

### PR DESCRIPTION
**Pull request by eradman**
## What type of PR is this? 

- [x] Bug Fix
- [x] Revert

## Description

This reverts commit 97db4925317b65abefc957fe47cf83a95c772c53.

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

## Related Tickets & Documents

https://github.com/getredash/redash/issues/6954#issuecomment-2176999381

### CODE REVIEW

**Comment by eradman** [comment]
@zachliu this is to solve the upgrade problem from older versions of Redash. I was unable to verify this myself, but reverting makes sense to me since the reverted change was a refactoring which was untested.

**Comment by zachliu** [comment]
@eradman I verified it on my local build :rocket:

**Comment by justinclift** [comment]
That's a bit unclear.  Verified so "we should merge this", or verified so "we **shouldn't** merge this"?

**Comment by zachliu** [comment]
@justinclift I hereby solemnly verified the content in this PR so that we should merge it as soon as possible

**Comment by justinclift** [comment]
Thanks @zachliu. :wink:

**Review by justinclift — APPROVED** [review]

**Pull request merged**
