### PR TITLE
send ip and user id to sentry

### PR DESCRIPTION
**Pull request by rauchy**

### CODE REVIEW

**Comment by jezdez** [comment]
@arikfr @rauchy Could this also be made a setting?

**Comment by jezdez** [comment]
(I'm happy to write the patch)

**Comment by arikfr** [comment]
@jezdez ,

> Could this also be made a setting?

Sure. Although I think that sending the user id shouldn't be a setting. Just the IP address.

**Comment by jezdez** [comment]
> @jezdez ,
> 
> > Could this also be made a setting?
> 
> Sure. Although I think that sending the user id shouldn't be a setting. Just the IP address.

Yeah, the IP is critical in this case, the user ID less so.

**Pull request merged**
