### PR TITLE
adding gevent worker in requirements.txt, adding some gunicorn config…

### PR DESCRIPTION
**Pull request by ialeinikov**
* gevent is added to the requirements.txt
* some gunicorn configuration parameters are added with defaults

### CODE REVIEW

**Comment by jezdez** [comment]
We had a similar case in #2743 where we noted that it doesn't require a new env var and that `GUNICORN_CMD_ARGS`is enough to enable this ability. @ialeinikov Could you try it out please?

From http://docs.gunicorn.org/en/stable/settings.html:

> Settings can be specified by using environment variable GUNICORN_CMD_ARGS.
> All available command line arguments can be used. For example, to specify the bind 
> address and number of workers:
>
> $ GUNICORN_CMD_ARGS="--bind=127.0.0.1 --workers=3" gunicorn app:app
>
> New in version 19.7.

**Comment by arikfr** [comment]
Oops, I completely forgot about this. 😳

**Comment by arikfr** [comment]
Although this Pull Request adds `gevent` to the requirements, so maybe worth keeping.

**Comment by jezdez** [comment]
Yeah, the extra dependency is useful I guess, until we solve #2810 😃 OTOH using a custom `Dockerfile` with an added requirements installation step would work as well.

**Comment by arikfr** [comment]
@jezdez it's true that a custom Dockerfile with a single `RUN pip install gevent==...` line will do the trick. I think we will move to using the gevent workers as the default setup, so I don't mind adding it already.

**Comment by tonidas** [comment]
The performance is WAY better with gevent, there is no comparison between delegating a process to each request than delegating a thread. I've created a new redash image to add the dependency

Looking forward for this merge @ialeinikov !

**Comment by arikfr** [comment]
Thanks!

**Pull request merged**
