### PR TITLE
Add test class for JWT decoding

### PR DESCRIPTION
**Pull request by eradman**
## What type of PR is this? 

- [x] New unit tests

## Description

After asserting current functionality, https://github.com/getredash/redash/pull/6271 can be rebased and more easily evaluated.

### CODE REVIEW

**Comment by justinclift** [comment]
Cool, this sounds like a good idea. :smile:

**Comment by eradman** [comment]
CC @gaecoli

**Review by gaecoli — APPROVED** [review]
LGTM!

**Comment by justinclift** [comment]
Looks like there's an conflict that needs fixing now?

**Comment by eradman** [comment]
These tests were included in commit 0d699328b8272e35d8113c2405d2666910433d32, so I'll close this

**Pull request closed without merging**
