### PR TITLE
Cloudwatch Support

### PR DESCRIPTION
**Pull request by tahege**

### CODE REVIEW

**Comment by arikfr** [comment]
Hi 👋 

Why did you close this pull request?

**Comment by tahege** [comment]
Hi @arikfr 👋 

I meant to create this PR against our fork of the project and use it internally for a few weeks before merging it here. I want to get feedback from our internal stakeholders on this first to make sure what's here is a fully baked solution.

**Comment by RichardLitt** [comment]
Sounds good, @tahege. :) Looking forward to hearing back if you have any suggestions after you get feedback internally.

**Comment by arikfr** [comment]
Thanks, @tahege.

You implemented a few things here that will be great as separate pull requests. Like the ability to have a dropdown in dynamic forms.

**Pull request closed without merging**
