### PR TITLE
Fix: Alert condition rendering

### PR DESCRIPTION
**Pull request by ranbena**
- [x] Bug Fix

## Description
Since https://github.com/getredash/redash/pull/4240 alert conditions are no longer represented by a textual description but by chars. This caused templating (notification template and alert default name) to render differently.

This is a fix for that.

_|Before Fix|After Fix
------|------|------
Alert Edit|Screen Shot 2019-10-17 at 14 01 22|Screen Shot 2019-10-17 at 13 59 40
Email|Screen Shot 2019-10-17 at 14 03 45|Screen Shot 2019-10-17 at 14 03 52

(Yes, I know there's server-client code duplication https://github.com/getredash/redash/issues/4187)

### CODE REVIEW

**Comment by arikfr** [comment]
I'm not sure this is worth the extra complexity. Does it feel that important?

**Comment by ranbena** [comment]
> I'm not sure this is worth the extra complexity. Does it feel that important?

Was thinking that while working on it but I'm undecided. Up to you @arikfr.

**Comment by ranbena** [comment]
Maybe we can settle for fixing only the alert name and leave out template rendering.

**Comment by ranbena** [comment]
> I'm not sure this is worth the extra complexity. Does it feel that important?

Closing due to public disinterest.

**Pull request closed without merging**
