### PR TITLE
Use column types provided by server rather than trying to derive them from the values

### PR DESCRIPTION
**Pull request by Jakdaw**
## What type of PR is this? (check all applicable)

- [X] Bug Fix

## Description
For background see:

https://discuss.redash.io/t/hex-for-binary-data/4900/11

Be warned, first time I've touched Javascript!

Start using the column types in the JSON document rather than trying to derive them from the values. Now a MySQL query like SELECT "2019-01-01", date("2019-01-01"); will return a string and a date.

I don't think the 'float' thing was ever actually being set in the old logic; and I can't see what our require the JSON.stringify() logic.

### CODE REVIEW

**Comment by Jakdaw** [comment]
Ahem! and I've only actually tested this on the Redash8 branch... tho I don't think that's relevant in practice!

**Comment by gabrieldutra** [comment]
Hi @Jakdaw, saw your comment about the tests in the forum :slightly_smiling_face:.

Changing this line to use the `SELECT DATE('{{test-parameter}}') AS parameter` query should fix the failing tests:
https://github.com/getredash/redash/blob/aa06b32e17fa6377073f0cefa7fa95a7e9a21795/client/cypress/integration/query/parameter_spec.js#L260

There's also a change in a Percy snapshot that this should fix too:
https://github.com/getredash/redash/blob/aa06b32e17fa6377073f0cefa7fa95a7e9a21795/client/cypress/integration/visualizations/table/.mocks/all-cell-types.js#L8

using `TIMESTAMP '1995-09-03T07:45' AS "date",` instead.

LMK if you get any issues with it

**Comment by Jakdaw** [comment]
Thanks @gabrieldutra looks like that sorted it!

**Comment by guidopetri** [comment]
@Jakdaw , thanks for the PR! We've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI, as well as updating merge conflicts?

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Pull request closed without merging**
