### PR TITLE
Fix auto limit breaks for Oracle queries 

### PR DESCRIPTION
**Pull request by tim5go**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Bug Fix

## Description
Pull request #5088 introduced the ability to auto limit SQL results to the first 1000 results (#976). However, Oracle does not support the LIMIT clause. This PR is to handle auto limit clause in Oracle's syntax.

## Related Tickets & Documents
#5180 #5088

### CODE REVIEW

**Review by arikfr — COMMENTED** [review]
Thank you for taking a stab at this! I wonder if it will be "safer" to just turn off this functionality for Oracle?

**Comment by tim5go** [comment]
@arikfr 
Um... if we disable this functionality for Oracle, should we also hide the **Limit Checkbox** on the UI side for consistency?
Otherwise, people may get confused.

**Comment by kravets-levko** [comment]
@arikfr For me it looks that adding a limit should be implemented in query runners: some basic implementation in BaseQueryRuner, and then others may override it if needed.

**Comment by jhult** [comment]
For what it is worth, I merged @tim5go's code to my branch and can confirm the auto limit is working for Oracle.

**Comment by tim5go** [comment]
@kravets-levko 
I am refactoring the code according to your comments, will publish the changes very soon.

**Comment by jhult** [comment]
@tim5go and @kravets-levko, we need this fix. Right now, I have it merged locally but it would be great to have it upstream. Any news on getting this merged? It looks like it might need to be rebased on `master` first.

**Comment by tim5go** [comment]
@jhult 
yup, it seems like it needs a rebase first.
For my part, I have nothing to add. I definitely would like to have it merged, but it's really up to the **Redash** team.

**Comment by jhult** [comment]
@kravets-levko, any chance we can get this merged?

**Comment by jhult** [comment]
@rafawendel @kravets-levko @susodapop @arikfr,

Any news on merging this?

**Comment by susodapop** [comment]
Hey @jhult we'll plan to merge this after the full V10 release later this summer. 

PS we're also working to improve the contribution process and review SLA going forward 😉  Thanks for your patience.

**Comment by jhult** [comment]
@susodapop, now that version 10 is out, any updates on getting this merged?

**Comment by jhult** [comment]
@susodapop, glad to see you self-assign this. Hopefully this means it can be merged soon.

**Review by susodapop — APPROVED** [review]
Thanks for your hard work on this! I've tested locally and rebased onto the latest master. Once the CircleCI build completes we're good to merge.

**Comment by susodapop** [comment]
There's a failing test: 

```
________________________________________________________________________________ TestRenderTemplate.test_render _________________________________________________________________________________

self = <tests.test_utils.TestRenderTemplate testMethod=test_render>

    def test_render(self):
        app = create_app()
        with app.app_context():
            d = {"failures": [{"id": 1, "name": "Failure Unit Test", "failed_at": "May 04, 2021 02:07PM UTC", "failure_reason": "", "failure_count": 1, "comment": None}]}
            html, text = [
                render_template("emails/failures.{}".format(f), d)
                for f in ["html", "txt"]
            ]
>           self.assertIn('Failure Unit Test',html)
E           TypeError: argument of type 'NoneType' is not iterable

tests/test_utils.py:93: TypeError
```

Researching now

**Comment by susodapop** [comment]
The failure was my mistake. I omitted a `return` statement during the rebase 🤦 . Build is proceeding normally now.

**Comment by jhult** [comment]
@susodapop,

Looks like it built successfully!

**Pull request merged**
