### PR TITLE
Payment ratio

### PR DESCRIPTION
**Pull request by JulianXie**
base

### CODE REVIEW

**Comment by tonyjiangh** [comment]
@JulianXie 
Are you sure you understand what you are doing here? It seems that something wrong is happening here?
你确定你知道你在干嘛吗？你是不是不小心把本地fork的内容给不慎公开了啊？

**Comment by JulianXie** [comment]
sorry ,mistake

**Comment by tonyjiangh** [comment]
Just realized that my wording was wierd & hard. Sorry about that.
Wish you enjoy redash :)

**Comment by RichardLitt** [comment]
Thank you again, @JulianXie! Please feel free to open more PRs. :)

**Pull request closed without merging**
