### PR TITLE
Remove importlib-resources from requirements.txt

### PR DESCRIPTION
**Pull request by eradman**
This is not required for Python >= 3.8 since the goal of this project is to back port functionality.  Also the version specified is not compatible with later versions of Python.

## What type of PR is this? 

- [x] Upgrade

## How is this tested?

- [x] Unit tests (pytest, jest)

## Related Tickets & Documents

https://pypi.org/project/importlib-resources/

### CODE REVIEW

**Comment by eradman** [comment]
I respectfully disagree with codecov!

**Comment by guidopetri** [comment]
Could we wait on this since we're removing these files and moving to poetry anyway?

**Comment by eradman** [comment]
Apologies @guidopetri I missed your comment. Feel free to revert if you think that's easier

**Comment by guidopetri** [comment]
Nah all good, I commented at the same time you merged. I'll make the change later in the poetry pr

**Pull request merged**
