### PR TITLE
Add a description field to a dashboard

### PR DESCRIPTION
**Pull request by kyoshidajp**
Add a description field to a dashboard like a query's one.

# Screenshot

## Edit dialog

before
dashboard_before

after
dashboard_after2

## Detail page

| before | after |
| ------ | ----- |
| dashboard_detail_before | dashboard_after |

### CODE REVIEW

**Comment by deecay** [comment]
Can this handle Markdown? I was thinking of using this feature like "For more details go [here](dummy)".

**Comment by arikfr** [comment]
@deecay I'm not sure it should. And you can always add a textbox widget for such thing.

**Comment by deecay** [comment]
@arik Yeah that's true, but textbox widget always takes 185px hight (one 'block' of grid, I guess?). It's a bit of an overkill for a oneliner description. Maybe a lower min-height of textbox widget is what I want.

**Comment by arikfr** [comment]
Maybe :)

**Comment by arikfr** [comment]
Hi,

(This is a template message, but I mean every word of it. Also you're welcome to reply)

Thank you for making this contribution. While we couldn't bring it to completion and merge, it's still very much appreciated. 🙇

In the past year the Redash code base gone under massive updates: on the backend we moved to Python 3 & RQ instead of Celery and on the frontend we replaced Angular with React. It's very likely this makes this PR irrelevant without significant changes. :-( 

I'm closing this PR now. But if you're still interested in making it happen, let me know and I will reopen.

Thanks.

**Pull request closed without merging**
