### PR TITLE
flatten all level

### PR DESCRIPTION
**Pull request by KimBioInfoStudio**
the original code only flatten 2d-dict, if there are some dict more than 2d, hard to qurey data and viz

TODO:
- [x] add a option btn to enable/disable this feature

### CODE REVIEW

**Comment by justinclift** [comment]
@KimBioInfoStudio Heya, there's no description for this PR. :wink:

Um... why is flattening stuff useful for MongoDB?

**Comment by KimBioInfoStudio** [comment]
> @KimBioInfoStudio Heya, there's no description for this PR. 😉
> 
> Um... why is flattening stuff useful for MongoDB?

in the original code, only 2d dict was faltten, but my data struct have 4d dict like, it's hard for me to query on low level and viz on love level:

```json
{ 
"a":"aa",
"b":["bb1","bb2","bb3","bb4"]
"c":{
"cc1"：["cc11","cc12","cc13"],
"cc2": {"cc21k":"cc21v"}
}
}
```

**Comment by justinclift** [comment]
@AndrewChubatiuk @eradman What do you both think of this?

I'm concerned that this will potentially break things for existing users of MongoDB.

If that's not likely to happen though, then this might be ok. :smile:

**Comment by KimBioInfoStudio** [comment]
> @AndrewChubatiuk @eradman What do you both think of this?
> 
> I'm concerned that this will potentially break things for existing users of MongoDB.
> 
> If that's not likely to happen though, then this might be ok. 😄

u r right, if the option is not configureable, this will break existing mongodb users

**Comment by justinclift** [comment]
That sounds like a problem. :wink:

**Comment by AndrewChubatiuk** [comment]
Hey @KimBioInfoStudio 
Nice feature
LGTM

**Comment by justinclift** [comment]
Thanks for completing this @KimBioInfoStudio, and thanks @AndrewChubatiuk for reviewing. :smile:

**Review by justinclift — APPROVED** [review]
Going with @AndrewChubatiuk's review conclusion. :wink:

**Pull request merged**
