### PR TITLE
Adds ssl support for prometheus query runner.

### PR DESCRIPTION
**Pull request by fabrei**
- Adds possibilty to upload and use of ssl cert, key and ca file in redash ui

## What type of PR is this? 

- [x] Feature

## Description

All versions are compatible.

## How is this tested?

- [x] Manually

1. Created a new prometheus data source.
2. Filled out necessary fields.
3. Uploaded ssl cert, key and ca file.
4. Saved data source.
5. Clicked on "Test Connection".

## Related Tickets & Documents

Asked in [discussions](https://github.com/getredash/redash/discussions/6655) to add this feature without issue.

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

image

### CODE REVIEW

**Comment by masayuki038** [comment]
Hi @fabrei, thanks for your PR.

Your update seems to have some points not covered by the unit test. Can I add tests?

**Comment by fabrei** [comment]
> Hi @fabrei, thanks for your PR.
> 
> Your update seems to have some points not covered by the unit test. Can you add tests?

Hi @masayuki038,

I added some tests. Hope it works now with test coverage :)

**Comment by fabrei** [comment]
Ah, damn the timezone O_o

The prometheus query runner does not use any timezone while calculating start and end time. It uses the local timezone on the system. In the CI it is UTC, which differs from my local one.

**Comment by fabrei** [comment]
> Ah, damn the timezone O_o
> 
> The prometheus query runner does not use any timezone while calculating start and end time. It uses the local timezone on the system. In the CI it is UTC, which differs from my local one.

Now the testcases should be fixed.

**Review by masayuki038 — APPROVED** [review]
@fabrei Thanks for your updates! It is very helpful.
Looks good from my end. Please wait for a few days.

@guidopetri @konnectr Could you check this if you have some time?

**Comment by masayuki038** [comment]
I am going to merge this since there are no issues.

**Pull request merged**
