### PR TITLE
 Receive communication error when Athena returns NaN value

### PR DESCRIPTION
**Pull request by kravets-levko**
Issue getredash/redash#2544

Solution: use `simplejson` instead of `json` to dump query results; `simplejson` can replace `NaN`/`Infinity` values with `null`

### CODE REVIEW

**Comment by arikfr** [comment]
We should probably switch to simple_json everywhere. I just wonder how can we make sure this is the right decision?

**Comment by jezdez** [comment]
@arikfr I would argue that we should maybe look for a faster and/or better json implementation than simplejson given the amount of serialization/deserialization happening allover Redash.

There are some precedence discussing [benchmarks](https://python-rapidjson.readthedocs.io/en/latest/benchmarks.html), [other benchmarks](https://artem.krylysov.com/blog/2015/09/29/benchmark-python-json-libraries/), [memory consumption](https://blog.ionelmc.ro/2015/11/22/memory-use-and-speed-of-json-parsers/) (!) and [many](https://pypi.org/project/ujson/), [many](https://pypi.org/project/yajl/), [many](https://github.com/mre/hyperjson) more. OTOH [simplejson](https://github.com/simplejson/simplejson) is the real thing and has been maintained for a while now.

**Comment by arikfr** [comment]
@jezdez thank you for the pointers! You're definitely right that we will benefit from a more performant (and memory efficient) JSON implementation.

From reading the [memory consumption blogpost](https://blog.ionelmc.ro/2015/11/22/memory-use-and-speed-of-json-parsers/), it looks like simplejson has the best memory consumption for a JSON that's more similar to what we usually have:

```
Peak memory usage (Python 2.7):

      simplejson: 1,171.7 Mb
           cjson: 1,304.2 Mb
            yajl: 1,457.1 Mb
            json: 1,468.0 Mb
       rapidjson: 1,561.6 Mb
        jsonlib2: 2,134.9 Mb
         jsonlib: 2,137.0 Mb
           ujson: 2,149.9 Mb
```

Also based on the same blog post, it seems like that only relevant alternative is `ujson` (considering stability), but it doesn't seem to support all the options we need...

**Comment by jezdez** [comment]
@arikfr Excellent, I hadn't looked as closely, that seals it. Do you want me to work on a patch?

**Comment by arikfr** [comment]
You're always welcome to :)

**Pull request merged**
