### PR TITLE
Support multi column results with using mongo query runner

### PR DESCRIPTION
**Pull request by del-zhenwu**
## What type of PR is this? (check all applicable)

- [x] Other

## Description
Support the following queries for results parser when using mongodb:
```
    "fields": {
        "run_id": 1,
        "metrics.value.acc": 2
    },
```
We currently only support for two levels in `fields`

### CODE REVIEW

**Comment by del-zhenwu** [comment]
still in reviewing?

**Comment by guidopetri** [comment]
@del-zhenwu , thanks for the PR! We've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI?

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Comment by del-zhenwu** [comment]
The new PR https://github.com/getredash/redash/pull/6290

**Comment by justinclift** [comment]
I'll close this PR now, as the new one is available. :smile:

**Pull request closed without merging**
