### PR TITLE
fix: increase the default gunicorn timeout

### LINKED ISSUE #5782: Default gunicorn timeout (30s) is not enough with some heavier configurations
### Issue Summary

Trying to deploy redash to kubernetes with helm-chart fails, because gunicorn workers takes some time to spin-up. Gunicorn has 30 second timeout for workers by default. If workers are not responsive after this time, they are killed. In result, redash cannot properly start on kubernetes with some heavier configuration:

```
2022-07-06 12:17:01.916 CEST

redash-server
Using external postgresql database
2022-07-06 12:17:01.916 CEST

redash-server
Using Redis: redis://:******@redash-redis-master:6379/0
2022-07-06 12:17:04.450 CEST

redash-server
[2022-07-06 10:17:04 +0000] [7] [INFO] Starting gunicorn 20.0.4

2022-07-06 12:17:04.451 CEST

redash-server
[2022-07-06 10:17:04 +0000] [7] [INFO] Listening at: http://0.0.0.0:5000 (7)
2022-07-06 12:17:04.451 CEST

redash-server
[2022-07-06 10:17:04 +0000] [7] [INFO] Using worker: sync
2022-07-06 12:17:04.454 CEST

redash-server
[2022-07-06 10:17:04 +0000] [10] [INFO] Booting worker with pid: 10
2022-07-06 12:17:04.538 CEST

redash-server
[2022-07-06 10:17:04 +0000] [11] [INFO] Booting worker with pid: 11
2022-07-06 12:17:04.623 CEST

redash-server
[2022-07-06 10:17:04 +0000] [12] [INFO] Booting worker with pid: 12
2022-07-06 12:17:04.723 CEST

redash-server
[2022-07-06 10:17:04 +0000] [13] [INFO] Booting worker with pid: 13
2022-07-06 12:17:34.917 CEST

redash-server
[2022-07-06 10:17:34 +0000] [7] [CRITICAL] WORKER TIMEOUT (pid:10)
2022-07-06 12:17:34.917 CEST

redash-server
[2022-07-06 10:17:34 +0000] [7] [CRITICAL] WORKER TIMEOUT (pid:11)
2022-07-06 12:17:34.920 CEST

redash-server
[2022-07-06 10:17:34 +0000] [11] [INFO] Worker exiting (pid: 11)
2022-07-06 12:17:34.921 CEST

redash-server
[2022-07-06 10:17:34 +0000] [7] [CRITICAL] WORKER TIMEOUT (pid:12)
2022-07-06 12:17:34.922 CEST

redash-server
[2022-07-06 10:17:34 +0000] [7] [CRITICAL] WORKER TIMEOUT (pid:13)
2022-07-06 12:17:34.923 CEST

redash-server
[2022-07-06 10:17:34 +0000] [10] [INFO] Worker exiting (pid: 10)
2022-07-06 12:17:34.931 CEST

redash-server
[2022-07-06 10:17:34 +0000] [13] [INFO] Worker exiting (pid: 13)
2022-07-06 12:17:34.941 CEST

redash-server
[2022-07-06 10:17:34 +0000] [12] [INFO] Worker exiting (pid: 12)
2022-07-06 12:17:36.025 CEST

redash-server
[2022-07-06 10:17:36 +0000] [22] [INFO] Booting worker with pid: 22
2022-07-06 12:17:36.123 CEST

redash-server
[2022-07-06 10:17:36 +0000] [23] [INFO] Booting worker with pid: 23
2022-07-06 12:17:36.224 CEST

redash-server
[2022-07-06 10:17:36 +0000] [24] [INFO] Booting worker with pid: 24
2022-07-06 12:17:36.224 CEST

redash-server
[2022-07-06 10:17:36 +0000] [25] [INFO] Booting worker with pid: 25
2022-07-06 12:18:06.413 CEST

redash-server
[2022-07-06 10:18:06 +0000] [7] [CRITICAL] WORKER TIMEOUT (pid:22)
2022-07-06 12:18:06.414 CEST

redash-server
[2022-07-06 10:18:06 +0000] [7] [CRITICAL] WORKER TIMEOUT (pid:23)
2022-07-06 12:18:06.414 CEST

redash-server
[2022-07-06 10:18:06 +0000] [7] [CRITICAL] WORKER TIMEOUT (pid:24)
2022-07-06 12:18:06.414 CEST

redash-server
[2022-07-06 10:18:06 +0000] [7] [CRITICAL] WORKER TIMEOUT (pid:25)
```

### Steps to Reproduce

1. Install redash from https://github.com/getredash/contrib-helm-chart
2. Make some heavier configuration.
3. Restart redash server instance

Raising gunicorn timeout to 60 seconds solves the problem. 

### Technical details:

* Redash Version: 10.0.0
* Browser/OS: n/a
* How did you install Redash: https://github.com/getredash/contrib-helm-chart

### PR DESCRIPTION
**Pull request by jacek-jablonski**
fixes #5782

## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [x] Manually
- [ ] N/A

Rolled out on kuberenetes. Redash-server works successfully

### CODE REVIEW

**Review by susodapop — APPROVED** [review]
LGTM. Thanks!

**Comment by aberenshtein** [comment]
@susodapop when do you plan to release it?
I'm also running on k8s and the latest version is 8 months old

**Comment by aberenshtein** [comment]
@jacek-jablonski what k8s version are you running?
Were you able to test this fix?

**Comment by jacek-jablonski** [comment]
> @jacek-jablonski what k8s version are you running? Were you able to test this fix?

K8s 1.21, 1.22 and 1.23. Yes, this fix worked for me.

**Comment by susodapop** [comment]
The k8s chart is a volunteer effort. We on the core team have no involvement with it. 

Redash V11 will release later this summer.

**Pull request merged**
