### PR TITLE
Set height for .counter-visualization-container to 300px

### PR DESCRIPTION
**Pull request by eradman**
## What type of PR is this? 

- [x] Refactor

## Description

- Set font size back to px to match most other CSS
- Font calculation made based on counter-visualization-container, not an inner div
- Decrease font size by 30% if optional target value is displayed
- Scale counter fontSize using power(0.5)
- Set embedded counter height to 100%

## How is this tested?

- [x] Manually

## Related Tickets & Documents

https://github.com/getredash/redash/discussions/6542

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

redash-counters-2-line-3-line

### CODE REVIEW

**Comment by justinclift** [comment]
@myonlylonely Are you ok to try this PR out? :smile:

**Comment by myonlylonely** [comment]
The size in the embed query has been corrected.👍
In embed query:
Original:
image
After this PR:
image

@justinclift But in the dashboard, it is still smaller than before.

In dashboard:
Original:
image
After this PR:
image

**Comment by justinclift** [comment]
Heh Heh Heh.  Seems like it's heading in the right direction at least. :wink:

**Comment by eradman** [comment]
Yeah, this is promising. I added a second commit with an updated method of scaling the fontSize

**Comment by myonlylonely** [comment]
I tried the new commit. The size in dashboard become bigger than the first commit, but still smaller than the original.
Original:
image
The new commit:
image

Also, I found that resize the embed query to a smaller size, the number is cut.
image

**Comment by eradman** [comment]
>  I found that resize the embed query to a smaller size, the number is cut

Good catch, I fixed this. There are some special rules for embeded queries set by the `.query__vis` class 

>  The size in dashboard become bigger than the first commit, but still smaller than the original

This is not true. In Redash 10 the counter content scalled down with the content, so a few characters would appear large, and a long string would be small

**Comment by eradman** [comment]
Forced-update to this branch to make the total diff easier to see

**Comment by myonlylonely** [comment]
The embeded queries is now fixed! 👍

> > The size in dashboard become bigger than the first commit, but still smaller than the original
> 
> This is not true. In Redash 10 the counter content scalled down with the content, so a few characters would appear large, and a long string would be small

No, I think it is related to the "Visualization Name" label. In original Redash 10, if I delete the "Visualization Name" (empty string), the number will be scalled to a nice bigger size.

The screen in original Redash 10, with or without "Visualization Name":
image

**Comment by justinclift** [comment]
Heh, sounds like we're making solid progress.

As an aside - wow, this has turned out to be way more complicated than it first looked eh? :smile:

**Comment by eradman** [comment]
Indeed! This is much more involved than it seemed at first

**Comment by eradman** [comment]
This change was updated again after having reverted "Render counter widgets using relative font size" (8b8dd4f68c8dc63ac15c14d270f4cf7b72c9eeee)

**Comment by eradman** [comment]
I will apply this patch to an internal Redash build. Closing in favor of the discussion https://github.com/getredash/redash/discussions/6542

**Pull request closed without merging**
