### PR TITLE
Add verify option to JSON datasource runner to allow skipping certificate verification

### PR DESCRIPTION
**Pull request by kevinchiang**
## What type of PR is this? (check all applicable)

- [x] Feature

## Description

Many internal endpoints are secured through SSL with an internal certificate authority.  By adding the "verify" option to be passed through the request_options, we can allow the requests library to skip SSL certificate verification.

## Mobile & Desktop Screenshots/Recordings (if there are UI changes).

Screen Shot 2020-10-14 at 6 41 30 PM

### CODE REVIEW

**Review by arikfr — APPROVED** [review]

**Comment by arikfr** [comment]
Thanks for the PR & for updating the docs 👍

**Comment by ChrisMagnuson** [comment]
I am having the same issues talked about on [this discourse thread](https://discuss.redash.io/t/json-query-certificate-verify-failed-on-self-signed-certificate/9371) that would be resolved by this pull request being merged so that self signed certificates can be used when a query specifies a `url:`.

It looks like something went wrong with the automated build of this pull request, can someone with authority to rerun the process please take a look at this so it can hopefully be merged in?

**Comment by susodapop** [comment]
Closing this PR after merging #5690. Not sure why circleCI wouldn't reset. Thank you so much for this contribution!

**Comment by kevinchiang** [comment]
Thanks!

**Pull request closed without merging**
