### PR TITLE
change default allow custom chart to true

### PR DESCRIPTION
**Pull request by gaecoli**
## What type of PR is this? 

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

### CODE REVIEW

**Comment by gaecoli** [comment]
@justinclift Change default custom chart to true.

**Comment by justinclift** [comment]
Cool, hopefully this makes the custom chart feature a easier for people to get into. :smile:

**Comment by justinclift** [comment]
@gaecoli The website "Environment Variables" page should be updated with this change too.

* https://redash.io/help/open-source/admin-guide/env-vars-settings
* https://github.com/getredash/website/blob/master/src/pages/kb/open-source/admin-guide/env-vars-settings.md

**Comment by gaecoli** [comment]
> @gaecoli The website "Environment Variables" page should be updated with this change too.
> 
> * https://redash.io/help/open-source/admin-guide/env-vars-settings
> * https://github.com/getredash/website/blob/master/src/pages/kb/open-source/admin-guide/env-vars-settings.md

OK!

**Pull request merged**
