### PR TITLE
ci: use docker/build-push-action

### PR DESCRIPTION
**Pull request by watarukura**
## What type of PR is this? 

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [x] N/A

## Related Tickets & Documents

https://discord.com/channels/1029619790563790848/1029619790563790851/1148007830805282958
>sid (gh:guidopetri) — 2023/09/04 06:33
@JustinClift i think we can simplify the .ci/docker_build file away. there's a build-and-push github action that we can use, e.g. https://github.com/stringer-rss/stringer/blob/main/.github/workflows/build.yml#L44-L56 , which can a) run conditionally on branches b) build across platforms and c) use caching automatically, which will improve our build times dramatically. i'd also be surprised if we couldn't set it to only build / push if the docker secrets are available
(i wrote that CI yaml recently, but i'm not super familiar with gh actions)

sid's idea is very good, I want to new preview docker image.

### CODE REVIEW

**Comment by watarukura** [comment]
lint check by https://github.com/rhysd/actionlint

```shell
❯ pwd
/Users/watarukura/src/github.com/watarukura/redash/.github/workflows
❯ actionlint -verbose ci.yml
verbose: Linting ci.yml
verbose: Using project at /Users/watarukura/src/github.com/watarukura/redash
verbose: Found 0 parse errors in 0 ms for ci.yml
verbose: Found total 0 errors in 717 ms for ci.yml
```

**Comment by justinclift** [comment]
Thanks, that looks like the right kind of thing. :smile:

**Comment by justinclift** [comment]
Ahhh.  This looks like it's failing when the `DOCKER_USER` or `DOCKER_PASS` variables aren't set.  Is there any way to have this skip build action without causing a failure, when they're not set?

Asking because it's kind of important.  Anyone that forks this repo isn't going to have those set in their repository, so their CI will immediately start throwing errors if we don't somehow work around the problem. :smile:

**Comment by watarukura** [comment]
OK, please wait...

**Comment by justinclift** [comment]
The concept seems ok, but it looks like you need some quote characters added. :smile:

**Comment by justinclift** [comment]
k, this looks good.  We can't test things out completely until @arikfr adds the login credentials to our GitHub settings, but that can come later on.

Thanks for getting this done @watarukura. :smile:

**Comment by watarukura** [comment]
@justinclift Thanks for great help!

**Comment by guidopetri** [comment]
This is awesome, thanks so much @watarukura !

**Pull request merged**
