### PR TITLE
fix flake8

### PR DESCRIPTION
**Pull request by konnectr**
## What type of PR is this? 

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

### CODE REVIEW

**Review by zhongjiajie — APPROVED** [review]
I think we should pin flake8 in our ci to keep it stable

**Comment by justinclift** [comment]
We have a "pre-commit" hook which does format things automatically before creating the commit... but only if the developer has set it up.

**Comment by konnectr** [comment]
> We have a "pre-commit" hook which does format things automatically before creating the commit... but only if the developer has set it up.

flake8 is not in pre-commit

**Comment by konnectr** [comment]
I think he should be here.
https://github.com/getredash/redash/blob/master/.pre-commit-config.yaml

**Comment by justinclift** [comment]
Oh.  Just checked and you're right.  My misunderstanding, sorry. :angel:

**Comment by justinclift** [comment]
Well, put it in a PR and we can try it out. :smile:

**Comment by zhongjiajie** [comment]
> I think he should be here.
> https://github.com/getredash/redash/blob/master/.pre-commit-config.yaml

One more thing we have to know, we should keep package version same as ci and pre-commit but we do not, it will install the latest in our ci https://github.com/getredash/redash/blob/fbe2f4d80895ea3a450dc3193c5fa45e81700812/.github/workflows/ci.yml#L19-L22  and have pin version in pre-commit https://github.com/getredash/redash/blob/ae29eb3dfbb5278d88f05389e68ede7f8a9c360a/.pre-commit-config.yaml#L1-L10

**Comment by zhongjiajie** [comment]
I find out we use many thing to format out code, we have pre-commit, and makefile wrapper the pre-commit, and we use separate lint check in ci, IMO we should keep them consistency to avoid our ci crash

**Comment by konnectr** [comment]
> > I think he should be here.
> > https://github.com/getredash/redash/blob/master/.pre-commit-config.yaml
> 
> One more thing we have to know, we should keep package version same as ci and pre-commit but we do not, it will install the latest in our ci
> 
> https://github.com/getredash/redash/blob/fbe2f4d80895ea3a450dc3193c5fa45e81700812/.github/workflows/ci.yml#L19-L22
> 
> and have pin version in pre-commit
> https://github.com/getredash/redash/blob/ae29eb3dfbb5278d88f05389e68ede7f8a9c360a/.pre-commit-config.yaml#L1-L10

You're right, I added the CI version.

**Comment by konnectr** [comment]
> I find out we use many thing to format out code, we have pre-commit, and makefile wrapper the pre-commit, and we use separate lint check in ci, IMO we should keep them consistency to avoid our ci crash

The goal now is to release a new version, I think after that you can do refactoring.

**Comment by zhongjiajie** [comment]
> > I find out we use many thing to format out code, we have pre-commit, and makefile wrapper the pre-commit, and we use separate lint check in ci, IMO we should keep them consistency to avoid our ci crash
> 
> The goal now is to release a new version, I think after that you can do refactoring.

I find out we do not release our version to pypi, do we have a plan to release to it now?

**Comment by zhongjiajie** [comment]
BTW, is there any things I can help for releasing? like bugfix or something like that

**Comment by konnectr** [comment]
> BTW, is there any things I can help for releasing? like bugfix or something like that

We communicate in discord https://discord.gg/CmRZB9Rz You can ask there how you can help. But now we are updating the frotend dependencies

**Comment by justinclift** [comment]
@zhongjiajie There is a lot of stuff to get done, so we can definitely use more assistance. :smile:

Do you have skill with front end stuff like React, as well as Python? :smile:

Asking about React because I'm trying to fix some front end stuff, but my skill level with it is not high. :roll_eyes:

**Comment by zhongjiajie** [comment]
> @zhongjiajie There is a lot of stuff to get done, so we can definitely use more assistance. 😄
> 
> Do you have skill with front end stuff like React, as well as Python? 😄
> 
> Asking about React because I'm trying to fix some front end stuff, but my skill level with it is not high. 🙄
> 
> --
> 
> If you are more familiar with Python instead, then please help look through all of the old, open PRs. We need to determine which ones are still useful, which ones need fixing, which ones should be closed (etc). Any of that would be super helpful. 😄

I am not familiar with front end develop, ok I will see some pr for python side

**Comment by justinclift** [comment]
Awesome. :smile:

**Pull request merged**
