### PR TITLE
New ElasticSearch Query Runner

### PR DESCRIPTION
**Pull request by susodapop**
## What type of PR is this? 

- [x] New Query Runner (Data Source) 
- [x] Other

## Description

This PR incorporates the excellent work from #4391 with adjustments in #5701. I rebased from `master` and applied both patches to retain everyone's commit attributions.

These changes have been reviewed twice and approved but were never merged. Here's hoping the third time's the charm.

In addition to those commits, I have deprecated the original `elasticsearch` query runner. Existing connections will continue to exist.

## How is this tested?

- [x] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [x] Manually
- [ ] N/A

Unending thanks to @nicolaslm and @wwl717195673 for their unit and manual testing.

I also manually tested the deprecation:
1. Create an `elasticsearch` data source 
2. Apply `deprecated=True` commit and reload UI3. 
3. DS from step 1 is still visible
4. Create `elasticsearch2` database 
5. Check contents of `data_sources` table

CleanShot 2022-07-19 at 21 49 51@2x
CleanShot 2022-07-19 at 21 50 05@2x

#### Data source selection screen:

CleanShot 2022-07-19 at 21 50 24@2x

### CODE REVIEW

**Comment by susodapop** [comment]
@wwl717195673 Can you please give this a look to make sure my one change looks good? The only change was to remove the dedicated `run_query` method from `XPackSQLElasticSearch` since it was identical `ElasticSearch2`.

**Comment by wwl717195673** [comment]
> @wwl717195673 Can you please give this a look to make sure my one change looks good? The only change was to remove the dedicated `run_query` method from `XPackSQLElasticSearch` since it was identical `ElasticSearch2`.

That's good.Both run_query methods are totally same.You can remove it.

**Comment by susodapop** [comment]
Thanks! I'm just fixing the logos rendering next and this will be good as gold 👌

**Comment by susodapop** [comment]
Alright, I have fixed the logos and deprecated `elasticsearch`. @wwl717195673 can you give this a final look before I merge?

**Comment by wwl717195673** [comment]
> Alright, I have fixed the logos and deprecated `elasticsearch`. @wwl717195673 can you give this a final look before I merge?

I have reviewed the code.That's awesome!!!

**Comment by JCWahoo** [comment]
How do I get the new query runner? I pulled latest and didnt see the UI changes

**Comment by susodapop** [comment]
Which "latest" did you pull?

**Comment by JCWahoo** [comment]
The 10.1.0 docker image

**Comment by susodapop** [comment]
10.1 was released last year so it won't include changes merged since then 😉 

If you want the latest preview build that includes this query runner you can use the [preview image](https://hub.docker.com/r/redash/redash/tags) or you can wait for the V11 release later this summer.

Another way to solve would be to `curl` the latest query_runner onto your docker host, write your own dockerfile that copies this query runner over the old one (I don't recommend this).

**Comment by JCWahoo** [comment]
Ah yes, should've opened my eyes on that one :-)

Many thanks! Gonna check out the preview release

**Pull request merged**
