### PR TITLE
Adds influxdb v2 query runner.

### PR DESCRIPTION
**Pull request by fabrei**
- Adds test cases
- Adds influxdb v2 icon
- Updates python dependencies

## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description

It uses influxdb-client python library which is compatible with influxdb v2. 

It supports ssl connection to influxdb as well.

## How is this tested?

- [x] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

## Related Tickets & Documents

#5391

### CODE REVIEW

**Review by masayuki038 — CHANGES_REQUESTED** [review]
@fabrei Regarding updates, it looks good from my end.

Did you run a manual test? I don't have InfluxDB2 env. So, I will rely on the results of your manual tests.

And please add "InfluxDB2" (I don't know a formal name) in https://github.com/getredash/redash#supported-data-sources.

**Comment by fabrei** [comment]
> @fabrei Regarding updates, it looks good from my end.
> 
> Did you run a manual test? I don't have InfluxDB2 env. So, I will rely on the results of your manual tests.

Yes, I tested the query runner manually with an influx database version 2. I tested it, with and without using ssl. It worked fine for me.

> And please add "InfluxDB2" (I don't know a formal name) in https://github.com/getredash/redash#supported-data-sources.

I added it, but used "InfluxDBv2", so that it's clear, that it's a query runner for influx database version 2.

**Review by masayuki038 — APPROVED** [review]
@fabrei Thanks for your reply. It is okay from my end.

@guidopetri Please review this PR if you have some time.

**Comment by masayuki038** [comment]
@TobiasGrether This is in a `1-week-review`. I think this will be merged in a few days if there are no issues.

**Comment by masayuki038** [comment]
There were no issues in `1-week-review`. I am going to merge this.

**Pull request merged**
