### PR TITLE
add pre-commit

### PR DESCRIPTION
**Pull request by junnplus**
## What type of PR is this? 

We need to provide a unified formatting method before submitting the code.

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [x] Other

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

### CODE REVIEW

**Comment by justinclift** [comment]
If we add this, should we update our "Local dev setup" wiki page with some installation steps for it?

**Comment by junnplus** [comment]
> If we add this, should we update our "Local dev setup" wiki page with some installation steps for it?

Yes

**Comment by gaecoli** [comment]
I don't seem to see a wiki on how to use it.

**Comment by junnplus** [comment]
> I don't seem to see a wiki on how to use it.

If it is merged, I will update the wiki page.

**Comment by gaecoli** [comment]
> > I don't seem to see a wiki on how to use it.
> 
> If it is merged, I will update the wiki page.


Cool! But i don't have much experience with this, I'll try to use it if merged. I have no opinion.
You can request @justinclift review it.

**Comment by justinclift** [comment]
@junnplus If we merge this, what are the benefits we're hoping for? :smile:

**Comment by junnplus** [comment]
> @junnplus If we merge this, what are the benefits we're hoping for? 😄

Guide the code submitter to submit formatted code, which is beneficial for ensuring code quality.

**Comment by justinclift** [comment]
Oh well.  I guess we can try it out and see how it goes. :smile:

**Review by justinclift — APPROVED** [review]
Sure, lets try it out. :smile:

**Comment by justinclift** [comment]
> If it is merged, I will update the wiki page.

@junnplus When you have some time, would you be ok to do that update? :smile:

**Comment by junnplus** [comment]
> When you have some time, would you be ok to do that update? 😄

I will update it in the next few days.

**Comment by junnplus** [comment]
@justinclift https://github.com/getredash/redash/wiki/Local-development-setup#configuring-pre-commit I have updated the usage of pre-commit configuration.

**Comment by justinclift** [comment]
Awesome.  Good stuff @junnplus. :smile:

**Pull request merged**
