### PR TITLE
Switch from numeral to numbro

### PR DESCRIPTION
**Pull request by eradman**
numeraljs is no longer maintained, and incorrectly parses high-precision floats (such as 1.2e-7) as _NaN_.

## What type of PR is this? 

- [x] Bug Fix

## How is this tested?

- [x] viz-lib yarn tests
- [x] manually

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

**Current behavior using numeral.js**

redash_float_number_numbro

**New behavior using numbro.js**

redash_float_number_numeral

### CODE REVIEW

**Comment by eradman** [comment]
Frontend tests failed:
1. numbers formatted without commas
2. percent is off by 100

**Comment by justinclift** [comment]
You ok to fix those? :smile:

**Comment by eradman** [comment]
I should be able to figure it out. Probably a difference in the interface for specifying [number format](https://numbrojs.com/format.html)

The broken tests were run by `cd viz-lib && yarn test`, which I mistakenly thought `yarn test` covered

**Comment by justinclift** [comment]
> The broken tests were run by cd viz-lib && yarn test, which I mistakenly thought yarn test covered

Oh.  That's news to me too.  Learning something every day I guess. :smile:

**Comment by eradman** [comment]
I fixed most of the tests. The failing tests are complaining about incorrect tooltips on the counter widgets

```
    -   "targetValueTooltip": "24,484,000",
    +   "targetValueTooltip": "24484000",
```

The tooltips do seem to be formatted correctly when I run a development server. I'll investigate further next week

**Comment by justinclift** [comment]
Awesome.  Sounds like it's *almost* across the line. :smile:

**Comment by eradman** [comment]
I have not stumbled across any problems while testing this manually, but this change is affects a very hot code path (parsing all numbers returned by the database, and all the number formatting for tables). We should keep poking at this for at least a week.

**Comment by justinclift** [comment]
> We should keep poking at this for at least a week.

Sounds sensible. :smile:

**Comment by eradman** [comment]
Found and fixed an off-by-100 error

Unfortunately touching one more line of code tripped the code coverage warning 🙄

**Comment by eradman** [comment]
I have tested a variety of queries and dashboards, so far it's looking good.

I'll aim to merge this tomorrow (August 15) unless someone has additional comments or concerns.

**Comment by justinclift** [comment]
Sounds good to me. :smile:

**Pull request merged**
