### PR TITLE
Add: new sunburst sequence visualization

### PR DESCRIPTION
**Pull request by arikfr**
This is a new type of visualization useful for visualizing sequences/paths, like paths a user takes on a website. Based on the great work of @chrisrzhou ([link](http://bl.ocks.org/chrisrzhou/raw/d5bdd8546f64ca0e4366/)) and @kerryrodden ([link](http://bl.ocks.org/kerryrodden/7090426)).

Sunburst Demo

TODO:
- [x] Implement logic to resize the visualization on window resize or options change.

### CODE REVIEW

**Comment by mootpointer** [comment]
This looks great. What kind of data shape (for want of a better word) is required?

**Comment by arikfr** [comment]
@mootpointer it expects:

* sequence - sequence id (a single path)
* stage - what stage in sequence this is (1, 2, ...)
* node - stage name 
* value - number of times this sequence occurred

see this query for reference: http://demo.redash.io/queries/2280/source

**Comment by dengc367** [comment]
hello @arikfr， as now, sunburst sequence can draw above five stages ?  or like sankey visualization, at most five stages?

**Comment by arikfr** [comment]
@dengc367 currently it supports up to 5 stages. Happy to review a pull request that unblocks this to more. Thanks.

**Pull request merged**
