### PR TITLE
Handle error when data_source is None

### LINKED ISSUE #4608: Show a helpful error message when trying to execute queries detached from a data source
When a data source gets deleted, it's queries are still accessible (detailed explanation can be found in #4336) but they error out due to [`data_source` being None](https://github.com/getredash/redash/blob/master/redash/handlers/query_results.py#L65).

We should provide a helpful error message there (perhaps by raising `QueryDetachedFromDataSourceError`).

### PR DESCRIPTION
**Pull request by fsr313**
- [X] Bug Fix
## Description
No exception handled when data_source is None and generates error 500.
This change handles that error using a try-except and now excepts a error response with a helpful message about the problem.
## Related Tickets & Documents
resolves #4608

### CODE REVIEW

**Comment by luislizarraga** [comment]
Did you add tests?

**Comment by luislizarraga** [comment]
I think that it applies the same comment as the other PR, you can check if data_source is `None` and then return the error message instead of relying on the AttributeError class, which handles a different error (https://docs.python.org/2.7/library/exceptions.html#exceptions.AttributeError)

**Comment by guidopetri** [comment]
@fsr313 , thanks for the PR! We've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI, as well as updating merge conflicts?

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Comment by justinclift** [comment]
@konnectr This PR looks like it'd be useful, and the merge conflict being shown above seems like it shouldn't be hard to solve.

What do you think? :smile:

**Pull request merged**
