### PR TITLE
Don't immediately remove notifications from notification trays

### PR DESCRIPTION
**Pull request by mnoorenberghe**
What type of PR is this? (check all applicable)

- [x] Other

## Description

Let the notifications go into browser/OS notification trays so users can click on them from there if they miss the initial notification. Modern browsers generally use OS notifications so the user is in control of the notification at the OS level.

[Example of how users can adjust the timeout on macOS](https://osxdaily.com/2014/01/29/change-notifications-banner-time-mac-os-x/)

The current 3s delay is almost unusuable… I can rarely get my mouse to that part of the screen in time.

### CODE REVIEW

**Comment by mnoorenberghe** [comment]
The UI change seems to be a false-positive.

**Comment by arikfr** [comment]
What's the default behavior without the user adjusting the settings? Will the notification just remain visible until dismissed?

**Comment by mnoorenberghe** [comment]
No, every OS dismisses the notification from the screen after a delay by
default.
-- 
Sent from my phone

**Comment by arikfr** [comment]
Thanks!

**Pull request merged**
