### PR TITLE
Support pan and zoom

### PR DESCRIPTION
**Pull request by stanhu**
I opened a separate PR for #645, but perhaps it can just be folded into this.

### CODE REVIEW

**Comment by tjwudi** [comment]
Well if we are using HighChart 4 why not just switch to HighStock?

I added date picker in #594. It was a really simple date picker with many hacky code. Actually HighStock supports date picker but because the version of HighChart we used were not compatible with any HighStock revision so I didn't use HighStock.

But if we are going to have date picker and pan&zoom support then it makes sense to switch to HighStock force instead. Since we can have many new nice features without hand crafting them. @arikfr Any thoughts?

**Comment by arikfr** [comment]
@tjwudi actually, the plan is to replace HighCharts, because it's not open source (see #273). Maybe we will leave it as an optional plugin, but the core will have a different visualization option. Therefore I prefer not to invest much more into it by switching to HighStock.

**Comment by arikfr** [comment]
@stanhu do you know if there were any backward incompatible changes between version 3 and 4?

**Comment by stanhu** [comment]
I couldn't find any documentation about upgrading from Highcharts 3 to 4. The changes I made in this PR seem to make basic line graphs work fine for 4, but I may have missed something.

**Comment by arikfr** [comment]
We decided to switch to a different charting library (nvd3 or plot.ly new open source lib), so I don't want to invest time in testing this, but also don't want to merge it without testing.

Therefore I'm closing this. I apologize for the time you wasted on this. :(

**Pull request closed without merging**
