### PR TITLE
Add redash.query_runner.oracle to default_query_runners

### PR DESCRIPTION
**Pull request by snickerjp**
## What type of PR is this? 

- [x] Feature

## Description

add `redash.query_runner.oracle` to `default_query_runners `

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

## Related Tickets & Documents

#6380 
#6386

### CODE REVIEW

**Comment by justinclift** [comment]
Good idea. :smile:

**Comment by justinclift** [comment]
Do you want this PR to be reviewed as-is, or are you still working on it? :smile:

**Comment by snickerjp** [comment]
Sorry.

I would like a review please.

**Review by justinclift — APPROVED** [review]
Nothing to be sorry about, I just wasn't sure. :grin:

This PR looks good to me. :smile:

**Pull request merged**
