### PR TITLE
Update Slack Alert Destination Configuration Wizard: Support legacy webhooks

### PR DESCRIPTION
**Pull request by rauchy**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
Following up on #5514, this PR will keep the webhook call the same in case it was created with a legacy webhook.

## Related Tickets & Documents
#5514

### CODE REVIEW

**Review by susodapop — APPROVED** [review]

**Comment by guidopetri** [comment]
@justinclift similar here, are you good with merging if it passes CI?

**Comment by guidopetri** [comment]
Looks like we need to add a test.

**Comment by guidopetri** [comment]
Reading more into this, I don't think we want this change - it's to support legacy webhooks for Slack, but Slack encourages users to migrate to new webhooks anyhow. Closing as a result.

**Comment by justinclift** [comment]
Cool. :smile:

**Pull request closed without merging**
