### PR TITLE
Plotly renderer for pivottable visualization

### PR DESCRIPTION
**Pull request by deecay**
This PR adds new graphical renderers to pivottable visualization.

### New renderers
In addition to currently available renderers such as "Table" and "Heatmap", the following renderers will be added:

* Horizontal Bar Chart
* Horizontal Stacked Bar Chart
* Bar Chart
* Stacked Bar Chart
* Line Chart
* Scatter Chart

All charts are created by plotly.js, so mouse hover, series selection, and other things work as expected.

snapcrab_noname_2017-12-12_10-42-34_no-00

### Notes

* `resolve.alias` had to be added to webpack.config. Without it, entire plotly.js library gets compiled by webpack, and in the process, webpack throws an error trying to compile mapbox-gl. [The official way of compiling plotly.js](https://github.com/plotly/plotly.js/#building-plotlyjs-with-webpack) results in almost double the vendor.js size and compile time.

* Plotly button/link at the Plotly menubar will not be removed.

### CODE REVIEW

**Comment by deecay** [comment]
circleci seem to fail because of the library import issue mentioned in Notes. Any suggestions are welcomed.

**Comment by deecay** [comment]
Resolved path and circleCI issues.

Additional screenshots.

Base pivot table.
image

Horizontal Bar Chart
image

Horizontal Stacked Bar Chart
image

Bar Chart
image

Stacked Bar Chart
image

Line Chart
image

Scatter Chart
image

**Comment by deecay** [comment]
By the way, I have yet to find a way to enforce our color scheme from the outside of the plugin.

**Comment by arikfr** [comment]
While I see the usefulness in this, it feels wrong (product wise) to offer two ways of creating charts. I think there will come the time where we will need to provide a more "native" way to pivot the data in Redash. This will later allow for visualizing using the current visualizations the resulting dataset.

Considering this and the fact that we're porting all visualizations to React and this will be needed to be redone anyway, I'm closing this now.

If you're still interested in this behavior, please open an issue to discuss. Thanks!

**Pull request closed without merging**
