### PR TITLE
Embed visualizations become flex.

### PR DESCRIPTION
**Pull request by shinsuke-nara**
## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Description

Embed visualizations are not flex for vertical but I think they should be flex.
The reason is following `less` code:
https://github.com/getredash/redash/blob/a16f551e22c6288df6f067aa12caa5afd9a8f1dd/client/app/assets/less/redash/query.less#L211-L214

This code intends that embed visualizations should be flex for vertical.

### Before fix. Not flex version
NotFlexEmbed

### After fix. Flex version
FlexEmbed

### CODE REVIEW

**Comment by arikfr** [comment]
@gabrieldutra does this need any changes following the merge of the React version of the viz embed page?

**Comment by gabrieldutra** [comment]
> @gabrieldutra does this need any changes following the merge of the React version of the viz embed page?

No, looks like it works post-merge without changes

image

**Comment by guidopetri** [comment]
@shinsuke-nara , thanks for the PR! We've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI, as well as updating merge conflicts?

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Comment by justinclift** [comment]
The merge conflict looked pretty simple, so I just made a first attempt at resolving it.

Lets see if our CI tests seem happy with things.

**Comment by justinclift** [comment]
This looks like it's already been reviewed (when first submitted), so now that it's passing CI I'll merge it. :smile:

**Pull request merged**
