### PR TITLE
Reorganize frontend code into Yarn workspaces

### PR DESCRIPTION
**Pull request by kravets-levko**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Other

### CODE REVIEW

**Comment by guidopetri** [comment]
@justinclift this seems like a substantial PR, I don't think we'd want to close this one but I personally have no idea what Yarn workspaces are.

@eradman have you got an opinion on what we should do with this PR?

**Comment by justinclift** [comment]
Yeah, no idea about yarn workspaces either yet.  Sounds like something we'll probably want to at least learn about to see if they're a good fit. :smile:

**Comment by gabrieldutra** [comment]
> this seems like a substantial PR, I don't think we'd want to close this one but I personally have no idea what Yarn workspaces are.

At this point I'm more leaning towards suggesting to merge `viz-lib` back into the main package instead of building the multiple packages setup with workspaces. Reason being: if there's no clear benefit in having visualizations as it's own package on NPM, it simplifies things a lot to maintain just the Redash webapp.

**Comment by justinclift** [comment]
Cool.  That's a pretty unanimous "lets not go with yarn workspaces" (at least for now) so I'll close this. :smile:

**Pull request closed without merging**
