### PR TITLE
Feature: replace HighCharts with Plotly

### PR DESCRIPTION
**Pull request by alonho**
Solves #273

### CODE REVIEW

**Comment by alonho** [comment]
Before merging this I want to run the JS unit tests and also test some existing queries and dashboards.
It seems we maintained backward compatibility with all features.

A new little feature allows using grouping with pie charts, it generates a pie for every group (series):
screen shot 2015-12-05 at 2 34 41 am

**Comment by alonho** [comment]
Ready for merge! added a checkbox for disabling the legend.

**Comment by arikfr** [comment]
:tada:

**Comment by toyama0919** [comment]
:+1:

**Pull request merged**
