### PR TITLE
Added arrow to multi-select component

### LINKED ISSUE #4042: Dropdown Parameter Missing Arrow
Previous versions:

image

Current version:

image

Was this intentional?

### PR DESCRIPTION
**Pull request by ranbena**
- [x] Feature

## Description
Added arrow to Select.
Fixes #4042.

### CODE REVIEW

**Comment by gabrieldutra** [comment]
Also needs to add the arrow to the Query Based Dropdown Parameter.

**Comment by ranbena** [comment]
@gabrieldutra I would really like to also make it not `min-width: 195px`. Don't you think it's a waste of space?I appreciate your opinion 🙏

**Comment by gabrieldutra** [comment]
> @gabrieldutra I would really like to also make it not `min-width: 195px`. Don't you think it's a waste of space?I appreciate your opinion

Go ahead, It is a waste of space indeed, my only concern is when it's empty-valued, but we can experience that with the arrow. One option is to add a placeholder in case it turns out to be weird looking.

**Comment by ranbena** [comment]
Now that there's an arrow, it's obvious that the remaining space is clickable.

Screen Shot 2019-08-06 at 16 10 46

**Comment by ranbena** [comment]
> my only concern is when it's empty-valued

It'll look exactly like an empty single value dropdown having minimum `60px` width.

**Pull request merged**
