### PR TITLE
[Data Sources] Implement Couchbase query runner

### PR DESCRIPTION
**Pull request by jayantak**
Implement Couchbase N1QL query runner. Cursory searching didn't show anyone else doing it too, so please let me know if I'm replicating anyone's work. 

Opening PR early for Pull Request First. 

https://www.couchbase.com/

If someone had a moment to answer a couple of questions:
1.  Is the docker based deployment the only one required? Is it also used to build the GCP/AWS images etc? 
1. ~~The couchbase python package requires an external package called libcouchbase, which may be installed from APT, but I don't see where to add them. The only apt-get install statements I see are in the docker installation section in the sample setup folder, so some direction would be good.~~ Of course I should add them to the base image, oops.

### CODE REVIEW

**Comment by arikfr** [comment]
Thanks!

> Is the docker based deployment the only one required? Is it also used to build the GCP/AWS images etc?

Yes. We use the same Docker image for the GCP/AWS images.

**Comment by arikfr** [comment]
Hi @jayantak ,
You need to properly rebase this brach, because currently it includes all the changes from the past months :O

**Comment by jayantak** [comment]
Oh gosh, I apologise, I was working on another branch on my fork and I pushed the rebase to master lol. Will fix it.

**Comment by gabrielbirnbaum** [comment]
Hi, I was wondering what is the status of this issue? I want to implement Redash with couchbase, and I am wondering if I should wait for this to be merged? @arikfr 

If there is anything that I can do to get this issue merged, I would love to get one of our developers to help.

thanks in advance, achi.

**Comment by rauchy** [comment]
@jayantak have you had the chance to progress with a clean feature branch for this?

**Comment by arikfr** [comment]
@gabrielbirnbaum hard to tell... I tried to find the actual query runner implementation in this PR, but couldn't. If you have the resources just implementing Couchbase support shouldn't be too complex.

Here's some details on what it takes to create a Query Runner in Redash: https://discuss.redash.io/t/creating-a-new-query-runner-data-source-in-redash/347

**Comment by gabrielbirnbaum** [comment]
@arikfr I looked at the guide and it seems pretty straight forward. One of our developers is gonna do a PR next week. I will keep you posted :) in any case, thanks for the help.

**Pull request closed without merging**
