### PR TITLE
Add page-specific class to body for each app page

### PR DESCRIPTION
**Pull request by kravets-levko**
Requested by @kocsmy

### CODE REVIEW

**Comment by arikfr** [comment]
@kocsmy can you explain the usage for page specific classes?

**Comment by kocsmy** [comment]
@arikfr sure: for example the Query page might need a body { overflow: hidden; } and the best way to do this is with a unique body class (or ID would work, too). 

It's also handy for other pages, in case we need to apply page specific styling.

**Comment by arikfr** [comment]
@kocsmy does the `<body>` needs this style or some other top level component might be just as good?

**Comment by kocsmy** [comment]
@arikfr the body needs this style afaik (I tried lower level elements)

**Comment by arikfr** [comment]
Having a page specific class will lead us to having unique snowflakes instead of consistent pages. What we do need is support for different layouts (a closed set of different layouts).

Thank to the work @kravets-levko did with creating the top level `<app-view>` component, we can use it to create support for layouts.

As we don't really need this now, let's close this and revisit when we do need a different layout for some of our pages.

**Comment by kocsmy** [comment]
But sometimes, we do need beautiful unique snowflakes so we can make snowballs that we can throw far far away.

**Pull request closed without merging**
