### PR TITLE
Further Query Improvements

### PR DESCRIPTION
**Pull request by kocsmy**
Initial commit for #2234

### CODE REVIEW

**Comment by kocsmy** [comment]
Thanks for the cleanup and layout improvements, @kravets-levko 

I can spot 2 issues:
- [ ] Minimalising the query editor makes the top part of the visualisation go below the hidden area and disappear:
screenshot 2018-01-25 00 15 30

- [ ] When the editor is closed, the metadata and meta refresh and history goes up. It should still stick to the bottom:
screenshot 2018-01-25 00 15 41

**Comment by kravets-levko** [comment]
@kocsmy Fixed. Can you please check and confirm that everything is ok

**Comment by kocsmy** [comment]
Thanks for the quick fixes, @kravets-levko — all look good now!

**Comment by arikfr** [comment]
Some comments:

Important: 
The data area needs its own scroll - right now the scroll is shared between the data area and the query text. This has two down sides: when you scroll the data you can't see the query but more important: you need to scroll down to be able to scroll to the side.

Nice to have: (can be fixed later on, unless very simple)
* The refresh schedule is part of the query metadata, so it doesn't need a divider on top of it. The vertical divider on the right should be seen on it.
image

* In data only view, the left side is very empty. Maybe we should use a horizontal area for metadata in such case?

**Comment by kocsmy** [comment]
Thanks @arikfr 

- Regarding the scroll: yes, we discussed that with @kravets-levko and we weren't sure, I think he can implement that version.
- Refresh schedule: You mean like this? 
screenshot 2018-01-28 13 20 02

- Too empty left side: I wouldn't move the bottom fixed metadata to the top, I actually tried that and having it move around is more annoying than having some empty space there. Maybe we can add something there later.

**Comment by arikfr** [comment]
> Refresh schedule: You mean like this?

Yes and probably with less padding between it and the "created/updated" part.

> Too empty left side: I wouldn't move the bottom fixed metadata to the top, I actually tried that and having it move around is more annoying than having some empty space there. Maybe we can add something there later.

That's because you think about this as being the same page in two different states. But what if you think about it as an independent page?

**Comment by kocsmy** [comment]
> That's because you think about this as being the same page in two different states. But what if you think about it as an independent page?

But this is the same page in different state?:) Okay, if I make myself think about that way, then we don't need the left sidebar at all and we can go with a totally different layout. But afaik we just moved away from that and made a decision to show the schema section always, even if it's empty? Anyway, I got what you're saying and I agree that left side feels very empty. Not sure how to address this, but let's discuss on our call.

**Comment by arikfr** [comment]
This PR needs a rebase...

**Comment by arikfr** [comment]
There is still one thing left and it's the issue with the "Refresh Schedule" not being part of the metadata above it. I merged regardless so we don't keep this large pull request hanging.

Created #2279 to track this.

**Comment by kocsmy** [comment]
Thanks @arikfr — yes, that's totally kept in mind and we'll make that happen, too!

**Pull request merged**
