### PR TITLE
Color picker component

### PR DESCRIPTION
**Pull request by kravets-levko**
## What type of PR is this? (check all applicable)

- [x] Feature

## Description

Color picker component to use in visualizations editors (as a replacement for `<input type="color">` and `<ui-select>` with color list and whatever we have there).

Because of a quite simple design, I decided to not add a new external library like `react-color` (`tinycolor2` already was among implicit dependencies) and implemented everything using Ant components.

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

image
image
image
image
image
image
image

### CODE REVIEW

**Comment by ranbena** [comment]
@kravets-levko In which viz, in the Netlify Preview instance, can I see this in action?

**Comment by kravets-levko** [comment]
@ranbena Currently - nowhere. I was testing it by adding to one of React pages (it was users list page I think). The first place I plan to use it - Chart Editor migration to React.

**Comment by kravets-levko** [comment]
I just didn't want to whip it within getredash/redash#4139

**Comment by ranbena** [comment]
> @ranbena Currently - nowhere. I was testing it by adding to one of React pages (it was users list page I think). The first place I plan to use it - Chart Editor migration to React.

Oh then know it goofed vertical alignment in https://deploy-preview-4136--redash-preview.netlify.com/queries/49#116.

**Comment by kravets-levko** [comment]
I already know why :man_facepalming: I just need to restore a single line of CSS, but will do it tomorrow.

**Comment by kravets-levko** [comment]
@ranbena I fixed crolo box alignment issue and added a "demo" for this component so you can try it (I'll remove it before merging): https://deploy-preview-4136--redash-preview.netlify.com/users?page=1&page_size=20&order=-created_at

**Comment by wtfzambo** [comment]
Yo, sorry for necrothreading this, I was looking for this functionality inside redash but could not find anything of the sorts.

Is it still to be implemented? I'm currently on version 8.0.0+b32245, self hosted.

**Comment by susodapop** [comment]
This will be release in V9.

**Pull request merged**
