### PR TITLE
Feature/watermark

### PR DESCRIPTION
**Pull request by bonashen**
## What type of PR is this? 

add watermark for dashboard

[ x ] Feature

## Description

add watermark for dashboard

## How is this tested?

[ x ] N/A

### CODE REVIEW

**Comment by bonashen** [comment]
Watermark on dashboard

Screenshot from 2023-05-01 20-15-54

Watermark setting 
Screenshot from 2023-05-01 20-17-10

**Comment by Avey777** [comment]
It is already difficult to merge the code here. You have another option available:
https://github.com/RedashCommunity/redash

**Comment by guidopetri** [comment]
@bonashen thanks for your contribution! Would you mind rebasing your branch on `master` and pushing to rerun CI checks?

**Comment by konnectr** [comment]
@bonashen Why did you delete the PR ?

**Pull request closed without merging**
