### PR TITLE
fix pubic dashboard not update result #6203

### PR DESCRIPTION
**Pull request by gaecoli**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

### CODE REVIEW

**Comment by gaecoli** [comment]
> ## [Codecov](https://app.codecov.io/gh/getredash/redash/pull/6214?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=getredash) Report
> > Merging [#6214](https://app.codecov.io/gh/getredash/redash/pull/6214?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=getredash) ([07f46a4](https://github.com/getredash/redash/commit/07f46a4718fc80b7499e037bfceb7f83edc7281a)) into [master](https://app.codecov.io/gh/getredash/redash/commit/05c9b35e42d20d952dd8bcf4a46154281877a022?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=getredash) ([05c9b35](https://github.com/getredash/redash/commit/05c9b35e42d20d952dd8bcf4a46154281877a022)) will **decrease** coverage by `0.01%`.
> > The diff coverage is `33.33%`.
> 
> ```diff
> @@            Coverage Diff             @@
> ##           master    #6214      +/-   ##
> ==========================================
> - Coverage   59.96%   59.95%   -0.01%     
> ==========================================
>   Files         153      153              
>   Lines       12467    12469       +2     
>   Branches     1687     1688       +1     
> ==========================================
>   Hits         7476     7476              
> - Misses       4783     4784       +1     
> - Partials      208      209       +1     
> ```
> 
> [Impacted Files](https://app.codecov.io/gh/getredash/redash/pull/6214?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=getredash)	Coverage Δ	
> [redash/handlers/query_results.py](https://app.codecov.io/gh/getredash/redash/pull/6214?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=getredash#diff-cmVkYXNoL2hhbmRsZXJzL3F1ZXJ5X3Jlc3VsdHMucHk=)	`80.10% <33.33%> (-0.88%)`	⬇️

What this? @justinclift

**Comment by justinclift** [comment]
@gaecoli It's saying that with this change, our "test coverage" has been reduced.

It's a to measure how much of our code is actually being tested.  So, over time we can try to increase it.

**Comment by gaecoli** [comment]
> @gaecoli It's saying that with this change, our "test coverage" has been reduced.
> 
> It's a to measure how much of our code is actually being tested. So, over time we can try to increase it.

Ok, i will try to learn it.

**Comment by justinclift** [comment]
I think @junnplus knows about it, so might be useful to ask if you have questions. :smile:

**Comment by gaecoli** [comment]
> I think @junnplus knows about it, so might be useful to ask if you have questions. 😄

Ok, fine.

**Comment by gaecoli** [comment]
> ## [Codecov](https://app.codecov.io/gh/getredash/redash/pull/6214?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=getredash) Report
> > Merging [#6214](https://app.codecov.io/gh/getredash/redash/pull/6214?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=getredash) ([07f46a4](https://github.com/getredash/redash/commit/07f46a4718fc80b7499e037bfceb7f83edc7281a)) into [master](https://app.codecov.io/gh/getredash/redash/commit/05c9b35e42d20d952dd8bcf4a46154281877a022?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=getredash) ([05c9b35](https://github.com/getredash/redash/commit/05c9b35e42d20d952dd8bcf4a46154281877a022)) will **decrease** coverage by `0.01%`.
> > The diff coverage is `33.33%`.
> 
> ```diff
> @@            Coverage Diff             @@
> ##           master    #6214      +/-   ##
> ==========================================
> - Coverage   59.96%   59.95%   -0.01%     
> ==========================================
>   Files         153      153              
>   Lines       12467    12469       +2     
>   Branches     1687     1688       +1     
> ==========================================
>   Hits         7476     7476              
> - Misses       4783     4784       +1     
> - Partials      208      209       +1     
> ```
> 
> [Impacted Files](https://app.codecov.io/gh/getredash/redash/pull/6214?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=getredash)	Coverage Δ	
> [redash/handlers/query_results.py](https://app.codecov.io/gh/getredash/redash/pull/6214?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=getredash#diff-cmVkYXNoL2hhbmRsZXJzL3F1ZXJ5X3Jlc3VsdHMucHk=)	`80.10% <33.33%> (-0.88%)`	⬇️

Hi @junnplus , if i want to fix this, how to avoid my code cover decrease.

**Comment by junnplus** [comment]
You can add a test to cover the changes.

**Comment by gaecoli** [comment]
@junnplus `pre-commit` is very good stuff.

**Pull request merged**
