### PR TITLE
Run prettier

### PR DESCRIPTION
**Pull request by rafawendel**
## What type of PR is this? (check all applicable)

- [X] Other

## Description
Plain runs prettier to avoid style changes in PRs

### CODE REVIEW

**Review by gabrieldutra — APPROVED** [review]

**Review by gabrieldutra — CHANGES_REQUESTED** [review]
Hey @rafawendel, I actually just executed `npm run prettier` locally and I didn't find such issues, is this really expected? Was there any change prior to the command execution?

**Comment by rafawendel** [comment]
> Hey @rafawendel, I actually just executed `npm run prettier` locally and I didn't find such issues, is this really expected? Was there any change prior to the command execution?

Did you run it on viz-lib?

**Comment by gabrieldutra** [comment]
I see what happened now @rafawendel, we should have this line updated https://github.com/getredash/redash/blob/aa9475977cff2f04f8d83f30a222170c42d23762/viz-lib/package.json#L18 as all the files are ts/tsx now.

Do you mind doing it since you are on this already?

**Comment by rafawendel** [comment]
> I see what happened now @rafawendel, we should have this line updated
> 
> https://github.com/getredash/redash/blob/aa9475977cff2f04f8d83f30a222170c42d23762/viz-lib/package.json#L18
> as all the files are ts/tsx now.
> 
> Do you mind doing it since you are on this already?

I also reverted the run in viz-lib and re-did it, but nothing changed so I kept it as-is

**Review by gabrieldutra — APPROVED** [review]

**Pull request merged**
