### PR TITLE
add pagination and base_url to JSON query_runner

### PR DESCRIPTION
**Pull request by Ken-Michalak**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source)
- [ ] New Alert Destination
- [ ] Other

## Description

Add the ability to paginate the JSON Query Runner and configure a base URL. This supports the `next_page_token`, `page_token` pattern or `next_offset`, `offset`. It's written to support pagination in Chargebee's API, but generalized for other sources, including [Google's pagination design pattern](https://cloud.google.com/apis/design/design_patterns#list_pagination), by passing `pagination: [next_offset, offset]` into the query.

### CODE REVIEW

**Comment by guidopetri** [comment]
@Ken-Michalak , thanks for the PR! We've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI?

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Comment by justinclift** [comment]
Just started to look at this PR (eg fix the merge conflict), but the PR was created without permission for contributors to add commits so I can't actually do anything.

Hopefully @Ken-Michalak is interested in picking this PR up again. :smile:

**Comment by Ken-Michalak** [comment]
@guidopetri I've updated the branch and also added support for the HATEOAS pattern with `pagination: _links.next.href`. Do you want to reopen this one, or should I make a separate one?

**Comment by justinclift** [comment]
GitHub doesn't seem to be allowing this PR to be re-opened, so probably best to make a new PR for it instead. :smile:

**Comment by justinclift** [comment]
kjkj

**Pull request closed without merging**
