### PR TITLE
DO NOT MERGE: fail tests on purpose

### PR DESCRIPTION
**Pull request by guidopetri**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description

Test PR, do not merge.

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

### CODE REVIEW

**Comment by guidopetri** [comment]
As expected, the unit tests that should have failed passed. @AndrewChubatiuk @justinclift this is a problem, since it essentially means our CI is broken.

**Comment by justinclift** [comment]
Uh uh, that's not good.  Any idea when it started?

**Comment by guidopetri** [comment]
I'm pretty sure it was the pull request target PR.

**Comment by AndrewChubatiuk** [comment]
@guidopetri updated checkout ref [here](https://github.com/getredash/redash/pull/6748/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL21)

**Comment by guidopetri** [comment]
Closing as the tests (correctly) fail now.

**Pull request closed without merging**
