### PR TITLE
Update mattermost.py

### PR DESCRIPTION
**Pull request by kolya7k**
Fix UnicodeEncodeError for non-Latin characters for mattermost destination (#6715)

### CODE REVIEW

**Comment by guidopetri** [comment]
@kolya7k thanks for the PR! While you're at it, do you think we should update all destinations to support UTF8?

**Comment by kolya7k** [comment]
Yes, but i encountered with this problem on MM because i'm using MM and Cyrillic symbols :)
I can later make a PR for every destination

**Comment by guidopetri** [comment]
Could we do it in this PR since it's a one line change?

**Comment by eradman** [comment]
Rebasing to see if tests pass

**Pull request closed without merging**
