### PR TITLE
GraphQL Runner

### PR DESCRIPTION
**Pull request by kevinchiang**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] New Query Runner (Data Source)
- [ ] New Alert Destination
- [ ] Other

## Description
A GraphQL query runner.  Each GraphQL data source has one API endpoint.

## Related Tickets & Documents
#3158 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

Screen Shot 2022-01-28 at 10 20 48 AM
Screen Shot 2022-01-28 at 10 20 54 AM
Screen Shot 2022-01-28 at 10 21 41 AM

### CODE REVIEW

**Comment by kevinchiang** [comment]
Tested the query runner on https://graphqlzero.almansi.me/api .

I added the GraphQL db-logo into client/app/assets/images/db-logos/graphql.png and rebuilt the frontend, but it didn't appear in dist.  Could use a pointer on how to make that build.

**Comment by susodapop** [comment]
Thanks for your work on this! Would you mind rebasing off of `master` to kick off the build check? There were some issues with `master` in January that have since been corrected. Not sure I have permission to push an empty commit to your fork 🙏

**Comment by rconjoe** [comment]
Any word on why this is held up?

**Comment by susodapop** [comment]
I'm not actively contributing to Redash at this time. Pinging @arikfr or @justinclift to have a look.

**Comment by justinclift** [comment]
Hmmm, it's saying there was a Cypress failure:

```
visualizations/pivot_spec.js             00:31        4        3        1        -        - 
```

Probably need to either rerun it (just to double check it's not a random failure), or figure out why. :frowning:

**Comment by guidopetri** [comment]
Closing; duplicated by #6268

**Pull request closed without merging**
