### PR TITLE
Scheduler tests (jest/enzyme)

### PR DESCRIPTION
**Pull request by ranbena**
Added tests for refresh scheduler - a mix of snapshots, prop/state changes and ui event simulations.

#### Enzyme 🥼
Allows dom traversal and manipulation, react props and state access, ui event simulation, shallow/deep component mounting. It's also a workaround to `react-test-renderer`'s inability to mount Ant components [because of this](https://github.com/facebook/react/issues/11565#issuecomment-427547413).

#### Reviewer 👋🏼
This is a large PR due to amount of tests and snapshot file size.
The PR is split into a few commits - setup and initial test, then gradually added tests by feature.

#### Run tests 🕵🏻‍♂️
Command: `npm test client/app/components/queries/ScheduleDialog.test.js`
```
PASS  client/app/components/queries/ScheduleDialog.test.js
ScheduleDialog
    ✓ Resets selected count value if out-of-range (198ms)
    Sets correct schedule settings
      ✓ Sets to "Never" (24ms)
      ✓ Sets to "5 Minutes" (20ms)
      ✓ Sets to "2 Hours" (23ms)
      Sets to "1 Day 22:15"
        ✓ Sets to correct interval (5ms)
        ✓ Sets to correct time (6ms)
      Sets to "2 Weeks 22:15 Tuesday"
        ✓ Sets to correct interval (5ms)
        ✓ Sets to correct time (5ms)
        ✓ Sets to correct weekday (5ms)
      Until feature
        ✓ Until not set (22ms)
        ✓ Until is set (31ms)
    Adheres to user permissions
      ✓ Shows correct interval options (248ms)
      ○ skipped 1 test
    Modal Confirm/Cancel feature
      ✓ Query saved on confirm if state changed (16ms)
      ✓ Query not saved on confirm if state unchanged (10ms)
      ✓ Cancel closes modal and query unsaved (23ms)

Test Suites: 1 passed, 1 total
Tests:       1 skipped, 15 passed, 16 total
Snapshots:   10 passed, 10 total
Time:        3.036s
```
Jest config breakdown:
```json
"jest": {
    "setupFiles": [
      "./client/app/jest_setup.js" // enzyme setup
    ],
    "snapshotSerializers": [
      "enzyme-to-json/serializer" // snapshot serializer alternative to jest's
    ],
    "moduleNameMapper": {
      "^@/(.*)": "<rootDir>/client/app/$1", // @ alias
      "\\.(css|less)$": "identity-obj-proxy" // for css files to load
    }
  }
}
```

### CODE REVIEW

**Comment by arikfr** [comment]
I see the tests still fail. It's worth mentioning that the way this supposed to work is that the user picks time in their timezone, but it gets saved in UTC. Is it possible this is what causing the failure?

**Comment by ranbena** [comment]
Yep. And my recent commit was meant to fix this by setting a persistent tz for tests. I'll keep at it.

**Comment by ranbena** [comment]
@arikfr fixed as [suggested here](https://stackoverflow.com/questions/40935886/components-using-date-objects-produce-different-snapshots-in-different-timezones):
https://github.com/getredash/redash/blob/44b0056ad44f31c6358e3c3ecbf976784aa5bf35/package.json#L14

**Comment by arikfr** [comment]
You need to rebase...

**Comment by ranbena** [comment]
Rebased. Reviewer / @arikfr - plz opt for "Squash and merge".

**Pull request merged**
