### PR TITLE
Fix JSON Serialization Error for Cassandra

### LINKED ISSUE #4931: unable to parse map type data from cassandra datastore
### Issue Summary

Used redash preview (support for cassandra tls) , we do have map type data in cassadra, when selecting data from these data types, we see an exception
TypeError: Object of type OrderedMapSerializedKey is not JSON serializable

### Steps to Reproduce
1. In cassandra create table with map type column
CREATE TABLE maptypeData (
    customer_id text,
    meta_string map<text, text>,
    PRIMARY KEY (customer_id)
);

2. Insert data
insert into maptypeData (customer_id,meta_string) values ('dummy',{'bucketName': 'testbucket', 'objectExposure': 'public', 'owner': 'dummy'});

3. from CQLSH 
select * from maptypeData;
customer_id | meta_string
-------------+----------------------------------------------------------------------------
       dummy | {'bucketName': 'testbucket', 'objectExposure': 'public', 'owner': 'dummy'}

4. From redash UI, run the same query 
Result: None
Error: Error running query: Object of type OrderedMapSerializedKey is not JSON serializable

Logs:
xecute_query job.id=11203a82-e06a-4622-93e7-3a3ce59a71de Unexpected error while running query:
Traceback (most recent call last):
  File "/app/redash/tasks/queries/execution.py", line 175, in run
    data, error = query_runner.run_query(annotated_query, self.user)
  File "/app/redash/query_runner/cass.py", line 165, in run_query
    json_data = json_dumps(data, cls=CassandraJSONEncoder)
  File "/app/redash/utils/__init__.py", line 121, in json_dumps
    return simplejson.dumps(data, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/simplejson/__init__.py", line 399, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.7/site-packages/simplejson/encoder.py", line 296, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/site-packages/simplejson/encoder.py", line 378, in iterencode
    return _iterencode(o, 0)
  File "/app/redash/query_runner/cass.py", line 36, in default
    return super(CassandraJSONEncoder, self).default(o)
  File "/app/redash/utils/__init__.py", line 103, in default
    result = super(JSONEncoder, self).default(o)
  File "/usr/local/lib/python3.7/site-packages/simplejson/encoder.py", line 273, in default
    o.__class__.__name__)
TypeError: Object of type OrderedMapSerializedKey is not JSON serializable
### Technical details:

The line numbers in the exception might not be accurate as I was trying to debug the issue.

* Redash Version:
preview
* Browser/OS:
Chrome
* How did you install Redash:
AMI+ docker-compose from preview image.

### LINKED ISSUE #4970: Cassandra / ScyllaDB date fields can't serialize into JSON
### Issue Summary

The `CassandraJSONEncoder` doesn't support encoding Python `Date()` objects:

https://github.com/getredash/redash/blob/d036df0ca177738f2fc157991f010aa2120b2ddc/redash/query_runner/cass.py#L32-L36

### Steps to Reproduce

1. Run `SELECT CAST('2020-01-01' as date)` against Cassandra or ScyllaDB
2. Observe the error: `"Error running query: Object of type Date is not JSON serializable"`

### Technical details:

* Redash Version: v9 Alpha
* Browser/OS: Firefox / Safari / Chrome
* How did you install Redash: SaaS

### PR DESCRIPTION
**Pull request by tim5go**
## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Description
From issues #4970 and #4931, we know that the current  `CassandraJSONEncoder` has the limitation to encode custom datatype in Cassandra (e.g. `cassandra.util.Date` and `OrderedMapSerializedKey`). This PR is to handle these problems.

## Related Tickets & Documents

Close #4970, Close #4931.

### CODE REVIEW

**Comment by tim5go** [comment]
@arikfr 
Do you know anyone is following up on that?

**Comment by tim5go** [comment]
@susodapop
Do you think you have time to look at this PR?

**Comment by justinclift** [comment]
@tim5go Thanks for this PR.  Sorry it's been hanging around for so long without being reviewed or merged.

About a month ago the project moved to being "Community Led", so in the time since then a bunch of us have been going through the outstanding PRs (merging, reviewing, closing, etc), cleaning things up, and so on.

Are you still interested in getting this PR reviewed and merged? :smile:

**Comment by tim5go** [comment]
@justinclift 
I'm still interested in working on this PR, may I know what I should do to re-open this PR, thanks you!

**Pull request closed without merging**
