### PR TITLE
Fix: TreasureData get_schema method was returning array instead of string as column name

### PR DESCRIPTION
**Pull request by ariarijp**
Fix schema information widget on Query Source View.

For details, Please see below screenshots.

---

Before

before

After

after

### CODE REVIEW

**Comment by arikfr** [comment]
Thanks! Is it TD version dependent or a bug we had since forever?

cc: @toru-takahashi

**Comment by toru-takahashi** [comment]
Thank you for the implement.

The reason that column name show Array type with column type is my expected behavior.
(And, it's not TD version's bug.)
Because, I though that showing column type with column name is useful for users to write a query at that time. (And, I think re:dash doesn't have a feature to show column type. Is it right?)

Anyway, It's ok to apply this fix to become same behavior as other plugins.

**Comment by arikfr** [comment]
@toru-takahashi got it. It's better to pass only the column name as it will be more readable and useful for auto complete.

I agree that adding support for types has its benefits, but we need to do it properly.

**Comment by toru-takahashi** [comment]
I see. Thank you!

**Pull request merged**
