### PR TITLE
LDAP Authentication. Create two envars REDASH_LDAP_USE_SSL and REDASH_LDAP_AUTH_BIND

### PR DESCRIPTION
**Pull request by MrCirca**
Hello,
I have created 2 new envars. 

- REDASH_LDAP_USE_SSL : This envar determines the use of SSL or not, giving value to use_ssl parameter. Default is false

- REDASH_LDAP_AUTH_METHOD:  This envar determines the authentication method(**SIMPLE** or **ANONYMOUS**). Default is SIMPLE

### CODE REVIEW

**Comment by MrCirca** [comment]
Also i have changed the documentation of redash website.
Check this [pull request](https://github.com/getredash/website/pull/115)

**Comment by MrCirca** [comment]
Still open...Someone to who can review this?

**Comment by Jakdaw** [comment]
Does this also encompass what I submitted in #3002 ?

Ie if you select 'anonymous' will the password be ignored?

**Comment by MrCirca** [comment]
Hello @Jakdaw ! Of course! Anonymous bind doesn't require password

**Comment by MrCirca** [comment]
Still open

**Comment by tonidas** [comment]
Great PR @MrCirca, I've spent 30minutes to discover that there is a flag on the Server object to select if it will use SSL. I was getting:

`ldap3.core.exceptions.LDAPSocketReceiveError: error receiving data: [Errno 104] Connection reset by peer`

Now I've created a custom image to add this flag.

@arikfr please look at this!

Cheers

**Comment by MrCirca** [comment]
Thank you @tonidas !!

**Comment by arikfr** [comment]
Thanks, @MrCirca . Sorry it was stuck for so long.

**Comment by MrCirca** [comment]
I have written documentation too.
https://github.com/getredash/website/pull/115

**Pull request merged**
