### PR TITLE
Add event to download query results.

### PR DESCRIPTION
**Pull request by akaimo**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source)
- [ ] New Alert Destination
- [ ] Other

## Description

Added a log when downloading files from the Web Application.
I have a need for this as part of SIEM efforts.

### CODE REVIEW

**Comment by konnectr** [comment]
@akaimo  thanks for the PR! We've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI, as well as updating merge conflicts?

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Comment by akaimo** [comment]
@konnectr  Thanks for the reply. I am hoping to merge this feature. I have imported the latest master.
But restyled is failing, what should I do?

**Comment by konnectr** [comment]
If you look at the logs. You can see that your code has not been verified.
https://restyled.io/gh/getredash/repos/redash/jobs/3408478
https://restyled.io/gh/getredash/repos/redash/jobs/3408478/patch

**Comment by akaimo** [comment]
@konnectr Thank you very much.
Is there any way to make past commits verified?
I am currently already set up with GPG. Should I commit again?

**Comment by justinclift** [comment]
It looks like we have slightly mucked up our formatting stuff.  I'm going to add a quick-and-dirty fix for that in a few minutes.  Once that's in place, please pull from the `master` branch again, then try reformatting again.  In theory (!) the formatting problems will then be gone.

**Comment by justinclift** [comment]
@akaimo As @konnectr was pointing our, your most recent commit wasn't signed:

https://github.com/getredash/redash/pull/5501/commits

If you look at the commits there (3 at the moment), only the first one was.  It looks like the most recent one from you wasn't.

Maybe a configuration error on your system? :smile:

**Comment by justinclift** [comment]
@akaimo We're just waiting on this one to finish passing its CI tests and get merged:

https://github.com/getredash/redash/pull/6322

Should be in about 20-25 minutes.

**Comment by akaimo** [comment]
@justinclift 

> We're just waiting on this one to finish passing its CI tests and get merged

Thank you very much.

> If you look at the commits there (3 at the moment), only the first one was. It looks like the most recent one from you wasn't.

I had not yet set up my GPG when I committed in 2021. https://github.com/getredash/redash/pull/5501/commits/ea97d16b509aed814718b0f2dec883f938a2da64
Can I sign this commit now?

**Comment by justinclift** [comment]
Signing it now won't hurt anything.  So you can do that if you want.

We still need for that other PR (to fix the formatting problem) to finish it's CI check and get merged.  That should happen in about 15-20 minutes.  Roughly. :smile:

**Comment by justinclift** [comment]
@akaimo That other PR finally just merged (it took about an hour!).

Probably the very best approach for this PR, is if you re-create it from the (updated) master branch, then manually apply your change to it and make a new (signed) commit with that.

In theory, that should pass all the tests and be signed correctly, etc. :smile:

**Comment by akaimo** [comment]
@justinclift Thanks for the suggestion.
I will try to create the PR again this way.
It may take some time, since frontend-e2e-tests was also failing.

**Comment by justinclift** [comment]
No worries.  If you need assistance, please let us know and we'll try to help. :smile:

**Pull request closed without merging**
