### PR TITLE
add ssl_config to redshift iam class

### PR DESCRIPTION
**Pull request by peterxichen**
## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Description
"RedshiftIAM object does not contain ssl_config" error when attempting to establish connection to Redshift using IAM role.

## Related Tickets & Documents
https://github.com/getredash/redash/issues/5464

### CODE REVIEW

**Comment by guidopetri** [comment]
@peterxichen , thanks for the PR! We've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI, as well as updating merge conflicts?

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Comment by justinclift** [comment]
This one is a simple 1-liner, so I just manually resolved the merge conflict using the web interface.  Hopefully the formatting isn't wrong enough to generate lint errors. :grin:

**Comment by justinclift** [comment]
Going to ignore Codecov for this one. :smile:

**Comment by justinclift** [comment]
It passed all the other tests, so merging it now. :smile:

**Pull request merged**
