### PR TITLE
[WIP] Update to latest RestrictedPython

### PR DESCRIPTION
**Pull request by ehfeng**
Now includes builtin function `set` as part of RestrictedPython.

### CODE REVIEW

**Comment by arikfr** [comment]
Don't we need to update the query runner code as well as a result?

**Comment by ehfeng** [comment]
Damn, good point. I hadn't gotten it set up locally when I created this PR.

**Comment by arikfr** [comment]
Ping :)

**Comment by arikfr** [comment]
Closing. You're welcome to reopen if relevant.

**Comment by ehfeng** [comment]
👍  Will try to (eventually) get to this.

**Pull request closed without merging**
