### PR TITLE
Plotly legent overlaps plot on small screens (when legend clicked)

### PR DESCRIPTION
**Pull request by kravets-levko**
## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Description

Revert changes from getredash/redash#3882 and apply a new fix. Previous time I misunderstood the problem and applied a wrong fix, but the real problem was with the code that detects CSS support.

## Related Tickets & Documents

Fixes getredash/redash#3975

### CODE REVIEW

**Comment by justinclift** [comment]
Awesome @kravets-levko.  I'll this out in a test instance later today (~10 hrs away), to confirm it solves the problem. :smile:

**Comment by arikfr** [comment]
Justin, are you familiar with the preview deployments?

**Comment by justinclift** [comment]
This change fixes the problem when testing just now in Firefox.

**Comment by justinclift** [comment]
> Justin, are you familiar with the preview deployments?

Not yet.  Sounds like there's a better way then running things up in a local VM?

**Comment by justinclift** [comment]
> Justin, are you familiar with the preview deployments?

Ahhh.  Thus the `deploy/netlify - Deploy preview ready` thing in the list above.  That'll save time in future. :smile:

**Comment by arikfr** [comment]
@justinclift 

> Ahhh. Thus the deploy/netlify - Deploy preview ready thing in the list below. That'll save time in future. 😄

Exactly. For every PR, Netlify creates a deployment. This allows testing only the frontend (they all use the same backend), but in many cases it's enough.

**Pull request merged**
