### PR TITLE
show error if trying unpublished query in alert or dashboard

### PR DESCRIPTION
**Pull request by alison985**
Original request in https://github.com/mozilla/redash/issues/429 was to port the ability to use unpublished queries in Alerts to from Mozilla's fork to getredash/redash. PR https://github.com/getredash/redash/pull/2660 was rejected because this is not desired behavior in getredash/redash. After additional discussion in https://github.com/mozilla/redash/issues/429 the idea to let the user know that unpublished queries weren't allowed in alerts or dashboards was raised.

This PR:
* Shows a toastr error if a user selects an unpublished query to use in an alert.
* Shows a toastr error if a user selects an unpublished query to use in a dashboard.
* Disallows unpublished queries from being added as widgets to a dashboard. (Previously unpublished queries weren't shown in the default list in the modal but could still be searched for and added.)

### CODE REVIEW

**Comment by alison985** [comment]
Thanks @arikfr! I had thought about filtering them out of search results but I thought that would cause bug reports when queries the user knew existed didn't show up as expected. I had also thought about text but thought that would clutter the interface. I love the disabled with text in the dropdown idea. Here is what it looks like for alerts - please let me know you think.

screenshot 2018-09-02 13 46 31

@kocsmy

**Comment by alison985** [comment]
And here's what it looks like for the Add to Dashboard modal. Because these are A links the visual options are a little different.

screenshot 2018-09-02 14 30 58

**Comment by arikfr** [comment]
🤔not happy about different styles in how it's presented. @kocsmy do you have any thoughts?

**Comment by kocsmy** [comment]
I don't think this is bad but maybe it could be improved by
- look more like it's in a disabled state instead of the text-decoration: line-through; Gray text and background.
- the hovered active item should have a different styling.

Shall we just merge this as it is and I'll further improve?

**Comment by alison985** [comment]
@kocsmy I have been able to restyle the disabled state locally but am not having any luck on the hovered active item.

**Comment by kocsmy** [comment]
I'd suggest using 0.5 opacity on the unpublished query and the current hover state should work fine:

image

**Comment by arikfr** [comment]
Also worth using the same tag like design for `Unpublished` text as we use everywhere else.

**Comment by alison985** [comment]
@kocsmy I wanted to follow up on this one.

**Comment by jezdez** [comment]
@kocsmy Hey, anything we're missing here to move this along?

**Comment by alison985** [comment]
@kocsmy & @jezdez - wanted to follow up on this one.

**Comment by kocsmy** [comment]
Thanks for the nudge @alison985 & @jezdez 
- I've checked the design on the modal (for unpublished queries which cannot be added), it all looks good to me.

For the record, this is how it looks: 
image

@arikfr suggested that we use the same tags we are using already: 
image

And as far as I see you implemented that for the alerts: 
image

I think it's a good idea to have the same for the add widget modal on the dashboard.

**Comment by alison985** [comment]
@kocsmy Updated. Here are all the various states.

Query in Alerts for Published Query
screenshot 2018-11-25 21 33 38

Query in Alerts for Unpublished Query
screenshot 2018-11-25 21 33 46

Add to dashboard before search:
screenshot 2018-11-25 21 33 57

Add to dashboard after search:
screenshot 2018-11-25 21 34 24

Add to dashboard after search with cursor on selection:
screenshot 2018-11-25 21 34 03

Add to dashboard unpublished query:
screenshot 2018-11-25 21 34 10

**Comment by kocsmy** [comment]
Please also mind the difference between the Unpublished label and tag label design:

**Comment by alison985** [comment]
@kocsmy I removed the () and updated the styles.

**Comment by jezdez** [comment]
@kocsmy Hey, following up on this, do you know if there is anything missing in this PR?

**Comment by kocsmy** [comment]
Hey @jezdez thanks for pinging. @alison985 when I check this PR there's a misalignment (I can't see this on your screenshot though). Can you check and fix if possible, please?

image

**Comment by emtwo** [comment]
Closing this PR and will continue discussion/review here: https://github.com/getredash/redash/pull/3347

**Pull request closed without merging**
