### PR TITLE
Use set in fetch_columns for efficient

### PR DESCRIPTION
**Pull request by zhongjiajie**
Change list to set

## What type of PR is this? (check all applicable)

- [x] Other

## Description

Use set replace list more efficient, cause function `fetch_columns` call frequently, `O(1)` is better than `O(n)`

### CODE REVIEW

**Comment by zhongjiajie** [comment]
@rauchy @arikfr @gabrieldutra PTAL, thanks

**Comment by zhongjiajie** [comment]
Why this PR with failling CI, also in https://github.com/getredash/redash/pull/5338 and https://github.com/getredash/redash/pull/5337

**Comment by zhongjiajie** [comment]
PTAL this pr if you have time @justinclift @konnectr @junnplus

**Comment by zhongjiajie** [comment]
backend lint failed due to https://github.com/getredash/redash/pull/6321

**Review by konnectr — APPROVED** [review]

**Comment by justinclift** [comment]
Merged!  Thanks heaps for creating this PR @zhongjiajie, and for keeping with it through all of this extra time. :smile:

**Pull request merged**
