### PR TITLE
Fix Hive and Impala data sources for use with Cloudera's CDH versions (#1969)

### PR DESCRIPTION
**Pull request by bradrushworth**
Allow Hive and Impala data sources to work with Cloudera CDH clusters (#1969).

### CODE REVIEW

**Comment by bradrushworth** [comment]
This also fixes #1840

**Comment by sunui** [comment]
Thanks for your great work,but could you please try to solve this merging issues?

**Comment by bradrushworth** [comment]
Sorry, what merging issues?

**Comment by sunui** [comment]
Sorry，I mean make this PR get merged，and close this？

**Comment by sadilet** [comment]
@bradrushworth @sunui Is this PR actual? I need that fix. Could I help you to get merged?

**Comment by guidopetri** [comment]
@bradrushworth , thanks for the PR! We've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI, as well as updating merge conflicts?

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Pull request closed without merging**
