### PR TITLE
Add support for setup.sh on CentOS 7

### PR DESCRIPTION
**Pull request by justinclift**
Tested on CentOS 7 x64 1810, and Ubuntu 18.04.01.

Should be reasonably robust too. :smile:

### CODE REVIEW

**Comment by arikfr** [comment]
Thank you, @justinclift! This is greatly appreciated, but unfortunately we're a small team, and won't have the resources to continue testing the setup script both on Ubuntu & CentOS 😔 

How about you move the CentOS version to a different repo (or just a Gist), and we add a link to it in the README and instructions?

**Comment by justinclift** [comment]
Ahhh.  I've been clearing out my GitHub account today (deleting all my repo's, gists, etc), with the intention of finally killing my account here.

Lets just close this then, and when I set up a new location (probably spin up Gitea on a server) then we can figure it out then. :smile:

**Comment by arikfr** [comment]
Just so the effort is not lost, maybe post this version to the forum?

Also, if you are going to keep the account itself but just without your own content, I can open the repo for you.

Thanks.

**Comment by justinclift** [comment]
No worries.  I'll post it to the forum.

**Pull request closed without merging**
