### PR TITLE
Setting source_content_type on ES queries

### LINKED ISSUE #2238: ElasticSearch query fails on ES 6
### Issue Summary

Using the public docker images which seem to be based on Redash 4 (beta?) trying to setup a query for an ES 6 backend results in

    Error running query: Failed to execute query. Return Code: 500 Reason: {"error":{"root_cause":[{"type":"illegal_state_exception","reason":"source and source_content_type parameters are required"}],"type":"illegal_state_exception","reason":"source and source_content_type parameters are required"},"status":500}

### Steps to Reproduce

1. Deploy redash using the redash docker compose file
2. Deploy ES 6 backend
3. Setup ElasticSearch datasource in Redash
4. Try a simple query

### Technical details:

* Redash Version: 4.0.0 (not sure about the exact built number - can't determine it from the docker image)
* Browser/OS: Redash in docker on Ubuntu 17.10
* How did you install Redash: redash docker compose file from github pulling in redash:latest from docker hub

Looks like redash uses the `source` query parameter but as per https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html this also requires to provide a `source_content_type` parameter.

### PR DESCRIPTION
**Pull request by alexdrans**
Fixes #2238

### CODE REVIEW

**Comment by arikfr** [comment]
Just to confirm: it won't cause issues with older versions of ES?

**Comment by alexdrans** [comment]
I haven't tested it @arikfr, but according to https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests the parameter has been around since 5.3 and was only made mandatory in 6.0.

**Comment by drslump** [comment]
I'm afraid this breaks the integration with older versions (ES 5.1). Any chance to make this configurable from the data source settings?

**Comment by arikfr** [comment]
@drslump definitely possible, but can you share the more details on the issue you had?

**Comment by drslump** [comment]
@arikfr sure. Any query to ElasticSearch 5.1 (AWS flavour) fails with the following error:

```
Error running query: Failed to execute query. Return Code: 400 Reason: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/my-index/_search] contains unrecognized parameter: [source_content_type]"}],"type":"illegal_argument_exception","reason":"request [/my-index/_search] contains unrecognized parameter: [source_content_type]"},"status":400}
```

Same query against version 5.3 (AWS flavour) works properly.

**Comment by mikeflynn** [comment]
Just ran in to this today. Still an active issue.

**Comment by arikfr** [comment]
@drslump, @mikeflynn I believe this is now fixed with #2722. I tested it both with ES 6.3 and 5.2.

**Pull request merged**
