### PR TITLE
Support multi column results with using mongo query runner

### PR DESCRIPTION
**Pull request by guidopetri**
Identical contents to #6290 but with formatting fixes. I screwed up a rebase and accidentally closed the other PR irreversibly.

### CODE REVIEW

**Comment by guidopetri** [comment]
@justinclift would you kindly give me an approval on this since I can't do it myself (I'm the latest committer)? 😅

**Review by justinclift — APPROVED** [review]

**Comment by justinclift** [comment]
Just did the approve.

**Comment by guidopetri** [comment]
Thanks mate :)

**Comment by guidopetri** [comment]
@del-zhenwu thanks for these changes!

**Pull request merged**
