### PR TITLE
Cleaner approach for _is_collection_a_view

### PR DESCRIPTION
**Pull request by jodevsa**

### CODE REVIEW

**Comment by arikfr** [comment]
Thanks! Do you know if this was supported in all recent versions or it's a new addition?

**Comment by jodevsa** [comment]
It should be all versions. Let me run it on some old versions and get back to you

**Comment by arikfr** [comment]
@jodevsa did you have a chance to check this? Thanks.

**Comment by arikfr** [comment]
Thanks!

**Pull request merged**
