### PR TITLE
Base duplicate index on column names

### PR DESCRIPTION
**Pull request by rauchy**
# What type of PR is this? (check all applicable)

- [x] Bug Fix

## Description

I've noticed that duplicate column names are indexed according to the amount of duplicates, and not based off the actual column name duplicates. For example: if you join the users table with the organizations table you would see `name, created_at, updated_at, name1, created_at2, updated_at3` where I would expect `name, created_at, updated_at, name1, created_at1, updated_at1`.

Not sure if this is intentional, and also it will probably break existing queries, so feel free to reject this :)

### CODE REVIEW

**Comment by rauchy** [comment]
Duplicate of #4353.

**Comment by rauchy** [comment]
Following the edge cases provided in #4353, I believe 03d7836b should be a better solution.

**Comment by guidopetri** [comment]
@rauchy , thanks for the PR! We've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI, as well as updating merge conflicts?

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Comment by justinclift** [comment]
Attempted a manual merge just now.  No idea if it'll work, but it'll probably fail the format check.  But, lets see what happens... :smile:

**Comment by justinclift** [comment]
Just fixed the formatting with `make format`. :smile:

**Comment by guidopetri** [comment]
I think we should merge this one instead of #4353 , since this one fully encompasses the other PR. I also think we might want a test here before merging

**Comment by justinclift** [comment]
Good thinking @guidopetri, yep we'll want some kind of test. :smile:

**Pull request merged**
