### PR TITLE
Add Apache ignite Query Runner

### PR DESCRIPTION
**Pull request by sdarlington**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [X] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description

Add a query runner for Apache Ignite and GridGain, an in-memory database and cache. Tested against Apache Ignite 2.8.1+ and GridGain 8.8.4+.

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [X] Manually
- [ ] N/A

Connected to and ran SQL queries again clusters with:

* Apache Ignite and GridGain
* Un-encrypted and with TLS encryption enabled
* With and without authentication

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

Screenshot 2022-05-31 at 14 02 19

### CODE REVIEW

**Comment by guidopetri** [comment]
@sdarlington , thanks for the PR! We've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI, as well as updating merge conflicts?

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Comment by justinclift** [comment]
Interestingly, the merge conflicts just seem to be a simple one liner in the settings __init__.py, and some basic python package dependency adjustments.  Should be fairly straight forward to update. :smile:

**Comment by sdarlington** [comment]
Rebased, one minor change and some testing (against Ignite 2.15 and GridGain UE 8.8.28).

**Comment by justinclift** [comment]
Looks like it still needs a bit of tweaking to make the formatting check happy.

This *might* be helpful for doing that, depending on your dev setup:

https://github.com/getredash/redash/wiki/Local-development-setup#configuring-pre-commit

**Comment by sdarlington** [comment]
Urgh, sorry, I missed the `make format` step. Fixed:

```
SDarlington-MBProM2:redash stephen.darlington$ make format
pre-commit run --all-files
isort....................................................................Passed
black....................................................................Passed
flake8...................................................................Passed
SDarlington-MBProM2:redash stephen.darlington$ 
```

**Comment by justinclift** [comment]
Thanks, it's re-running the tests now. :smile:

**Comment by justinclift** [comment]
Cool.  Looks like everything's passing, except the Code coverage tests.

We haven't really set any hard measures in place for Code coverage of query runners, though it you reckon it'd be easy to add tests to covering that (?) then it's probably worth doing.

@sdarlington Thoughts? :smile:

**Comment by sdarlington** [comment]
I added some very basic tests. There's only so much that can be done without running a GridGain cluster!

**Comment by justinclift** [comment]
> There's only so much that can be done without running a GridGain cluster!

Yeah, that's pretty much my thinking about tests for query runner code too.

We have some initial concept/ideas for creating some new query runner testing (maybe running once per week or something?).  But that's not going to be relevant in the short term. :wink:

**Comment by justinclift** [comment]
Cool, looks good enough.

Thanks for taking the time on this @sdarlington. :smile:

**Comment by justinclift** [comment]
@sdarlington We're having a problem with the `pygridgain` dependency, as it has a hard coded requirement on `tzlocal` version 2.1.

Unfortunately our Trino data source has a hard requirement on `tzlocal` version 4.x.

If we drop the `pygridgain` dependency, will people still be able to connect to Gridgain data sources using the pyignite code?

I'm hoping for a "yes", but guessing it'll be a "no". :sweat_smile:

**Comment by justinclift** [comment]
I've created an issue in the pygridgain repo, asking if there's a chance they could update tzlocal to the 4.x series:

https://github.com/gridgain/python-thin-client/issues/62

Just in case it's not too much of a problem. :smile:

**Comment by sdarlington** [comment]
@justinclift The engineering team say they'll take a look at updating the dependencies.

If this is blocking you, given that it's a new feature that no one is currently using, I would be okay with temporarily taking out the GridGain library. (I won't bore you with the details, but the protocols have diverged a little. GridGain does largely work with the Ignite library, but there are some limitations/bugs.)

**Comment by justinclift** [comment]
Thanks @sdarlington.  It can probably wait a few days, so if it turns out they can easily update that tzlocal dependency in the meantime then I think we're good. :smile:

**Comment by justinclift** [comment]
@sdarlington Would you be ok to ping the engineering team and see how they're going with this?

It's been ~2 weeks and I'm not seeing any changes in that gridgain repo, so I'm inclined to remove it from our repo.  That way we can get the Trino data source working again.

**Comment by justinclift** [comment]
Thanks for checking @sdarlington. :grin:

In that case, we'll remove the `pygradgain` dependency for now so that Trino data sources begin working again.  When the GridGain stuff is fixed, please let us know and/or create a PR to add it back (if you reckon it'll be useful). :smile:

**Pull request merged**
