### PR TITLE
README: update list of supported data sources

### PR DESCRIPTION
**Pull request by aniket-s-kulkarni**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [X] Other

## Description
This PR just updates the README as a follow on to PR #5771 

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [X] N/A

### CODE REVIEW

**Comment by aniket-s-kulkarni** [comment]
@susodapop I created a small followup PR to #5790 - just ensure the README reflects Netezza as one of the supported data sources.

**Comment by susodapop** [comment]
Thank you! If you don't mind, let's use this as an opportunity to double check that the list in README is completely up-to-date with the contents of `./redash/query_runner`. I can make the changes if you grant me access to your branch.

**Comment by aniket-s-kulkarni** [comment]
> Thank you! If you don't mind, let's use this as an opportunity to double check that the list in README is completely up-to-date with the contents of ./redash/query_runner. I can make the changes if you grant me access to your branch.

@susodapop do you mean [this repo](https://github.com/getredash/website/edit/master/src/pages/kb/data-sources/supported-data-sources.md)? 

I can add you to my branch if that helps.

**Comment by susodapop** [comment]
> @susodapop do you mean [this repo](https://github.com/getredash/website/edit/master/src/pages/kb/data-sources/supported-data-sources.md)?

I was referring actually to the same README this current pull request changes. But yes, the getredash/website page should also be updated. IMO it's more important for our README to be most up-to-date, though. It's okay if getredash/website is a bit behind.

**Comment by aniket-s-kulkarni** [comment]
> I was referring actually to the same README this current pull request changes. But yes, the getredash/website page should also be updated. IMO it's more important for our README to be most up-to-date, though. It's okay if getredash/website is a bit behind.

OK

> I can make the changes if you grant me access to your branch.

@susodapop I have added you to my branch.

**Review by susodapop — APPROVED** [review]

**Comment by aniket-s-kulkarni** [comment]
@susodapop so are we good to merge this branch ?

**Comment by susodapop** [comment]
Yes, I was on hold until the PR checks all passed 😃

**Pull request merged**
