### PR TITLE
Origin username should be included in metadata for scheduled queries

### PR DESCRIPTION
**Pull request by evgenyx00**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description
When a scheduled query is configured, the scheduler sends the query metadata using a fixed username "Scheduled," thereby limiting the capability to trace the query's source.
This fix set username metadata field with the valid owner of the query.

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [x] Manually
- [ ] N/A

Tested manually the change by creating a scheduled query, and verified correct value is sent in the Username field.
Moreover, other tests are already covering these changes.

### CODE REVIEW

**Comment by justinclift** [comment]
This sounds pretty reasonable to me. :smile:

**Comment by justinclift** [comment]
@konnectr @gaecoli Does this PR seem ok to yourselves? :smile:

**Comment by gaecoli** [comment]
> @konnectr @gaecoli Does this PR seem ok to yourselves? 😄

I'm OK!

**Comment by justinclift** [comment]
Thanks.  Merging it. :smile:

**Comment by justinclift** [comment]
Thanks for this PR @evgenyx00. :smile:

**Pull request merged**
