### PR TITLE
Update yarn network-timeout: 30s(default) -> 600s

### PR DESCRIPTION
**Pull request by winebarrel**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [x] Other

## Description

In the docker build of GitHub Actions, yarn failed with ESOCKETTIMEDOUT, so change the network-timeout.

cf. https://github.com/getredash/redash/actions/runs/6533929053/job/17752711820#step:9:2944

> #35 1402.3 error An unexpected error occurred: "https://registry.yarnpkg.com/core-js/-/core-js-2.6.12.tgz: ESOCKETTIMEDOUT".

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [x] N/A

## Related Tickets & Documents

- https://github.com/getredash/redash/pull/6525

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

N/A

### CODE REVIEW

**Comment by justinclift** [comment]
Ahhh, cool.  I was thinking we might need to back out the arm64 PR, but if this works instead then it's the better way to go.

**Review by justinclift — APPROVED** [review]

**Comment by justinclift** [comment]
Interestingly, with this value changed the CI docker push job no longer times out immediately. :partying_face:

Instead, it times out after six hours (building arm64 image very, very, very slowly): :frowning_face:

image

**Comment by justinclift** [comment]
We'd better back out this change, and the arm64 one too, so that `preview` Docker Hub builds start being reliably created again.

That being said, if there's some way to get the arm64 builds working reliably later on then that'd be welcome. :smile:

**Comment by winebarrel** [comment]
@justinclift Sorry for breaking the test..

Thanks for undoing the changes.

**Comment by justinclift** [comment]
It's no worries.  It was worth trying out the PR just in case it all worked. :smile:

Don't be afraid to experiment and try things out. :grin:

**Pull request merged**
