### PR TITLE
convert docker-compose to docker compose

### PR DESCRIPTION
**Pull request by guidopetri**
## What type of PR is this? 

- [x] Other

## Description

Docker now has `compose` support within it, and installing the latest version of `docker` allows for `docker compose`. The old [docker-compose syntax is being deprecated](https://docs.docker.com/compose/migrate/#docker-compose-vs-docker-compose). This change moves us from the old `docker-compose` syntax to the new `docker compose` syntax.

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [x] Manually
- [ ] N/A

Via PR checks.

### CODE REVIEW

**Comment by justinclift** [comment]
What version of Docker are you using that works with this?

Asking so we have some idea of a known-good configuration. :smile:

**Comment by guidopetri** [comment]
I'm on docker 24. If you follow the current install instructions, it seems to just get the latest version: https://docs.docker.com/engine/install/debian/#install-using-the-repository

**Comment by justinclift** [comment]
From eyeballing the change, it *looks* fairly straight forward.

I've not personally used the v2 docker compose commands yet though, so no practical experience of potential gotchas we should watch out for.

I guess we can merge it, and if something goes badly wrong then we can revert the change (or fix whatever the problem is).

**Review by justinclift — APPROVED** [review]

**Comment by eradman** [comment]
@guidopetri can youupdate the dev environment setup instructions to match this change?

https://github.com/getredash/redash/wiki/Local-development-setup#set-up-the-prerequisites

**Comment by guidopetri** [comment]
Ah, yes! Good call.

**Comment by guidopetri** [comment]
@eradman thanks again for updating those docs for me 😅

**Pull request merged**
