### PR TITLE
Add 'connection_source' property in presto query runner

### PR DESCRIPTION
**Pull request by iamhongri**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source)
- [ ] New Alert Destination
- [x] Other

## Description
 - Add 'connection_source' property in presto query runner

### CODE REVIEW

**Comment by guidopetri** [comment]
@iamhongri , thanks for the PR! We've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI, as well as updating merge conflicts?

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Comment by justinclift** [comment]
The resolve conflicts in this PR look like they were mostly due to differing formatting, so I just manually reformatted those a bit differently.  Hopefully got it right.

This PR looks like it's never been reviewed though, so even if it passes CI now it'll still need to be looked over properly.

**Comment by justinclift** [comment]
Ahhh.  Looks like I didn't get the reformatting correct enough for `black --check` to be happy with. :frowning:

**Comment by justinclift** [comment]
@iamhongri This should be super easy to fix, if you're interested in it still. :smile:

**Comment by guidopetri** [comment]
Closing due to lack of activity. Feel free to reopen if you want to come back to this PR!

**Pull request closed without merging**
