### PR TITLE
Update maildev path in developer docker compose

### PR DESCRIPTION
**Pull request by rjmunro**
## What type of PR is this? (check all applicable)

- [x] Other

## Description

The docker compose file was using an outdated path for the maildev test mail server.
It's moved to maildev/maildev.

### CODE REVIEW

**Comment by susodapop** [comment]
Nice catch. Captured the following from [docker hub](https://hub.docker.com/r/djfarrelly/maildev/#!) today.

CleanShot 2022-03-03 at 13 11 37@2x

**Review by susodapop — APPROVED** [review]
LGTM

Thanks!

**Comment by soulteary** [comment]
Hello project maintainers @rjmunro @susodapop 

I came across this pr by searching, recently maildev updated a new version, I recommend you to use the new version

docker image, maildev/maildev is not ready yet, you can use `soulteary/maildev` first, Hope it helps you

**Comment by rjmunro** [comment]
@susodapop I've rebased it to latest master and force pushed. That will ensure it's up to date with any other changes on master and trigger a rebuild without the need to pollute history with empty commits.

**Comment by rjmunro** [comment]
@soulteary The latest version of maildev/maildev is 2.0.4 and was pushed 15 hours ago as I write this, by the djfarrelly account who created the original version. So I don't think there is anything to gain by switching to your fork.

https://hub.docker.com/r/maildev/maildev/tags

**Comment by soulteary** [comment]
@rjmunro In fact, my fork was merged into the original repo shortly after I left a comment **one or two months ago**. 😄

It really doesn't do any good to look at this two months later. Just ignore that message.

**Comment by eradman** [comment]
Thanks for pointing this out @rjmunro. The maildev image was updated in commit 65d0eb

**Pull request closed without merging**
