### PR TITLE
add codecov action

### PR DESCRIPTION
**Pull request by junnplus**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

### CODE REVIEW

**Comment by junnplus** [comment]
It appears that the codecov robot did not report the coverage.

**Comment by justinclift** [comment]
How easy is it to experiment with it in your fork, and find out what's wrong there? :smile:

**Comment by junnplus** [comment]
> How easy is it to experiment with it in your fork, and find out what's wrong there? 😄

I guess it could be that the codecov bot was not granted permission.

**Comment by justinclift** [comment]
@arikfr Do you have time to look at this?

**Comment by arikfr** [comment]
I added the Codecov earlier today (~12 hours ago). Maybe need to trigger it again somehow?

**Comment by justinclift** [comment]
It doesn't seem to be completely going wrong:

Looking at the `backend-unit-tests` output, it shows generation of the coverage.xml near the end of the `Run Tests` section:

```
Coverage XML written to file coverage.xml
```

Further down, the `Upload coverage reports to Codecov` section is populated with stuff that seems to mean that piece worked:

```
[...]
[2023-07-11T03:37:28.218Z] ['info'] => Found 1 possible coverage files: coverage.xml
[...]
[2023-07-11T03:37:29.219Z] ['info'] Uploading...
[2023-07-11T03:37:29.414Z] ['info'] {"status":"success",
"resultURL":"https://app.codecov.io/github/getredash/redash/commit/2b0656f4a26b42b6d9b15daffd2866b3822a4772"}
```

Further down again, the `Store Coverage Results` section indicates that seems to have worked too:

```
With the provided path, there will be 1 file uploaded
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
Container for artifact "coverage" successfully created. Starting upload of file(s)
Total size of all the files uploaded is 37884 bytes
File upload process has finished. Finalizing the artifact upload
Artifact has been finalized. All files have been successfully uploaded!
[...]
Artifact coverage has been successfully uploaded!
```

So, those parts seem to be ok at least.

**Comment by justinclift** [comment]
The permissions for Codecov in the repo seem correct.  It has the permissions shown here:

https://docs.codecov.com/docs/github-2-getting-a-codecov-account-and-uploading-coverage

**Comment by justinclift** [comment]
Cool, that looks like it worked. :smile:

**Comment by junnplus** [comment]
> The permissions for Codecov in the repo seem correct. It has the permissions shown here:

Sorry, I forgot to submit the configuration file for codecov. By default, it won't report coverage if there are no code changes.

**Comment by justinclift** [comment]
Cool.  This seems like a win. :smile:

**Review by justinclift — APPROVED** [review]
Cool.  This seems like a win. :smile:

**Pull request merged**
