### PR TITLE
(WIP) SystemStatus query runner (get Redash system status using SQL)

### PR DESCRIPTION
**Pull request by kravets-levko**
## What type of PR is this? (check all applicable)

- [x] Feature
- [x] New Query Runner (Data Source)

## Description

I haven't been sleeping and decided to try myself in creating query runners. This is just an experiment inspired by https://github.com/getredash/redash/pull/3568#issuecomment-471999196

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

image

image

### CODE REVIEW

**Comment by ranbena** [comment]
So awesome! 🤩

**Comment by arikfr** [comment]
@ranbena 

> Conceptually, not sure this should be a new query runner cause it contains actual data.

Interesting definition, but I'm not sure the fact it provides its own data disqualifies it from being a query runner on its own.

Having said that, it will be useful if this data source could connect to remote instances as well. The only change is to load the data from the `/status.json` API instead of reading directly. Then in the data source configuration it can take a URL and API key.

**Comment by kravets-levko** [comment]
Another +1 for using data source for system status: it will obey common ACL rules. Current `/status.json` is hard-locked to admins only and cannot be shared with other users; if making that URL available to all - it couldn't be restricted. With data source it becomes really flexible: we can add it by default when setting up redash instance, but make it available only for admin group; if somebody wants - he can share it with other users.

**Comment by kravets-levko** [comment]
Added an example how it could be used to retrieve celery workers status:

image

**Pull request closed without merging**
