### PR TITLE
Hide dashboards that current user cannot see based on his groups

### PR DESCRIPTION
**Pull request by gseva**
This pr is based on https://github.com/getredash/redash/pull/878

The difference is that text widgets are public. And i also added some tests.

### CODE REVIEW

**Comment by arikfr** [comment]
I've added a few more tests and merged. Thank you!

Btw, I'm wondering if we should enforce this when trying to access the dashboard directly (with the URL)?

**Comment by arikfr** [comment]
@yanenok note that this includes your work as well, so thank you both!

**Comment by gseva** [comment]
@arikfr 
Thanks for merging!
Regarding the direct access, i think it makes sense to redirect to or show nothing at all. But actually it wouldn't show data in that case, so i guess it's ok

**Comment by arikfr** [comment]
The title might leak information, but I guess it's not that big of a deal. Will leave as is for now.

**Pull request merged**
