### PR TITLE
Changed asc_url to entity_id

### PR DESCRIPTION
**Pull request by DSigmund**
Respect the User Setting instead of a hardcoded  value

## What type of PR is this? 

- [x] Bug Fix

## Description
See https://github.com/getredash/redash/issues/6201

## How is this tested?

- [x] Unit tests (pytest, jest)
- [x] E2E Tests (Cypress)
- [x] Manually (Login via ADFS against Local IDP)
- [ ] N/A

## Related Tickets & Documents
https://github.com/getredash/redash/issues/6201

### CODE REVIEW

**Comment by justinclift** [comment]
@getredash/maintainers Is anyone around who understands SAML and has time to review this Python PR? :smile:

**Review by guidopetri — APPROVED** [review]
I'm comfortable merging this in if @DSigmund you could confirm that you've deployed this and it works as expected.

I don't think any of the current maintainers have enough SAML knowledge to truly review this PR.

**Comment by DSigmund** [comment]
It works as expected :-)

Many Thanks for merging it!

**Comment by myonlylonely** [comment]
@guidopetri @DSigmund
It seems this commit breaks our existing SAML config, which works on other system as well (like Sentry).
I can no longer login by SAML after this commit.
What exactly does this commit do? What should I change?

**Comment by DSigmund** [comment]
Hi,

It fixes the Setting where you have to enter a SAML-URL.
You are now able and must enter the correct URL as written in the
instructions.

**Comment by seiyeah78** [comment]
I probably encountered this bug. 
After making changes for the upgrade from V8 to V10, I set the Azure AD's entity id to REDASH_SAML_ENTITY_ID, but I ran into an error and couldn't log in successfully. 
It worked when I made the Azure AD's entity id exactly the same as the URL for the callback (Assertion Consumer Service URL). 
I realized that part of the request was becoming the URL for the callback. 
This fix will likely revert it back to normal. 

Thank you for addressing this.

**Pull request merged**
