### PR TITLE
Add ITEMS_PER_PAGE parameter

### PR DESCRIPTION
**Pull request by kyoshidajp**
Now, only 15 items display per query result page. I would like to check more items without page transition.

I add the parameter `ITEM_PER_PAGE` which enable to specify how many items can display in result list per page.

### CODE REVIEW

**Comment by arikfr** [comment]
Before finishing release v4 we're going to have #1356 implemented, which will include the ability to control # of rows to display.

At first I thought of closing this pull request in favor of #1356, but maybe there is still a place for a global setting? WDYT?

**Comment by kyoshidajp** [comment]
My opinion is that it would be better to control number of rows as a default configuration, aside from each query.

**Comment by kyoshidajp** [comment]
This feature was implemented by #2993.

**Comment by jezdez** [comment]
Thanks @kyoshidajp :)

**Pull request closed without merging**
