### PR TITLE
add fork dashboard function

### PR DESCRIPTION
**Pull request by gaecoli**
## What type of PR is this? 

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

## Related Tickets & Documents

Add fork dashboard function

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

image

### CODE REVIEW

**Comment by gaecoli** [comment]
@guidopetri 
image

how to fix this?

**Comment by gaecoli** [comment]
> @guidopetri image
> 
> how to fix this?

I have fixed it done!

**Comment by gaecoli** [comment]
@justinclift can you review this pr?

**Review by guidopetri — APPROVED** [review]
Looks like this should work to me. Thanks @gaecoli !

**Comment by gaecoli** [comment]
Thank you! @justinclift @guidopetri

**Pull request merged**
