### PR TITLE
Fix: Cannot refresh if a query name contain control characters.

### PR DESCRIPTION
**Pull request by iwakiriK**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
If a query name contains control characters, it cannot be refreshed.

control characters

We find out that the problem occurs in the response header.
https://github.com/getredash/redash/blob/v10.0.0-beta/redash/handlers/query_results.py#L422

This PR will fix this problem.

### How to Reproduce
- Create a query
- Copy a control character and paste them in the query name
  - http://www.unicode-symbol.com/u/0010.html
- Reload

## Related Tickets & Documents
https://www.regular-expressions.info/unicode.html
https://www.compart.com/en/unicode/category
https://pypi.org/project/regex/
https://stackoverflow.com/questions/1832893/python-regex-matching-unicode-properties/4316097#4316097

### CODE REVIEW

**Comment by guidopetri** [comment]
@iwakiriK , thanks for the PR! Same here, we've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI, as well as updating merge conflicts?

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Comment by justinclift** [comment]
Just attempted to fix the merge conflict using the web interface.  It'll probably need some formatting clean up though.

**Comment by justinclift** [comment]
@konnectr Any interest in reviewing this?  It's passing our CI tests, and looks fairly simple. :smile:

**Review by konnectr — APPROVED** [review]

**Comment by justinclift** [comment]
Thanks heaps @konnectr. :smile:

**Pull request merged**
