### PR TITLE
Add the option to take new custom version for Snapshot

### PR DESCRIPTION
**Pull request by lucydodo**
## What type of PR is this? 

- [x] Other

## Description

When we needed to manually change the snapshot version, we had to run a few commands manually,
but this PR makes it a little easier. Once these PRs are merged, the following options are available in the 'Periodic Snapshot'.

Screenshot 2024-08-01 at 16 53 36
Each option causes the following behavior to occur:

- 'Bump the...': Increate the last digit in the current version by 1
- 'Specific...': Use the entered value as the new version.
- If both options are selected, the CI will abort with the following error
Screenshot 2024-08-01 at 16 55 17

https://github.com/getredash/redash/blob/1053a3341de7e4c0c390e8969641bff9a3c6f411/.github/workflows/periodic-snapshot.yml#L52

On a related note: this code is part of the syntax in GitHub Actions Workflow that outputs the error in the image above.

### Why run the command below
https://github.com/getredash/redash/blob/1053a3341de7e4c0c390e8969641bff9a3c6f411/.github/workflows/periodic-snapshot.yml#L84

GitHub does not trigger existing workflows for commits, tags, etc. that changed with `GH_TOKEN`.
Therefore, I have specified to run the workflow manually, please refer the following article for more information:
> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN, with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run.
[Automatic token authentication - GitHub Docs](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow)

## How is this tested?

- [x] Manually

I confirmed it works fine on my repo.

## Related Tickets & Documents

Not applicable.

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
Not applicable.

Any comments or review are welcome. Thank you.

### CODE REVIEW

**Comment by justinclift** [comment]
This seems useful. :smile:

@eradman You'll probably be interested in this, as it tweaks how the monthly tag name is done.  Looks like a decent progression. :smile:

**Review by justinclift — APPROVED** [review]
The concept sounds decent to me, and the code looks fine too. :smile:

**Comment by eradman** [comment]
I couldn't get this to work on my own repo: this is the result of checking "Bump the last digit of the version"

gh-workflow-1

**Comment by justinclift** [comment]
Disabled workflow?

**Comment by lucydodo** [comment]
Hi @eradman,
Screenshot 2024-08-03 at 04 25 37
> https://github.com/eradman/redash/actions/workflows/preview-image.yml

My guess is that you disabled the 'Preview Image' workflow yourself.
To the right of the search bar you see in the screenshot, there should be an option to re-enable it by pressing the menu button. Enable it and try again. I just checked and it still works fine for my repos. :)

**Comment by eradman** [comment]
Thanks @justinclift @lucydodo! I enabled the "Preview Image" workflow and was able to run this manually

**Pull request merged**
