### PR TITLE
Update requests module to 2.32.2

### PR DESCRIPTION
**Pull request by eradman**
## What type of PR is this? 

- [x] Bug Fix

## Description

The requests 2.32.0 module was yanked

## How is this tested?

- [x] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

## Related Tickets & Documents

https://github.com/getredash/redash/pull/7049

### CODE REVIEW

**Comment by justinclift** [comment]
s/poetry/requests/ ?

**Comment by eradman** [comment]
> s/poetry/requests/ in the title?

Oops, Yes! Fixed

**Review by justinclift — APPROVED** [review]
Looks good to me. :smile:

**Comment by justinclift** [comment]
Shouldn't we do the `update branch` thing for this PR too, as it's probably going to need that before being mergable anyway?

**Pull request merged**
