### PR TITLE
Fix viz-lib failing with npm version 7

### LINKED ISSUE #5235: npm install throws "Could not resolve dependency" (upstream dependency conflict) when using npm 7
### Issue Summary

npm install throws "Could not resolve dependency" (upstream dependency conflict) when using npm 7

### Steps to Reproduce

1. Use npm 7: `sudo npm -g install npm@~7`
2. Clone redash master
3. `npm install`

You get:

```
ubuntu@ip-172-31-23-99:~/redash$ npm install

> redash-client@9.0.0-beta postinstall
> (cd viz-lib && npm ci && npm run build:babel)

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @redash/viz@0.1.1
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   peer react@">=16.8.0" from the root project
npm ERR!   peer react@">=16.9.0" from antd@4.7.3
npm ERR!   node_modules/antd
npm ERR!     peer antd@">=4.0.0" from the root project
npm ERR!   1 more (react-dom)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.x" from @ant-design/icons@4.2.2
npm ERR! node_modules/@ant-design/icons
npm ERR!   peer @ant-design/icons@">=4.0.0" from the root project
npm ERR!   @ant-design/icons@"^4.2.1" from antd@4.7.3
npm ERR!   node_modules/antd
npm ERR!     peer antd@">=4.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/ubuntu/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-10-25T11_02_22_326Z-debug.log
npm ERR! code 1
npm ERR! path /home/ubuntu/redash
npm ERR! command failed
npm ERR! command sh -c (cd viz-lib && npm ci && npm run build:babel)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-10-25T11_02_22_408Z-debug.log
```

*Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?*

As noted in the error message, it happens because npm 7 has better/stricter peer dependency resolution.

**Workaround**

As noted in error message, you can use `--legacy-peer-deps` to force npm 6 behavior. However this should be solved properly.

```
ubuntu@ip-172-31-23-99:~/redash$ npm install --legacy-peer-deps

> redash-client@9.0.0-beta postinstall
> (cd viz-lib && npm ci && npm run build:babel)


added 1396 packages, and audited 1462 packages in 21s

17 vulnerabilities (5 low, 8 moderate, 4 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.

> @redash/viz@0.1.1 build:babel
> babel src --out-dir lib --source-maps --ignore 'src/**/*.test.js' --copy-files --no-copy-ignored

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Successfully compiled 150 files with Babel.

added 5 packages, and audited 2931 packages in 42s

46 vulnerabilities (17 low, 10 moderate, 18 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

### Technical details:

* Redash Version: 66463aedd44ea179b3b92e2baf51bb698c72f672
* Browser/OS: Ubuntu 20.04.1 aarch64
* How did you install Redash: git clone master branch

### PR DESCRIPTION
**Pull request by gabrieldutra**
## What type of PR is this? (check all applicable)

- [x] Other

## Description

After npm 7 the peerDependencies are actually installed, so this was creating a conflict. I've changed the way they are declared and also took the opportunity to add `engines` to the file.

Fixes #5235

## Related Tickets & Documents
--

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
--

### CODE REVIEW

**Review by kravets-levko — APPROVED** [review]

**Comment by gabrieldutra** [comment]
Just noticed I changed the npm version from `nvm` for the wrong local folder 😅 

Since it actually installs peerDependencies from this version, the Double-React problem I was afraid indeed happened:

image

So, this still won't fix it for npm version 7 😬, Removing all the peerDependencies should work, but I'll look into better solutions.

**Comment by kravets-levko** [comment]
@gabrieldutra I think the root of all problems is that we don't install `viz-lib` as a regular npm module, so npm doesn't build a proper dependency tree and doesn't deduplicate dependencies. It treats `viz-lib` as a separate project within redash, but not its dependency. So maybe let's look for a solution in this direction? No clear sight what to do, maybe `npm link` will help

**Comment by gabrieldutra** [comment]
> @gabrieldutra I think the root of all problems is that we don't install `viz-lib` as a regular npm module, so npm doesn't build a proper dependency tree and doesn't deduplicate dependencies. It treats `viz-lib` as a separate project within redash, but not its dependency. So maybe let's look for a solution in this direction? No clear sight what to do, maybe `npm link` will help

Yep, it's not a simple setup anyway. I did consider `npm link` when I set up the lib, I don't remember what specifically made me not use it. But one thing that seemed to best fit this setup was yarn workspaces, it just happened that I haven't had enough reason to test this yet.

**Comment by gabrieldutra** [comment]
> Is this PR still useful?

For viz-lib specifically, probably no, since it's now working with the LTS Node version 😅

**Comment by justinclift** [comment]
Awesome, thanks. :smile:

**Pull request closed without merging**
