### PR TITLE
Support pandas dataframe

### PR DESCRIPTION
**Pull request by bryanyang0528**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source)
- [ ] New Alert Destination
- [ ] Other

## Description

A proposed solution for solving issue #2078 
In a data team, our data scientists usually use pandas and dataframe to manipulate data. This function will make their life easier. 

## Related Tickets & Documents

#2078

It will look like this:

Screen Shot 2020-03-13 at 19 19 52

### CODE REVIEW

**Comment by denisov-vlad** [comment]
Thanks!

I think pandas -> redash columns conversion could be written in another way. We use this code snippet inside Python query runner:

```
for column_name, column_type in df.dtypes.iteritems(): # use items() for python 3
    if column_type == np.bool:
        redash_type = TYPE_BOOLEAN
    elif column_type == np.inexact:
        redash_type = TYPE_FLOAT
    elif column_type == np.integer:
        redash_type = TYPE_INTEGER
    elif column_type in (np.datetime64, np.dtype('<M8[ns]')):
        # date or datetime?
        if len(df[column_name].head(1).astype(str).loc[0]) > 10:
            redash_type = TYPE_DATETIME
        else:
            redash_type = TYPE_DATE
    else:
        redash_type = TYPE_STRING
    
    add_result_column(result, column_name, column_name, redash_type)
```

**Comment by guidopetri** [comment]
@bryanyang0528 , thanks for the PR! We've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI, as well as updating merge conflicts?

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Comment by justinclift** [comment]
I've just push a commit to this PR which does the re-formatting (`make format`) so the `backend-lint` test will now pass.

Now it should be ok to review (@guidopetri maybe?) then merge. :smile:

**Comment by justinclift** [comment]
Oh no, it looks like one of the backend unit tests is failing now.  Seems like this PR may need a bit more work after all. (!)

Going to re-run the tests again now, just in case that failure was something not related to this PR (maybe network problem again?).  Lets see what happens... :smile:

**Comment by justinclift** [comment]
Looks like an actual failure that needs investigation. :frowning: 

@bryanyang0528 Do you have time & interesting to look into it? :smile:

**Comment by guidopetri** [comment]
Closing due to lack of activity. Feel free to reopen if you want to come back to this PR!

**Pull request closed without merging**
