### PR TITLE
ci: migrate to github workflow ci

### PR DESCRIPTION
**Pull request by junnplus**
## What type of PR is this? 

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## How is this tested?

- [x] Unit tests (pytest, jest)
- [x] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

### CODE REVIEW

**Comment by Avey777** [comment]
> ## What type of PR is this?
> * [x]  Refactor
> * [ ]  Feature
> * [ ]  Bug Fix
> * [ ]  New Query Runner (Data Source)
> * [ ]  New Alert Destination
> * [ ]  Other
> 
> ## Description
> ## How is this tested?
> * [x]  Unit tests (pytest, jest)
> * [x]  E2E Tests (Cypress)
> * [ ]  Manually
> * [ ]  N/A
> 
> ## Related Tickets & Documents
> ## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

I'm looking forward to you merging the code into the main branch, everyone is waiting here

**Comment by justinclift** [comment]
As a data point, this PR worked fine in the new [RedashCommunity](https://github.com/RedashCommunity/redash) fork once we removed the `--record` from Cypress, as we're not setup to record: https://github.com/RedashCommunity/redash/commit/a5d12b1740402a25dce6ded436af5e3fbd227d79

That's unlikely to be a problem here though, so it should be fine as-is.  In theory. :wink:

**Comment by gabrieldutra** [comment]
I did not have time to fully test it (i.e.: artifacts, BE jobs, any automated `master` script), but when I checked the only thing I could notice was related to the Cypress Cloud itself, as the Git context was lost from it: 

Screenshot 2023-05-11 at 13 44 12

**Comment by justinclift** [comment]
Ahhh.  Yeah, that might indicate something that needs looking into for this repo.

For the RedashCommunity repo, we're still figuring out how all the pieces fit together.  eg there are hard coded keys parts of the CI, so we're avoiding uploading to Cypress Cloud, Percy (etc) until we have a better handle on stuff. :smile:

**Comment by justinclift** [comment]
Ugh.  I rebased it onto the wrong repo `master`.  :facepalm:

Fixing...

**Comment by justinclift** [comment]
@junnplus This is finally merged here! :smile:

**Pull request merged**
