### PR TITLE
Feature: Add option to hide widget level filters

### PR DESCRIPTION
**Pull request by yoavbls**
## What type of PR is this? (check all applicable)

- [x] Feature

## Description
When dashboard filters are enabled all the widgets still keep their filters and make 
a lot of visual noise and redundancy.
In this PR I Added another flag that shows only when dashboard filters are checked
and let you choose to hide the filters in the widget level.

## Related Tickets & Documents
#3074

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
Before:
image

After:
image

### CODE REVIEW

**Comment by rauchy** [comment]
Thanks @yoavbls, LGTM.

I'm wondering if two checkboxes are even required - maybe selecting dashboard level filters should automatically hide widget filters? WDYT @arikfr?

**Comment by arikfr** [comment]
> I'm wondering if two checkboxes are even required - maybe selecting dashboard level filters should automatically hide widget filters? WDYT @arikfr?

This makes sense. I just wonder if it's worth having both options for the sake of backward compatibility? 🤔

**Comment by rauchy** [comment]
> I just wonder if it's worth having both options for the sake of backward compatibility? 🤔

I think we should bite the bullet and allow toggling between dashboard-level and widget-level. Having both displayed feels confusing to me.

**Comment by arikfr** [comment]
Hi,

(This is a template message, but I mean every word of it. Also you're welcome to reply)

Thank you for making this contribution. While we couldn't bring it to completion and merge, it's still very much appreciated. 🙇

In the past year the Redash code base gone under massive updates: on the backend we moved to Python 3 & RQ instead of Celery and on the frontend we replaced Angular with React. It's very likely this makes this PR irrelevant without significant changes. :-( 

I'm closing this PR now. But if you're still interested in making it happen, let me know and I will reopen.

Thanks.

**Pull request closed without merging**
