### PR TITLE
Revert "show pg and athena column comments and table descriptions as …

### PR DESCRIPTION
**Pull request by eradman**
## What type of PR is this? 

- [x] Revert

## Description

This commit did not sort tables properly by schema, then name.

## How is this tested?

- [x] Unit tests (pytest, jest)
- [x] E2E Tests (Cypress)
- [x] Manually

## Related Tickets & Documents

https://github.com/getredash/redash/discussions/6964

### CODE REVIEW

**Comment by justinclift** [comment]
For reference, the original PR this is reverting is #6582.

**Comment by justinclift** [comment]
@gaecoli Would you be ok to look over this one as well? :pray:

**Comment by gaecoli** [comment]
> @gaecoli Would you be ok to look over this one as well? 🙏


What happened? Why should this be reverted?

**Comment by eradman** [comment]
> > @gaecoli Would you be ok to look over this one as well? 🙏
> 
> What happened? Why should this be reverted?

The list of tables is no longer sorted by schema and table name in the query editor.

We can, of course fix this but there were changes in this commit that I do not understand.

**Comment by gaecoli** [comment]
> > > @gaecoli Would you be ok to look over this one as well? 🙏
> > 
> > 
> > What happened? Why should this be reverted?
> 
> The list of tables is no longer sorted by schema and table name in the query editor.
> 
> We can, of course fix this but there were changes in this commit that I do not understand.

Ok.

**Review by gaecoli — APPROVED** [review]
LGTM!

**Comment by justinclift** [comment]
Thanks @eradman and @gaecoli. :smile:

**Pull request merged**
