### PR TITLE
Chart: Bubble size control by coefficient and sizemode

### PR DESCRIPTION
**Pull request by deecay**
## What type of PR is this? (check all applicable)

- [x] Feature

## Description
This PR will enable 

1. users to control the bubble size in bubble chart, by defining a fixed numeric coefficient. Coefficient of 0.5 reduces the size of the bubble to half. This is essential when Bubble size column is too large or too small compared to the x and y axis columns.
2. users to specify what the bubble size column value will be proportional to; area or diameter.

## Related Tickets & Documents

Closes getredash/redash#4411

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

**Original Chart**
image

**Coefficient set to 0.07**
image

**Editor**
image

**Table**
image

### CODE REVIEW

**Comment by deecay** [comment]
Ready for review.

**Comment by kravets-levko** [comment]
Hi @deecay! I reviewed your code - everything look good. Could you please sync with master, so I can finally check everything and merge this PR? Thanks!

**Comment by deecay** [comment]
@kravets-levko, done.

**Comment by deecay** [comment]
@kravets-levko 
Fixed. Thanks for your support.

**Comment by kravets-levko** [comment]
Thank you @deecay! :rocket:

**Pull request merged**
