### PR TITLE
add ability to add viz to dashboard from query page 

### LINKED ISSUE #955: Add a button / drop-down from the query window to quickly add it to a dashboard.

### PR DESCRIPTION
**Pull request by alison985**
fixes #955

This PR ports the Mozilla functionality upstream.

I had to make a minor tweak to get it to run in the current redash code. I also added feedback to the user that the widget was added successfully which is not in Mozilla's branch.

Original PR with code review is here: https://github.com/mozilla/redash/pull/184/

### CODE REVIEW

**Comment by kocsmy** [comment]
Hey @alison985 thanks for the PR, I like this idea. Can you please provide a screenshot about the new button placement + modal?

**Comment by kocsmy** [comment]
Thanks for the screenshot, @alison985 — I'll propose something better for this feature in a few days.

**Comment by kocsmy** [comment]
hey @alison985 — I'd recommend using this area for the button, we have most of the visualisation  related things here already: 
screenshot 2018-07-08 18 00 38

**Comment by alison985** [comment]
@kocsmy I like it a lot and have changed my code to do that instead. I do want to point out, on the off chance you didn't notice it, that on a 13" MacBook Air it takes up a good chunk of the last whitespace on the bottom of the page which points towards a future space issue.
screenshot 2018-07-08 11 28 12

**Comment by arikfr** [comment]
Good point about screen size, @alison985 .

How about we add icons to these buttons and in small resolutions only use the  icons?

**Comment by alison985** [comment]
Works for me, in Font Awesome icons I propose:
* Edit Visualization: edit
* Add to Dashboard: plus-cicle
* Embed: code
* Download Dataset: file-download

**Comment by jezdez** [comment]
@arikfr @kocsmy Codeclimate gives feedback for this pull request (and others) that implies something is wrong. Could you clarify if

a) we can safely ignore the failures here and elsewhere and

b) if it'd be an option to disable some of the more complex rules it's applying like number of arguments?

**Comment by emtwo** [comment]
In light of https://github.com/mozilla/redash/issues/482, I just wanted to bring up the issue of whether *unpublished* queries can be added to dashboards from the query page.

Not sure if it's been addressed yet here but it's worth being aware of.

**Comment by jezdez** [comment]
FYI I've opened https://github.com/getredash/redash/issues/2727 to track the issue of the too strict Code Climate Analysis configuration.

**Pull request closed without merging**
