### PR TITLE
Remove pace-progress

### PR DESCRIPTION
**Pull request by gabrieldutra**
## What type of PR is this? (check all applicable)

- [x] Other

## Description

There were a few issues happening after recent changes with an error coming internally from Pace (rare cases, but now since we have a better Error handling, it turned to be a problem on those few cases). I removed it for now, lmk if you prefer one of those other options:

1. Find an alternative to Pace
2. Find a way to properly handle Pace exceptions

## Related Tickets & Documents
--

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
--

### CODE REVIEW

**Comment by gabrieldutra** [comment]
@arikfr @kravets-levko lmk how important Pace is to you 😅.

**Comment by kravets-levko** [comment]
> lmk how important Pace is to you :sweat_smile:

Not important at all :smile: Do we already we have alternative loading indicators on every page?

**Comment by gabrieldutra** [comment]
> Not important at all 😄 Do we already have alternative loading indicators on every page?

It seemed so, to be honest I don't miss it when I navigate through pages.

**Comment by kravets-levko** [comment]
> to be honest I don't miss it when I navigate through pages.

Sometimes on prod loading query/dashboard/some list may be quite slow, so that's important that user doesn't see a blank page. I checked codebase and looks that we already have loading indication on every page, so I guess it's safe to drop Pace

**Pull request merged**
