### PR TITLE
Fixed last test

### PR DESCRIPTION
**Pull request by ranbena**
- [x] Bug Fix

## Description
Added height test to 2nd widget in test.

### CODE REVIEW

**Comment by gabrieldutra** [comment]
I actually already had a similar solution in 4c7073626bdf6d9f6438891c58d9a5b8b0aee00e, but it falls in the same issue: as `addWidget` uses the api it does not provide the correct `{ col, row }` and the result is a vertical alignment:

image

Options:
- Leave as is
- Manually provide the `{ col, row }`
- Let this one be created in UI and use `cy.route` to get the element and make the height assertion

**Comment by ranbena** [comment]
> and the result is a vertical alignment:

Does the alignment have any significance to this test?

**Comment by gabrieldutra** [comment]
> Does the alignment have any significance to this test?

Nah, I also think that's acceptable. I'll merge and wrap this up with and extra fix to the possible flakiness with the `DynamicTable`.

**Comment by ranbena** [comment]
No need to merge this. https://github.com/getredash/redash/commit/4c7073626bdf6d9f6438891c58d9a5b8b0aee00e is great.

**Comment by gabrieldutra** [comment]
The missing position object actually makes another flakiness by making widgets [swap](https://percy.io/Redash/redash/builds/2244669/view/145955649/1280?mode=diff&browser=chrome&snapshot=145955649) :sweat_smile:.

**Comment by ranbena** [comment]
> The missing position object actually makes another flakiness by making widgets [swap](https://percy.io/Redash/redash/builds/2244669/view/145955649/1280?mode=diff&browser=chrome&snapshot=145955649) 😅.

Unexpected. @gabrieldutra you on this? Or do you want me to take it?

**Comment by gabrieldutra** [comment]
> Unexpected. @gabrieldutra you on this? Or do you want me to take it?

I'll handle that, I think I'll  manually provide the `{ col, row }` as it's the easiest option.

**Comment by ranbena** [comment]
@arikfr did we eventually change the add widget api call to include position?

**Pull request closed without merging**
