### PR TITLE
Show vertical scrollbar for IE

### PR DESCRIPTION
**Pull request by deecay**
Vertical scrollbar for HTML shown in Chrome and Firefox, but not IE.

### CODE REVIEW

**Comment by arikfr** [comment]
Can you add screenshots of before/after please?

**Comment by deecay** [comment]
Current:
now


Scrollbar is missing from from every page.


Fixed:
patched1


* If `-ms-overflow-style` set to 'scroll', the bar appears anytime mouse is in the window. Disappears when mouse is out. 
* If set to 'auto', the bar appears when mouse is in the window and near the vertical scrollbar. Disappears when mouse moves away from the bar.

This PR adopts 'scroll'. But any value but 'none' is fine for me.

**Comment by arikfr** [comment]
The behavior I see in Chrome on OSX is that the scrollbar appears when you start scrolling. Is this the same behavior with "auto"?

**Comment by deecay** [comment]
With 'auto':
 1. Moving mouse around will show wide scrollbar. Staying still for a while will auto hide the wide scrollbar.
 2. Pressing down key and scrolling down while wide scrollbar is shown, wide scrollbar is shown.
 3. Pressing down key and scrolling down while wide scrollbar is NOT shown, narrow scrollbar is shown.

out

**Comment by arikfr** [comment]
Let's use `auto` then. Thanks!

**Comment by deecay** [comment]
Done.

**Comment by arikfr** [comment]
Cool, thanks!

**Pull request merged**
