### PR TITLE
Add linux/arm64 to docker image platforms

### PR DESCRIPTION
**Pull request by winebarrel**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [x] Other

## Description

Add linux/arm64 to Docker image architecture.

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [x] Manually
- [ ] N/A

## Related Tickets & Documents

N/A

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

N/A

### CODE REVIEW

**Comment by justinclift** [comment]
Ahhhh.  The concept sounds ok, but I'm not sure it'll work just yet due to the `pgautoupgrade` repository not having a proper arm64 docker image yet.

Well, there's an early stage development docker image for arm64, but that's all at present.

**Review by guidopetri — APPROVED** [review]
I don't think we have to worry so much, this is just adding a new platform to dockerhub

**Comment by justinclift** [comment]
Cool, no worries. :smile:

**Comment by winebarrel** [comment]
Thank you!

**Pull request merged**
