### PR TITLE
[MySQL] Query cancelling correctly

### PR DESCRIPTION
**Pull request by dozen**
related: #2302

1. change Mysql-python to PyMySQL
  libmysql is can't handling SIGINT. So, use pure python implementation.
2. kill MySQL thread by another connection when catch SIGINT.

`_cancel` may be ad hoc, but for the time being we can cancel the query of mysql correctly.

### CODE REVIEW

**Comment by arikfr** [comment]
Thank you for the input @Jakdaw , I reviewed the original issue and @dozen's alternative implementation that uses threads. And honestly still not too excited to add threads to the mix.

> Please don't merge this - shifting to PyMySQL breaks support for MariaDB's 10.3 feature "Compound Statements Outside of Stored Programs"; see:

Considering that Redash is a tool to query and visualize data, and less for managing the schema -- is there a reasonable use case for compound statements?

> Additionally it breaks putting multiple queries into a single redash query; like:-
set @param = if("{{redashparam}}"="","default","{{redashparam}}"); select * from table where p = @param;

Why does it break them? Maybe we need to use a different API?

**Comment by Jakdaw** [comment]
> Thank you for the input @Jakdaw , I reviewed the original issue and @dozen's alternative implementation that uses threads. And honestly still not too excited to add threads to the mix.

Why the fear of threads? This is starting one thread in the celery worker for the duration of the query and ensures that it's all cleaned up before the celery worker returns to the pool.

I'm sure that there are threads being created in some of the libraries used for other data sources (certainly Cassandra comes to mind, probably others) that Redash uses - why is this any different?

> > Please don't merge this - shifting to PyMySQL breaks support for MariaDB's 10.3 feature "Compound Statements Outside of Stored Programs"; see:
> 
> Considering that Redash is a tool to query and visualize data, and less for managing the schema -- is there a reasonable use case for compound statements?

Compound statements are not for managing the schema. They simply allow you to do some of the things that you might otherwise need to do in a stored procedure in a query - so you can, for instance, open a cursor (based on redash query parameters) and iterate over the entries to collate information from further queries (based on redash query parameters) into a temporary table to display in the Redash UI. All without having to first define any stored procedures in the DB engine.

> > Additionally it breaks putting multiple queries into a single redash query; like:-
> > set @param = if("{{redashparam}}"="","default","{{redashparam}}"); select * from table where p = @param;
> 
> Why does it break them? Maybe we need to use a different API?

I'm not sure - I've not dug into the details of what it's sending to the DB and how that differs from the C-library - I'll take a look. I believe it complained that everything after the first semicolon was unexpected. There may be a way to support it with pymysql; I've not checked, just observed that there are lots of queries that work with MySQLdb that don't work under this pull request. I'll have a dig and see whether I can find some more details.

**Comment by arikfr** [comment]
> Why the fear of threads? This is starting one thread in the celery worker for the duration of the query and ensures that it's all cleaned up before the celery worker returns to the pool.

It's possible I'm a bit driven by FUD, more than trying to keep things simple 😳 

> I'm sure that there are threads being created in some of the libraries used for other data sources (certainly Cassandra comes to mind, probably others) that Redash uses - why is this any different?

True about Cassandra and I indeed saw cases where the thread it starts keep running even after the query was done.

Anyway if you happen to find a simple way to make the pure Python implementation to work -> great. If not, then let's give the thread implementation a try.

**Comment by hoangphuoc25** [comment]
Can we get this merged in? We are facing the same problem with redash. Having a temporary solution is better is still better than nothing @arikfr

**Comment by Jakdaw** [comment]
I agree that something should really be done about the ability to cancel queries but don't think that this PR is the answer as it breaks almost every query I have (which either have compound statements, multiple statements, or call stored procedures). @arikfr I'll rebase PR # 3003 against master and add the cancelling (yes, with a thread) functionality to that.

That way the MySQL query runner can cancel queries and properly support compound statements, multiple statements and stored procedures. This is what I've been running on my self-hosted instance for 6 months or so now.

**Comment by arikfr** [comment]
@Jakdaw's pull request (#3003) was merged, so I'm closing this one. Thank you, @dozen for the effort.

**Pull request closed without merging**
