### PR TITLE
Fix: Unable to open large Dashboard in Safari browser

### PR DESCRIPTION
**Pull request by iwakiriK**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
Due to a SecurityError, we are unable to open large dashboards in Safari browser.
image

For more information, please see this issue.
https://github.com/getredash/redash/issues/5333

The reason for this is that the value of `parametersChanged` is wrong.
The comparison method is not deep equal, so it almost assigns true.
https://github.com/getredash/redash/blob/v10.0.0-beta/client/app/components/Parameters.jsx#L57

This causes `updateUrl` runs frequently.
As a result, `history.replaceState` runs frequently.
https://github.com/getredash/redash/blob/v10.0.0-beta/client/app/components/Parameters.jsx#L62-L64

### How to Reproduce
- Create a parameter query
- Create a Dashboard
- Put about 40 of the queries in the Dashboard and save them.
- Open the Dashboard in Safari and wait for 10 seconds.

## Related Tickets & Documents
https://github.com/getredash/redash/issues/5333

### CODE REVIEW

**Comment by jimsparkman** [comment]
Tested this in my environment, fixes the Safari bug for me!

**Review by susodapop — APPROVED** [review]
LGTM. I rebased onto master so we can re-run the circleci build and then merge 😄

**Comment by susodapop** [comment]
After some manual testing there appears to be an issue with this implementation. Please review and add a Cypress test for it as well:

Steps to reproduce the issue:
1. Create a query that returns a single column (this will be used as a backing query for a dropdown)
2. Create a second query with a multi-parameter that uses the results from step 1.
3. Execute the query from step 2 with some options selected.
4. Change the settings for this multi-dropdown parameter (for example, change from wrapping with single quotes to no wrap)
5. Change the selected options and execute the query again. The result does not update properly until you reload the page.

CleanShot 2021-12-22 at 12 49 31

**Review by susodapop — CHANGES_REQUESTED** [review]
After some manual testing there appears to be an issue with this implementation. Please review and add a Cypress test for it as well:

Steps to reproduce the issue:
1. Create a query that returns a single column (this will be used as a backing query for a dropdown)
2. Create a second query with a multi-parameter that uses the results from step 1.
3. Execute the query from step 2 with some options selected.
4. Change the settings for this multi-dropdown parameter (for example, change from wrapping with single quotes to no wrap)
5. Change the selected options and execute the query again. The result does not update properly until you reload the page.

CleanShot 2021-12-22 at 12 49 31

**Comment by InvalidPointer** [comment]
Encountered this bug. @iwakiriK @susodapop any news regarding fix?

**Comment by guidopetri** [comment]
@iwakiriK , thanks for the PR! Same here, we've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI, as well as updating merge conflicts? We should also address the feedback already given.

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Comment by justinclift** [comment]
Rebased this onto `master` branch.  Sounds like this PR is only a partial fix though, as per @susodapop's comment + screen recording above.

**Pull request closed without merging**
