### PR TITLE
Fix query page header

### PR DESCRIPTION
**Pull request by kravets-levko**
Issue getredash/redash#3017

#### Short title and no tags:
image
image
image

#### Short title and a lot of tags:
image
image
image

#### Long title and no tags:
image
image
image

#### Long title and a lot of tags:
image
image
image

### CODE REVIEW

**Comment by kravets-levko** [comment]
@arikfr I didn't touch `EditInPlace` component, but will check it.

**Comment by kravets-levko** [comment]
@arikfr Seems it's a bug in `EditInPlace` component itself. I'll create another PR for it.

**Comment by kocsmy** [comment]
This is what I spot:
- There's an unnecessary 10 px margin-bottom here. This is also on mobile.
image

@arikfr did you find anything else?

**Comment by arikfr** [comment]
@kocsmy 

What I noticed is:

* Tags seem to be a bit too high compared to the title itself?
* The title used to be aligned with the "Dashboards" menu item and now it's aligned with the schema browser. This is not how it was before and not how it works on other pages (like Dashboards).

**Comment by kocsmy** [comment]
Thanks, @arikfr indeed those are also issues.

Another one is the size of the tag container pushes the height of the header and makes it 2-3px higher:
size

**Comment by kravets-levko** [comment]
@arikfr @kocsmy I fixed all things you mentioned - now it looks much better. Can you review again, please?

**Comment by kocsmy** [comment]
There's still an unnecessary margin bottom on smaller screens:
image

I couldn't fine anything else, this is a minor issue though.

**Comment by kravets-levko** [comment]
@kocsmy Ooops, missed that. Fixed now

**Comment by arikfr** [comment]
Only thing I noticed is that the right side of the header is unaligned:

This branch:

image

Current master:

image

**Comment by kravets-levko** [comment]
@arikfr I set the same paddings as on the Dashboard page. But will check tomorrow, though

**Comment by arikfr** [comment]
👌

**Comment by jezdez** [comment]
For the record, the PR fixing the issue in the Edit-in-place was fixed in #3049.

**Pull request merged**
