### PR TITLE
Fix chart labels

### PR DESCRIPTION
**Pull request by denisov-vlad**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description
Fixed labels for charts. Before that, all labels have values = 0.

The error was that `Object` in JS has keys as strings, so `Object.keys(labelsValuesDict);` returned wrong array.

I don't have any experience with JS, so please review it carefully.

## How is this tested?

- [x] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [x] Manually
- [ ] N/A

## Related Tickets & Documents
#6996

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
image

### CODE REVIEW

**Review by eradman — CHANGES_REQUESTED** [review]
This change has 17 commits, it should only be 1. (Error trying to rebase?)

**Comment by eradman** [comment]
@lvitti if you have time please test this change as well. We want to keep the functionality you implemented in https://github.com/getredash/redash/pull/6908 if possible.

**Comment by lvitti** [comment]
Hi @denisov-vlad, @eradman sorry for that bug, yes look like this fix is working also for Pie aggregation 
I'm not an expert in javascript either, here is another implementation of the fix using Map() 
https://github.com/getredash/redash/compare/master...lvitti:redash:lvitti/fix_6996_chart_doesnt_show_values?expand=1

**Comment by denisov-vlad** [comment]
@eradman Are there any blockers to merge it?

**Comment by lvitti** [comment]
> Yes, this is a very "hot" code path and testing for adverse side-effects has proven to require more care and the addition of unit tests.
> 
> I proposed that we revert the change that caused this issue in #7018

And what is the plan to solve the other bug? Because it's as bad as this.

Why not just add a test to this case and consider the 2 fixes ?

**Comment by eradman** [comment]
> And what is the plan to solve the other bug? Because it's as bad as this.
> 
> Why not just add a test to this case and consider the 2 fixes ?

The bug with the pie charts should be fixed as well, but this is a regression.

**Comment by ezraodio1** [comment]
I've been playing around with this feature and have noticed a few things.

1. If you recreate this bar chart with the issue and click Edit Visualization -> X Axis -> Scale -> Category, the labels are correct.
2. This issue with the labels is not limited to bar charts - I recreated it with the pie chart. As @denisov-vlad mentioned, the error is because the dictionary forces keys to be strings. Therefore, if your choice for X Axis isn't a column of strings, then the labels will be incorrect.
3. Using @lvitti's implementation with Map() doesn't seem to break anything, which logically makes sense since it isn't forcing a data type on its keys. All of the charts I made with the Map() implementation were correct, and I also **didn't** need to manually set the X Axis scale to "Category."


https://github.com/getredash/redash/assets/97199317/383e637e-b39c-48e9-b8da-09024d59523e

**Comment by eradman** [comment]
We merged an alternate fix in https://github.com/getredash/redash/pull/7022

**Pull request closed without merging**
