### PR TITLE
Update TagsList and Sidebar to use Ant components

### PR DESCRIPTION
**Pull request by gabrieldutra**
## What type of PR is this? (check all applicable)

- [x] Refactor

## Description
Following [this](https://github.com/getredash/redash/pull/4323#discussion_r341839683) discussion, this is an adaptation using Ant components for the Sidebar menu and the TagsList.

Initially this is to discuss the result and possible modifications from the Ant Components.

## Related Tickets & Documents
--

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
**Queries List**
ant-tags-and-sidebar

**Users List**
users-page

### CODE REVIEW

**Comment by kravets-levko** [comment]
Awesome @gabrieldutra! :tada: 

Is it possible to move that blue stripe (selected item indication) to left - as it was with Bootstrap styles?
image

**Comment by arikfr** [comment]
@kravets-levko I agree that with the current position of the sidebar the indication should be on the left side, but what if we moved the sidebar to the left side? :open_mouth:

**Comment by kravets-levko** [comment]
I like current placement of sidebar, but, I think, @gabrieldutra may try both variants and then decide what looks better :+1:

**Comment by gabrieldutra** [comment]
**Inverted Stripe**
inverted-stripe

**Inverted Menu**
inverted-menu

In general perspective, left-to-write readers will face the sidebar first when it's on the left side.

I liked the feeling when it was on the left side, but lmk what you prefer :)

**Comment by kravets-levko** [comment]
I like sidebar on right side more, but left side looks good as well :+1:

**Comment by arikfr** [comment]
I think the thinking behind putting the sidebar on the right side was:

* It makes sense to show the main content (the list) first. 
* The sidebar isn't a menu but more like filters for the data shown (which is more common to have on the right).

Considering that both options look good, let's go with having it as is today and put the stripe in the right place (https://github.com/getredash/redash/pull/4338/commits/c21ecdfdb6e457f258c7ec8d5d35650ffb4d596d).

**Comment by gabrieldutra** [comment]
Done!

**Pull request merged**
