### PR TITLE
Added support for "ObjectId" for querying fields that are of type ObjectId

### PR DESCRIPTION
**Pull request by erans**
For example:
{
	"collection" : "mycol",
	"query" : {
		"_id" : "ObjectId(\"xxxxxxxx\")"
	}
}

### CODE REVIEW

**Comment by arikfr** [comment]
I believe we already support this with the support for Mongo Extended JSON.
You should be able to write this query as:

```json
"_id": {"$oid": "..."}
```

https://docs.mongodb.com/manual/reference/mongodb-extended-json/#oid

**Comment by erans** [comment]
This is true when using Strict Mode - but not it's not always the case:
http://stackoverflow.com/questions/26938598/mongodb-oid-vs-objectid

This supports both modes.

**Comment by arikfr** [comment]
It's not something that depends on your MongoDB server -- it's in the [implementation of PyMongo](https://github.com/mongodb/mongo-python-driver/blob/master/bson/json_util.py#L140-L141).

**Comment by erans** [comment]
Heh... maybe its time I upgrade my PyMongo version :-|

OK. Scrape that.

**Pull request closed without merging**
