### PR TITLE
Design improvements

### PR DESCRIPTION
**Pull request by kocsmy**
I'm adding a couple of improvements, please don't merge yet, this needs more testing.

- [x] Increase query editor height from max 460px
- [x] Fix query header on smaller [screens](https://www.dropbox.com/s/hx4ejkv3gh3n6iy/Screenshot%202018-05-04%2022.28.32.png?dl=0) 
- [x] Improved error message and warning design
- [x] Add illustrations for empty states
- [ ] Hide Recent Dashboards and Recent queries if it's empty @arikfr 
- [ ] Add background to login pages

### CODE REVIEW

**Comment by kocsmy** [comment]
Just showing how this will look:

dashboard
lert
query

**Comment by arikfr** [comment]
Can I merge this now?

**Comment by kocsmy** [comment]
@arikfr yes, please!

**Comment by arikfr** [comment]
🕺

**Pull request merged**
