### PR TITLE
try fix cypress in the correct way

### PR DESCRIPTION
**Pull request by gaecoli**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

### CODE REVIEW

**Comment by justinclift** [comment]
Oh, that's an interesting idea.  So the `.should("be.enabled")` will first test if the button is enabled.  And only then will it try to click it.

I wonder if there will need to be some kind of timeout override on the `.should()` call too?

Well, I guess can do the same thing as with the previous PR (#6112), and run it several times to make sure it's working reliably now. :smile:

@gabrieldutra What are your thoughts on this one?

**Comment by gaecoli** [comment]
> Oh, that's an interesting idea. So the `.should("be.enabled")` will first test if the button is enabled. And only then will it try to click it.
> 
> I wonder if there will need to be some kind of timeout override on the `.should()` call too?
> 
> Well, I guess can do the same thing as with the previous PR (#6112), and run it several times to make sure it's working reliably now. 😄
> 
> @gabrieldutra What are your thoughts on this one?

We can fix it together.

**Comment by gaecoli** [comment]
image

**Comment by gaecoli** [comment]
> image

I will try another time.

**Comment by gaecoli** [comment]
image

I don't know what is this.

**Comment by gaecoli** [comment]
Two times tests are all ok!

**Comment by justinclift** [comment]
Yeah, that `build` task seems to be breaking things.  I *think* it might be part of some left over CircleCI configuration.

I'll create a PR in the next few hours to try and fix that.  eg by trying out some different settings to get rid of it :smile:

**Comment by gaecoli** [comment]
> **build ** Expected — Waiting for status to be reported

https://stackoverflow.com/questions/52200096/github-pull-request-waiting-for-status-to-be-reported

I look at this doc.

**Comment by gaecoli** [comment]
> > **build ** Expected — Waiting for status to be reported
> 
> https://stackoverflow.com/questions/52200096/github-pull-request-waiting-for-status-to-be-reported
> 
> I look at this doc.

https://github.com/orgs/community/discussions/25720

**Comment by gaecoli** [comment]
This PR we can wait for @gabrieldutra's response. And then decide to merge or continue to fix it.

**Comment by justinclift** [comment]
Arik fixed the `build` item problem.  So tests should now generally be working ok... :smile:

**Comment by gaecoli** [comment]
> Arik fixed the `build` item problem. So tests should now generally be working ok... 😄

Cool!

**Review by gabrieldutra — APPROVED** [review]

**Comment by gaecoli** [comment]
> > Oh, that's an interesting idea. So the `.should("be.enabled")` will first test if the button is enabled. And only then will it try to click it.
> 
> Usually cypress does that behind the hoods (like [this](https://glebbahmutov.com/cypress-examples/recipes/disabled-button.html)). I don't remember exactly why the button was an exception 🤔.
> 
> No need to replace any timeout

We will keep last PR about this problem?

**Comment by gaecoli** [comment]
@gabrieldutra As you said, i change `should("be.enabled")` to `should("be.not.disabled")`, and i keep `timeout` in `click()`.

**Comment by gabrieldutra** [comment]
Sorry @gaecoli, I meant we don't need any timeout override. You can remove in this PR, and leave only the .should you added.

By the way, not.be.disabled and be.enabled should be equivalent

**Review by gabrieldutra — APPROVED** [review]

**Comment by gaecoli** [comment]
So now i can merge it in master? @gabrieldutra

**Comment by gabrieldutra** [comment]
> So now i can merge it in master? @gabrieldutra

Go ahead :)

**Pull request merged**
