### PR TITLE
Configurable mysql datasource

### PR DESCRIPTION
**Pull request by zhongjiajie**
Make mysql datasource connection params
as configurable

## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Bug Fix

## Description

Make mysql datasource connection params configurable

## Related Tickets & Documents

None

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

None

### CODE REVIEW

**Comment by zhongjiajie** [comment]
@gabrieldutra @rauchy @rafawendel PTAL thanks

**Comment by zhongjiajie** [comment]
FYI, CI failed. Did we have some magic command to restart CI?
```log
ERROR: Failed to download Chromium r722234! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:207:27)
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/src/app/node_modules/puppeteer/install.js:66:16)
    at Module._compile (internal/modules/cjs/loader.js:1256:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1277:10)
    at Module.load (internal/modules/cjs/loader.js:1105:32)
    at Function.Module._load (internal/modules/cjs/loader.js:967:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@2.1.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@2.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-21T02_43_14_243Z-debug.log
ERROR: Service 'cypress' failed to build : The command '/bin/sh -c npm ci > /dev/null' returned a non-zero code: 1
child_process.js:674
    throw err;
    ^

Error: Command failed: docker-compose -p cypress build
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at buildServer (/home/circleci/project/client/cypress/cypress.js:47:3)
    at Object.<anonymous> (/home/circleci/project/client/cypress/cypress.js:91:5)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 354,
  stdout: null,
  stderr: null
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! redash-client@9.0.0-beta cypress: `node client/cypress/cypress.js "build"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redash-client@9.0.0-beta cypress script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2020-11-21T02_43_17_248Z-debug.log
```

**Comment by zhongjiajie** [comment]
I user git force push to restart failing CI

**Comment by zhongjiajie** [comment]
CI green, PTAL, @arikfr @gabrieldutra @rauchy @rafawendel @kravets-levko

**Review by susodapop — APPROVED** [review]
LGTM. Tested manually against mariadb.

**Comment by susodapop** [comment]
Thanks for pinging on this. Sorry to only now get to it! Thank you very much for this contribution.

**Pull request merged**
