### PR TITLE
Bump gunicorn from 20.0.4 to 21.2.0

### PR DESCRIPTION
**Pull request by bluetech**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [x] Other

## Description

The version 20.0.4 has a security issue:
https://grenfeldt.dev/2021/04/01/gunicorn-20.0.4-request-smuggling/

Changelog:
https://docs.gunicorn.org/en/stable/news.html

Also, the old versions expose the gunicorn version in the `Server` header which is considered bad practice these days because it needlessly exposes info to attackers. Newer versions don't do that anymore.

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [x] Manually
- [ ] N/A

I tested using the docker-compose (changing `dev_server` to `server`) and seeing that basic functionality works.

### CODE REVIEW

**Comment by justinclift** [comment]
Interesting.  It looks like Gunicorn 20.0.4 is fairly old now too, with newer releases available:

&nbsp; &nbsp; https://pypi.org/project/gunicorn/#history

We should probably try with those, and see if things all still work properly. :smile:

**Comment by bluetech** [comment]
@justinclift Right, 20.0.4 is the problematic version this PR updates from. The version the PR updates to 21.2.0 is currently the latest.

**Comment by justinclift** [comment]
@bluetech Oops.  Thanks, yeah somehow I'd misread or misunderstood the version numbers last night. :facepalm:  Definitely needed sleep. :smile:

**Review by justinclift — APPROVED** [review]
Seems like a straight forward version bump. :smile:

**Comment by justinclift** [comment]
Thanks heaps @bluetech. :smile:

**Pull request merged**
