### PR TITLE
Store start datetime in redash:status hash again.

### PR DESCRIPTION
**Pull request by jezdez**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] New Query Runner (Data Source)
- [ ] New Alert Destination
- [ ] Other

## Description

As described in the ticket, this was a regression of the Celery/RQ transition.

## Related Tickets & Documents

#4893

### CODE REVIEW

**Comment by guidopetri** [comment]
@jezdez , thanks for the PR! We've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI?

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Comment by justinclift** [comment]
If this passes the CI tests we should merge it. :smile:

**Comment by justinclift** [comment]
Thanks for fixing this @jezdez. :smile:

**Comment by jezdez** [comment]
Sure thing! I'm not working with Redash anymore (job change) but I'm glad this got fixed properly now.

**Comment by justinclift** [comment]
Cool.  As you're not working with Redash any more, should we close #3673?

**Pull request merged**
