### PR TITLE
Query schedule may not always contain an "until" key

### PR DESCRIPTION
**Pull request by robinedwards**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description

Noticed this error occurring from redash in our Sentry:

image

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [x] Manually
- [ ] N/A

Sentry error stopped occurring

### CODE REVIEW

**Comment by eradman** [comment]
I can't figure out how `schedule->until` can end up missing, unless the `queries` table was modified manually. Are there any other keys missing? Try running this:

```sql
SELECT id,array_agg(keys) AS key
FROM queries, jsonb_object_keys(schedule::jsonb) keys
GROUP BY id ORDER BY id;
```

**Comment by robinedwards** [comment]
I've not modified it manually, there was a new migration added:

https://github.com/getredash/redash/blob/master/migrations/versions/640888ce445d_.py

Which touches the column.

Running your query:

```

redash=> SELECT id,array_agg(keys) AS key
FROM queries, jsonb_object_keys(schedule::jsonb) keys
GROUP BY id ORDER BY id;
ERROR:  cannot call jsonb_object_keys on a scalar```

Looking a bit closer I have several rows where the schedule is null:
```
redash=> select count(*) from queries where schedule is null;
 count 
-------
   255
(1 row)```

Then picking out a few examples where until is null:

```
redash=> select schedule from queries where schedule is not null limit 10;
                                   schedule                                    
-------------------------------------------------------------------------------
 {"time": "08:00", "until": null, "interval": 604800, "day_of_week": "Monday"}
 {"time": "23:15", "until": null, "interval": 86400, "day_of_week": null}
 {"time": "08:00", "until": null, "interval": 604800, "day_of_week": "Monday"}
 {"time": "00:15", "until": null, "interval": 86400, "day_of_week": null}
 null
 {"time": "09:00", "until": null, "interval": 604800, "day_of_week": "Monday"}
 {"time": "01:15", "until": null, "interval": 604800, "day_of_week": "Sunday"}
 {"time": null, "until": null, "interval": 3600, "day_of_week": null}
 {"time": null, "until": null, "interval": 3600, "day_of_week": null}
 {"disabled": true}
(10 rows)```

**Comment by robinedwards** [comment]
@justinclift would it be possible to get a review

**Comment by justinclift** [comment]
@guidopetri Do you have time to look at this?  It seems super simple. :smile:

**Comment by justinclift** [comment]
> Approving since we're not making progress.

Thanks.  Just merged it. :smile:

**Pull request merged**
