### PR TITLE
Add: support for specifying SAML nameid-format

### PR DESCRIPTION
**Pull request by zoetrope**
By default Saml2Client use 'NAMEID_FORMAT_TRANSIENT' for NameIDPolicy in AuthnRequest.
I want to use other format.
So I add configuration 'REDASH_SAML_NAMEID_FORMAT'.

### CODE REVIEW

**Comment by arikfr** [comment]
Now that I merged your other pull requests, you need to rebase this.

**Comment by zoetrope** [comment]
I rebased it.

**Comment by arikfr** [comment]
Thanks.

**Comment by arikfr** [comment]
This is not related to the Pull Request directly, but I assume that the author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.

**Pull request merged**
