### PR TITLE
Add a make target to generate .env file for development

### PR DESCRIPTION
**Pull request by justinclift**
## What type of PR is this? 

- [x] Feature

## Description

This PR adds a new `make env` command, which generates a development oriented `.env` file.

```
$ make env
```

It's just a small quality-of-life improvement for developers, and helps reduce confusion as to what values are needed.

At present it only generates the `REDASH_COOKIE_SECRET` and `REDASH_SECRET_KEY` environment variables, but we can easily add more as needed.

## How is this tested?

- [x] Manually

Tested (using bash) by running `make env` then confirming it worked using `cat .env`.

```
$ make env
printf "REDASH_COOKIE_SECRET=`pwgen -1s 32`\nREDASH_SECRET_KEY=`pwgen -1s 32`\n" >> .env
$ cat .env
REDASH_COOKIE_SECRET=9GWB4pw54flMmfTLEhJMcUYKW9nWgUmZ
REDASH_SECRET_KEY=KV86JIFs2V3lDjXIXU6KWShJy1auGCm4
```

## Related Tickets & Documents

We should update the [Local development setup wiki page](https://github.com/getredash/redash/wiki/Local-development-setup) with this command when merged. :smile:

### CODE REVIEW

**Comment by justinclift** [comment]
@getredash/maintainers @guidopetri @junnplus I reckon this will be useful. :smile:

**Review by junnplus — APPROVED** [review]
LGTM, It has also been helpful to me. 😊

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by guidopetri** [comment]
It is useful indeed! Thanks Justin :)

**Pull request merged**
