### PR TITLE
get data size in memory for better logs

### PR DESCRIPTION
**Pull request by zachliu**
## What type of PR is this? 

- [ ] Refactor
- [x] Feature
- [x] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [x] Manually
- [ ] N/A

This change only affects the logs. 

## Related Tickets & Documents

It solved https://github.com/getredash/redash/issues/7030

### CODE REVIEW

**Comment by zachliu** [comment]
the error `ModuleNotFoundError: No module named 'distutils.command.build'` has nothing to do with my changes :confused:

**Comment by justinclift** [comment]
Yeah, that error was a problem due to upstream setuptool pushing out a bad release (`72.0.0`):

https://github.com/getredash/redash/pull/7084

I thought it should be fixed now though, unless they've re-broken it.

**Review by justinclift — APPROVED** [review]
This makes good sense to me. :smile:

**Comment by justinclift** [comment]
@eradman This looks good to merge yeah?

**Review by eradman — APPROVED** [review]
Before

```
[INFO][rq.job.redash.tasks.queries.execution] job.func_name=redash.tasks.queries.execution.execute_query job.id=83bee200-e22e-4c16-b5d0-cb05444cb51b job=execute_query query_hash=f514c4e634b96dfc3dd73ecd3cd1cd55 ds_id=1 data_length=2 error=[None]
```

With this change

```
[INFO][rq.job.redash.tasks.queries.execution] job.func_name=redash.tasks.queries.execution.execute_query job.id=18bf6502-05e2-49b8-af05-9a33577c32fb job=execute_query query_hash=f514c4e634b96dfc3dd73ecd3cd1cd55 ds_id=1 data_length=280715 error=[None]
```

This matches up

```
$ wc -c Deepest_Dir_2024_08_01.csv
   22850 Deepest_Dir_2024_08_01.csv
```

**Review by eradman — CHANGES_REQUESTED** [review]
Actually, this doesn't line up

The JSON for my sample query is ~49kB, raw text is ~22kB, but the log message is ~257kB

**Comment by zachliu** [comment]
@eradman This is `in-memory` data size. Python requests extra space for storing objects for performance reasons. For example, a list of 5 ASCII characters is not stored in a 5 x 1 = 5 bytes memory space. Instead, Python requests 104 bytes for such a list.

On the other hand, estimate the "true" size of a Python dictionary is difficult. It requests a lot of operations such as converting the dictionary to CSV and use a `StringIO` object to capture the CSV output in memory. I'd argue this is too expensive to do for a log entry.

**Comment by zachliu** [comment]
I wanted to change `data_length` to `estimated_data_in_memory` but it may break people's log-based monitoring if they are using services like DataDog.

**Comment by eradman** [comment]
> I wanted to change `data_length` to `estimated_data_in_memory` but it may break people's log-based monitoring if they are using services like DataDog.

Got it!

```
>>> s = "The Quick Fox"
>>> import sys
>>> len(s)
13
>>> sys.getsizeof(s)
62
```

**Review by eradman — APPROVED** [review]

**Comment by justinclift** [comment]
Awesome. :smile:

**Pull request merged**
