### PR TITLE
Add an optional footer-extra component.

### PR DESCRIPTION
**Pull request by jezdez**
## What type of PR is this? (check all applicable)

- [x] Feature

## Description

This is similar to the `<home-extra/>` and `<datasource-list-extra/>` placeholders, which would allow adding additional infos and links to the footer via Redash extensions.

### CODE REVIEW

**Comment by arikfr** [comment]
Now that we have a help link in the navbar and version in the menu, the plan is to remove the footer...

**Comment by kravets-levko** [comment]
@arikfr +1. Aside of that, it should be implemented as [`DynamicComponent`](https://github.com/getredash/redash/blob/master/client/app/components/DynamicComponent.jsx)

**Comment by jezdez** [comment]
> Now that we have a help link in the navbar and version in the menu, the plan is to remove the footer...

Aha, that's fair, I'm simply wondering how to add link to our bugtracker and thought this would we an acceptable location. Do you know where it would fit better?

> @arikfr +1. Aside of that, it should be implemented as [`DynamicComponent`](https://github.com/getredash/redash/blob/master/client/app/components/DynamicComponent.jsx)

Nice, that totally flew past me! Looking at the code, I'd basically call `registerComponent` with an existing React component which is then rendered instead?

**Comment by kravets-levko** [comment]
@jezdez 

1. register: `registerComponent('SomeComponent', MyComponent)`
2. use: `<DynamicComponent name="SomeComponent" />`

**Comment by jezdez** [comment]
@arikfr To clarify, since the footer hasn't been remove in 7.0.0, should this be closed?

**Comment by arikfr** [comment]
> Do you know where it would fit better?

Maybe inside the help drawer? It already has a DynamicComponent point which we use to have a link to open chat support/show status page:

image

**Comment by ranbena** [comment]
@jezdez here's some sample code:

```jsx
// HelpDrawerExtraContent.jsx

import React from 'react';
import PropTypes from 'prop-types';
import { registerComponent } from '@/components/DynamicComponent';
import Button from 'antd/lib/button';

import './HelpDrawerExtraContent.less';

class HelpDrawerExtraContent extends React.Component {
  static propTypes = {
    onLeave: PropTypes.func.isRequired,
    openPageUrl: PropTypes.func.isRequired,
  }

  render() {
    const { openPageUrl, onLeave } = this.props;
    return (
      <div className="help-drawer-extra-content">
        <a href="#" onClick={() => openPageUrl("https://www.bugzilla.org")}>Bugzilla</a>
        <Button onClick={onLeave}>Close drawer</Button>
      </div>
    );
  }
}

export default function init() {
  registerComponent('HelpDrawerExtraContent', HelpDrawerExtraContent);
}

init.init = true;
```

```less
// HelpDrawerExtraContent.less

.help-drawer-extra-content {
  background-color: #F6F8F9;
  width: 100%;
  height: 50px;
  padding: 10px 10px 10px 20px;
  line-height: 30px;
  display: flex;
  border-top: 1px solid #e0e0e0;
 
  a {
    flex: 1
  }

  button {
    height: 30px;
  }
}
```

**Comment by jezdez** [comment]
@ranbena Super super exciting, thank you for sharing this snippet. Cheers!

@arikfr That works for us I think, thanks for the help!

**Pull request closed without merging**
