### PR TITLE
Ask user to log in when session expires

### PR DESCRIPTION
**Pull request by kravets-levko**
## What type of PR is this? (check all applicable)

- [x] Other

## Description

When session expires, app will detect it on next request to a backend, and will show a prompt (see screenshots). When clicking on the link, popup with login page will appear. After logging in, app will continue where it stopped.

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

image
image

### CODE REVIEW

**Review by rauchy — APPROVED** [review]
LGTM! (yay another use for `axios-auth-refresh`)

**Comment by kravets-levko** [comment]
@rauchy 

> (yay another use for axios-auth-refresh)

I requested your review mostly because I modified your code a bit and wanted to be sure that I didn't break anything (I didn't manage to test this part properly :confused:)

**Comment by rauchy** [comment]
@kravets-levko I tested it and it works as expected 👍

**Review by gabrieldutra — COMMENTED** [review]
Overall code looks good, I love how this can easily keep the existent workflow 🎉.

2 things I noticed:
1. It seems it always shows up the Modal, even if no session existed before 🤔
2. Not sure what you think about it, but I would go for a regular modal (the messages can ofc be changed):
Screen Shot 2020-09-22 at 18 59 34

I understand that the `<h3>` idea was to call the attention, but maybe the Primary action is enough? It's aligned with most similar modals I've seen.

LMK your opinion anyway 😁

**Comment by kravets-levko** [comment]
@gabrieldutra 

1. This happens only on preview instance, but thanks for pointing - I'll check this.
2. Yes, the regular modal looks good as well. Maybe I'll even try `Modal.warning()` :slightly_smiling_face:

**Comment by kravets-levko** [comment]
Replaced dialog with `Modal.warning` - IMHO looks much better :slightly_smiling_face: Thank you @gabrieldutra!

image

**Comment by kravets-levko** [comment]
> It seems it always shows up the Modal, even if no session existed before :thinking:

@gabrieldutra  fixed in https://github.com/getredash/redash/pull/5178/commits/bc25ee0ae826bf91288a1bbb0dc9bdef7b09ce63

**Review by gabrieldutra — APPROVED** [review]

**Pull request merged**
