### PR TITLE
Sort numeric values as numbers rather than strings (for a Category-type X Axis)

### PR DESCRIPTION
**Pull request by magni-**
## What type of PR is this? (check all applicable)
- [x] Feature
- [x] Bug Fix

Is this a feature or a bugfix? 🤷🏼 

## Description

The way things currently work, if a `Category`-type axis has numeric values with differing numbers of digits (e.g. `1 2 10`) and you sort it, you'll end up with values that don't seem properly (numerically-speaking) sorted (e.g. `1 10 2`). This PR changes that so that numeric strings are sorted as numbers.

If you were to have a mix of numeric and non-numeric strings, we currently return the numbers first. This behavior is preserved by using `Infinity` as the "parsed" value for non-numeric strings. Non-numeric strings are then properly sorted via the same `_.identity` method as currently.

~AFAICT, there are no frontend unit tests~, only integration tests via Cypress? And it doesn't look like category sorting is currently covered there. For now I've just tested this manually locally instead:
```javascript
arr = ['hello', '1', 'redash', '2', '10'];
=> [ 'hello', '1', 'redash', '2', '10' ]

// current behavior
sortBy(arr, identity);
=> [ '1', '10', '2', 'hello', 'redash' ]

// with these changes
sortBy(arr, [numericSorter, identity]);
=> [ '1', '2', '10', 'hello', 'redash' ]
```

I couldn't come up with a good name for `numericSorter`, would welcome any better sounding alternatives 🙇🏼 

edit: I somehow missed the frontend tests hiding in plain sight (I'm too used to them being in their own `spec`/`test`/`__tests__` folder apparently 🤦🏼) Will see what test coverage I can add.

edit2: I added a test and red-green'ed it.

## Related Tickets & Documents
None that I could find

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
N/A

### CODE REVIEW

**Comment by susodapop** [comment]
Will review later this week! Thanks for a well-formed PR 👍

**Comment by magni-** [comment]
@susodapop sorry for the ping, but can you take a look? Thanks! 🙇🏼

**Comment by susodapop** [comment]
Ping deserved! I got sidetracked on redash-migrate. Will review this in the morning on 15 October CST.

**Comment by susodapop** [comment]
I checked this out for some manual testing but it didn't behave like I expected. I started with data like this:

CleanShot 2021-10-18 at 21 38 58

I expected the sort to result in `1,2,3,4,5,6,7,8,9,10,11`. But instead sorting the x-axis began `1,10,11,2...`.

**Comment by magni-** [comment]
> I checked this out for some manual testing but it didn't behave like I expected.

@susodapop I'm having trouble running queries locally, do you have any pointers so I can reproduce and debug? I have Redash running locally following the instructions from `CONTRIBUTING.md`, but they don't cover adding query sources. I've tried using a [CSV data source](https://redash.io/help/data-sources/querying/csv-files#Step-3-Pull-the-data-into-Redash) since that seemed like it'd be the simplest to get up and running, but I'm not able to figure it out (see screenshot)

image

**Comment by guidopetri** [comment]
@magni- , thanks for the PR! We've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI?

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Comment by eradman** [comment]
This did not seem to work for me, even if the query returned integers instead of numbers formatted as text

numeric_sort_category

But I actually don't think this is a good idea:  if the category needs to be sorted numerically

1. return numbers from the query and pick "Sort Values"
2. order the results in the query itself

**Comment by justinclift** [comment]
@eradman Cool, thanks for looking at it. :smile:

@magni- What are your thoughts on this? :smile:

**Pull request closed without merging**
