### PR TITLE
upgrade to Celery 4.1.0

### PR DESCRIPTION
**Pull request by mashrikt**
This refers to #2517 

I have reviewed Mozilla's both upgrade to [Celery 3.1.25](https://github.com/getredash/redash/pull/2270) and [Celery 4.1.0](https://github.com/mozilla/redash/pull/297).

I feel like I should give you guys a heads up regarding [this](https://github.com/celery/celery/issues/4356).

### CODE REVIEW

**Comment by atharvai** [comment]
Hey thanks for working on this. I also worked on it in parallel as I didn't know you had started.

One thing maybe you can merge from my branch is the new env var config key: `REDASH_WORKER_MAX_MEMORY_PER_CHILD`
This is updated in two files: 
https://github.com/getredash/redash/pull/2535/files#diff-324d42e08af87005833f42ea274a9abeR37 
https://github.com/getredash/redash/pull/2535/files#diff-ad93995bb355251c02f87fc02db69351R53

my PR: https://github.com/getredash/redash/pull/2535

I couldn't find our fork to create a PR from mine

**Comment by mashrikt** [comment]
@atharvai I have created a PR from [your celery_upgrade branch to my celery4 branch.](https://github.com/mashrikt/redash/pull/1) 
Would it be possible for you to fix the conflicts?

**Comment by mashrikt** [comment]
@arikfr  Review possible?

**Comment by RichardLitt** [comment]
@mashrikt We haven't forgotten. We'll review this as soon as we have some time. :)

**Comment by mashrikt** [comment]
@RichardLitt  Good to hear from you again!
Hope you're well.

**Comment by alison985** [comment]
Please note there is a new issue with celery 4.1.0 because of an unpinned dependency in celery. see https://github.com/mozilla/redash/pull/405

**Comment by atharvai** [comment]
Is there any more progress on this? I imagine we'll want to upgrade to `celery==4.1.1` too because of issue Mozilla folks noticed.

**Comment by jezdez** [comment]
This was fixed in #2773. Thanks @mashrikt for your help!

**Pull request closed without merging**
