### PR TITLE
Add: use results row count as the value for the counter visualization.

### PR DESCRIPTION
**Pull request by deecay**
This PR is a response to #889

Now Counter visualization can show the row count of resultset.

When one sees a counter value in a dashboard, he often wants to obtain detailed information through table data. With this PR, we can now provide table data and its row counter with one query.

### CODE REVIEW

**Comment by arikfr** [comment]
Can you give a real world example where you might use this?

**Comment by arikfr** [comment]
Also, why not just run another query that returns the count?

**Comment by deecay** [comment]
Sure!

Two-query method has 2 downsides.

1. You have to find a way to guide people to the matching query with table result.
Lets say there is one dashboard that shows 3 counters. Number of unfulfilled backorders for today, this week, and last week. When one dashboard widget shows that there are "12 unfulfilled backorders last week", they often click on the query name, hoping to find out more details about those 12 backorders. When they click on "TABLE", they only see "12".
 I couldn't find a sensible way to construct a dashboard with many KPI figures, where people can easily drill down to each KPI's individual details. Issuer of #889 said that he may add a counter column to every row with row_cont(), but it's not the way to go; I agree. But with this PR, people can click on "TABLE" to see the details of the exact query the counter showed. 

2. Two queries means more maintenance and more computing resource. 
Two queries for the same data means twice the number of queries (of essentially the same data but only different in representation), twice the maintenance cost for queries (if you change the where clause of one query, you must update the corresponding query, and you *must not* forget to update it), twice the worker process for redash, and twice the session load for the data source (you would want to minimize this when the data source is not your own). All these extra costs can be avoided by just one checkbox.

Please let me know your thoughts.

**Comment by arikfr** [comment]
Both are great use cases actually!

**Pull request merged**
