### PR TITLE
fix: Uncaught rejection promise error in Edit Visualization Dialog Modal

### PR DESCRIPTION
**Pull request by arungovindm2001**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description
A fix to Uncaught Promise Error exception when clicking No in Edit Visualization Dialog modal

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [X] N/A

## Related Tickets & Documents
#6793

### CODE REVIEW

**Comment by justinclift** [comment]
Thanks @arungovindm2001.  It looks like the `restyled` check is failing, and wants the formatting to be [slightly different](https://restyled.io/gh/getredash/repos/redash/jobs/4152571/patch).

Are you ok to get that done? :smile:

**Comment by arungovindm2001** [comment]
> Thanks @arungovindm2001. It looks like the `restyled` check is failing, and wants the formatting to be [slightly different](https://restyled.io/gh/getredash/repos/redash/jobs/4152571/patch).
> 
> Are you ok to get that done? 😄

Sorry for being a little late :sweat_smile:. I have done the restyling. Thanks!

**Review by eradman — APPROVED** [review]
Looks reasonable

**Comment by justinclift** [comment]
Cool, merged.  Thanks for getting this done @arungovindm2001. :smile:

**Pull request merged**
