### PR TITLE
Fix: query scrolling issues

### LINKED ISSUE #1024: Cannot scroll on query editor
I cannot scroll on the query editor with a mouse. It seems that it works well with a touchpad... Re:dash 0.10.0+b1774

Demo URL: http://demo.redash.io/queries/1600/source
Video: http://sendvid.com/mo3jokk3

System details: OS X 10.11.3 / Chrome 50.0.2661.86 (reproduced normal and incognito mode)

### PR DESCRIPTION
**Pull request by vishesh92**
#1024

### CODE REVIEW

**Comment by AntoineAugusti** [comment]
Does not fix the issue for us :/

**Comment by vishesh92** [comment]
@AntoineAugusti  Which browser are you using?

**Comment by AntoineAugusti** [comment]
Latest Chrome on OS X

**Comment by vishesh92** [comment]
I am using the same browser. If your project is publicly accessible, please share the link.

**Comment by arikfr** [comment]
On Chrome/OSX it for sure fixed the scrolling issue. I don't know the mouse issue.

**Comment by arikfr** [comment]
(I'll keep #1024 until I can confirm the  mouse behavior)

**Comment by arikfr** [comment]
Thanks!

**Pull request merged**
