### PR TITLE
Add ability to search table column names in schema browser

### PR DESCRIPTION
**Pull request by alison985**
Re: #2484 and https://github.com/mozilla/redash/issues/380

This PR:
* Allows you to search for a table name, a column name, or both. A space should be used between table name and column name. If there is no space it is a table name search only, with a space anything after the space is for a column name.
* If more than one space is used it gets replaced with one space. This avoids having to give an error toastr message and the behavior that happens when there are multiple spaces.

### CODE REVIEW

**Comment by arikfr** [comment]
If I remember right, the `filter` filter can take an object, and apply the search based on the object structure. Using this will require changing the data structure of the schema locally to the browser, but that shouldn't be much of an issue. And potentially will make implementation of filtering simpler.

**Comment by jezdez** [comment]
@alison985 Remind me, is this closer to be solved? What can I do help you with this?

**Comment by jezdez** [comment]
@alison985 The pull request description above says otherwise, which is why I'm asking. Could you update the description please?

**Comment by alison985** [comment]
@jezdez Updated. Sorry about that.

**Pull request merged**
