### PR TITLE
add pg types map

### PR DESCRIPTION
**Pull request by gaecoli**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

### CODE REVIEW

**Comment by justinclift** [comment]
@gaecoli Is there some reference documentation for the `1043` value?

Where is that value coming from, and what happens when it is missing? :smile:

**Comment by gaecoli** [comment]
image
image

**Comment by justinclift** [comment]
This *might* be useful reference information:

https://github.com/psycopg/psycopg2/blob/329f43c76233ebb85f762f05f0b936f3ac5c223f/psycopg/typecast_builtins.c#L1-L31

Would it be useful to add some of the others?  Maybe the other numbers for the types we already have (NUMBER, FLOAT, etc)?

**Comment by gaecoli** [comment]
image


> This _might_ be useful reference information:
> 
> https://github.com/psycopg/psycopg2/blob/329f43c76233ebb85f762f05f0b936f3ac5c223f/psycopg/typecast_builtins.c#L1-L31
> 
> Would it be useful to add some of the others? Maybe the other numbers for the types we already have (NUMBER, FLOAT, etc)?

Yes, i can fix it.

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by gaecoli** [comment]
> Cool. 😄

I added `string`, `date` types. The Redash not show `binary`, so i don't add it.

**Comment by gaecoli** [comment]
Our ci has error.

**Comment by justinclift** [comment]
It seems to be a problem with the Yarn package repository infrastructure.  Hopefully it will be ok if we try again in a few minutes. :smile:

**Review by justinclift — APPROVED** [review]
Looks good to me. :smile:

**Comment by justinclift** [comment]
Thanks @gaecoli. :smile:

**Pull request merged**
