### PR TITLE
Error screens

### PR DESCRIPTION
**Pull request by kocsmy**
- [x] Change error message accordingly (see the code for a few examples)

In order to make our error messages more useful and digestible, we're adding a couple of improvements. 

screenshot 2018-01-31 22 57 21

### CODE REVIEW

**Comment by arikfr** [comment]
Shouldn't it be centered?

**Comment by kocsmy** [comment]
>Shouldn't it be centered?

Yep (I was a bit hesitant) and fixed it now.

**Comment by kocsmy** [comment]
@arikfr I improved the layout based on our discussion, see updated screenshot

**Comment by arikfr** [comment]
Yeah, looks better. Now I need to wire in the logic :-)

**Pull request merged**
