### PR TITLE
Add RisingWave support

### PR DESCRIPTION
**Pull request by stefannegele**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [x] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description

RisingWave (1.6.0) is a PostgreSQL compatible streaming database. This PR basically uses the PostgreSQL query runner but changes the listing of tables in two ways:
- not using incompatible postgres function (introduced after last redash release)
- removing risingwave internal schemas from table listing

## How is this tested?

- [ ] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [x] Manually
- [ ] N/A

### CODE REVIEW

**Comment by konnectr** [comment]
I believe that it is necessary to allocate RisingWave to a separate file

**Comment by gaecoli** [comment]
> I believe that it is necessary to allocate RisingWave to a separate file

You are right!

**Comment by stefannegele** [comment]
Hi, i moved the code to its own file. Sadly now the data source is not showing up in the UI anymore. What am I missing?

**Comment by konnectr** [comment]
You need to add settings https://github.com/getredash/redash/blob/master/redash/settings/__init__.py#L341 @stefannegele

**Comment by stefannegele** [comment]
@konnectr thanks for the hint! I just applied it, then tested, squashed, and rebased to upstream. Let me know if you need anything else for this to get accepted :)

**Review by gaecoli — APPROVED** [review]
LGTM!

**Comment by gaecoli** [comment]
Thank you! @stefannegele

**Pull request merged**
