### PR TITLE
Allow multiple requests to JIRA when necessary.

### PR DESCRIPTION
**Pull request by dettoni**
Although issue #1721 allowed to use maxResults up to 1k, most of JIRA Cloud instances do not allow maxResults greater than 100, and I think it's impossible to change this limit in JIRA. 

So, I changed to repeat the query increasing the startAt parameter until the defined maxResults is reached.

### CODE REVIEW

**Comment by RichardLitt** [comment]
Thanks @dettoni. I'm curious; why did you close this so soon after it was opened?

**Comment by dettoni** [comment]
It's broken. I will refactor and reopen.

**Comment by guidopetri** [comment]
@dettoni , thanks for the PR! We've updated a lot of things now that we're Community-driven so - if you're still interested in getting this merged - would you mind rebasing off master to re-run the CI, as well as updating merge conflicts?

We're trying to clean up our PR todo list, so if you're not interested, that's fine - we'll close the PR in about a week if we don't hear back. If you're interested in reopening the PR afterwards, we would also very much welcome that.

**Comment by justinclift** [comment]
Interestingly, it looks like the merge conflict is probably fairly easy to solve for someone familiar with Jira + Python:

### redash/query_runner/jql.py

```
<<<<<<< master
    for k, v in issue['fields'].iteritems():
=======
    for k, v in issue["fields"].items():  #
>>>>>>> master
```

So, it's just a single line conflict.

**Pull request closed without merging**
