### PR TITLE
Implement view access permission for Dashboard and Query resources.

### PR DESCRIPTION
**Pull request by meinac**
This feature will be available only if `FEATURE_SHOW_PERMISSIONS_CONTROL`
and `FEATURE_ENABLE_VIEW_PERMISSION` flags are set as +True+.
If user has view access to a dashboard objct, all the queries related to
this dashboard will be accessible by the user but the otherway around is
not possible.

### CODE REVIEW

**Comment by arikfr** [comment]
Thanks! I'll review this once v3 is released (beta should be this week 🤞).

**Comment by meinac** [comment]
@arikfr would you like to merge this into master? Since these changes effect the core of the application, with each new feature, the risk of loosing the track of the code increases.
I would merge this pr ASAP which will be foundation of any other. Please let me know, I'm happy to give any support you need to make this merged.

**Comment by arikfr** [comment]
Thank you for the follow up, @meinac. I didn't have the chance to properly review this after the `v3` release as we dived right into `v4` and you're touching some areas that require careful thought and review.

There are security implications here that need to be reviewed properly, but also I feel that there are few product aspects that we need to think about in a more "holistic" way to make sure we don't apply a patch that will be hard to replace later on.

Now that `v4` is almost done (just fixing few last issues -- mainly #2406), the new knowledge base is out, I'm getting more time to think about this. I will give it some thought and then share with you and the community to discuss the way forward and how this pull request fits in.

How's that sound?

**Comment by luisnunezsalgado** [comment]
Anyone with write permissions, could generate the merge and inclusion of the changes into the main branch of source code ? please

**Comment by arikfr** [comment]
Thanks, @meinac for your contribution. Unfortunately I'm going to close this now. We decided to invest some time to solve the use cases around sharing data in Redash in a more holistic way, including addressing issues with sharing queries with parameters. To follow along you can watch #3284.

**Pull request closed without merging**
