### PR TITLE
Chart Aggregate Y column values rather than displaying last Y value

### PR DESCRIPTION
**Pull request by lvitti**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

## Description
Resubmit the fix created by @akc2267 in the [PR](https://github.com/getredash/redash/pull/4673).

A couple fixes so that Y values are summed. Without this fix, charts will display the final row for every X value. If multiple rows exist for a given X, then those values will be over-written. Plotly displays this info correctly, so without this fix, redash's hover labels are incorrect while Plotly's visual representation is accurate.

## How is this tested?

- [x] Unit tests (pytest, jest)
- [ ] E2E Tests (Cypress)
- [ ] Manually
- [ ] N/A

## Related Tickets & Documents
https://github.com/getredash/redash/issues/4587
https://github.com/getredash/redash/pull/4673

### CODE REVIEW

**Comment by lvitti** [comment]
@guidopetri, @kravets-levko

**Review by eradman — APPROVED** [review]
Tested this change; seems to work perfectly.

agg_y_pie

**Comment by lvitti** [comment]
@justinclift

**Comment by justinclift** [comment]
Somehow missed this one, sorry for the delay. :facepalm: 

Thanks for reviewing it @eradman, and @lvitti good you for being persistent. :grin:

**Pull request merged**
