### PR TITLE
Plug custom Celery tasks via dynamic settings

### PR DESCRIPTION
**Pull request by rauchy**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source)
- [ ] New Alert Destination
- [ ] Other

## Description
This would allow users to provide their own custom tasks to run periodically.

### CODE REVIEW

**Comment by jezdez** [comment]
Huh, that's a new twist on the extension problem, we have had extensible periodic tasks for a while until they were removed in #3465. Would you say the overlap is okay keeping given dynamic settings are more deployment specific and not particularly tied to extensions?

That reminds me @arikfr I just saw your last comment in #3569 about the requirements file added there. Merging this would go a long way to a better separation of App and Worker code.

**Comment by jezdez** [comment]
IOW, I'm very much interested in solving #3466 still.

**Comment by arikfr** [comment]
@jezdez just to clarify: this is not instead of the extension point for periodic tasks as implemented in #3569. This is just another option which is easier to use in some scenarios.

As for the requirements file, I will follow up in #3569.

**Comment by jezdez** [comment]
Okay, understood, thanks for clarification!

**Pull request merged**
