### PR TITLE
Chart series switch places when picking Y axis or color

### PR DESCRIPTION
**Pull request by kravets-levko**
## What type of PR is this? (check all applicable)

- [x] Bug Fix

## Related Tickets & Documents

Fixes getredash/redash#4404

### CODE REVIEW

**Comment by arikfr** [comment]
I've noticed similar behavior when updating colors. Will it address it too?

**Comment by kravets-levko** [comment]
Yes. I noticed that too - see commit message :slightly_smiling_face:

**Comment by kravets-levko** [comment]
@arikfr I'm going merge it, unless you have any comments

**Comment by arikfr** [comment]
@kravets-levko merged it :stuck_out_tongue:

**Pull request merged**
