### PR TITLE
Add: Calendar visualization

### PR DESCRIPTION
**Pull request by androsj**
This is something I'm implementing where I work at. It is based on [FullCalendar](https://fullcalendar.io/) and [UI-Calendar by angular-ui](http://angular-ui.github.io/ui-calendar/).

This is what I've managed so far:
calendar2

### CODE REVIEW

**Comment by androsj** [comment]
As of now this is how's it looking:
calendario con colores

**Comment by androsj** [comment]
@arikfr Hey, I'm glad you took the time to review this.

Good call on the vendoring thing! I knew for sure it was on bower but I hadn't checked on npm.
I just tried it the npm way and it fails because this module has dependencies (jquery, moment, etc)..

Is there a way to include those imports on a npm module ?

**Comment by arikfr** [comment]
Does it fail to install or it fails when trying to use it?

**Comment by androsj** [comment]
The ui-calendar module fails to compile because it cannot resolve its dependencies (jquery, moment, angular, etc).. It is written in ES5. That is why I included a version (calendar.js) with the necessary imports.

**Comment by androsj** [comment]
@arikfr Hey! I think you'll dig the progress I've made on this..

- I added support for a bunch of other views fullcalendar offers. (week, day-agenda, week-list, etc)
- Added 'Group by' support
- Hovering an event now shows a popover with all its info.
- now uses the bootstrap3 theme

**Comment by androsj** [comment]
Will attempt to rebase on top of master soon...

**Comment by androsj** [comment]
Will attempt to rebase on top of master soon...

**Comment by arikfr** [comment]
@androsj considering the significant changes done to visualizations following the React migration, this is no longer viable for merging :-( Thank you for putting in the work and sorry for letting this linger for so long that it became obsolete. :bowing_man:

**Comment by androsj** [comment]
@arikfr I appreciate you taking the time of writing something before closing this.
I implemented this for the self-hosted instance at my workplace, so it wasn't all in vain. We've been using it ever since.

Fullcalendar now actually offers a React component!
Feel free to check it out. 
https://fullcalendar.io/docs/react

**Comment by arikfr** [comment]
@androsj this is the least I could do. 

Are you still using Redash at your work place? 

Good to know that Fullcalendar has a React component :ok_hand:

**Comment by androsj** [comment]
@arikfr yes, everyone loves it at work. I believe we are still on v5 because I would need to reimplement the calendar visualization, which they mainly use to see which employees are on vacation, etc.

**Comment by arikfr** [comment]
@androsj lots of good stuff in the newer releases (including v8 which is about to be wrapped up) :wink: Promise to provide faster turn around for a new calendar viz...

**Pull request closed without merging**
