### PR TITLE
Fix #1101: Query execution fails if user name has unicode characters

### LINKED ISSUE #1101: Query execution fails if user name has unicode characters
```
[2016-06-08 21:16:08,491: ERROR/MainProcess] Task redash.tasks.execute_query[82e3c23b-ceb7-4ed1-81c2-98f8601a6b14] raised unexpected: UnicodeEncodeError('ascii', u'/* Username: \u4f0a\u85e4\u76f4\u4e5f, Task ID: 82e3c23b-ceb7-4ed1-81c2-98f8601a6b14, Query ID: 6, Queue: queries, Query Hash: f1fc50d12a0b5cd0279b42db51130dbe */ SELECT TOP 100 *\nFROM CurrentDB.dbo.Booking', 13, 17, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/redash/redash.0.11.0.b1903/redash/tasks/base.py", line 13, in __call__
    return super(BaseTask, self).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/redash/redash.0.11.0.b1903/redash/tasks/queries.py", line 445, in execute_query
    return QueryExecutor(self, query, data_source_id, metadata).run()
  File "/opt/redash/redash.0.11.0.b1903/redash/tasks/queries.py", line 395, in run
    data, error = query_runner.run_query(annotated_query)
  File "/opt/redash/redash.0.11.0.b1903/redash/query_runner/mssql.py", line 125, in run_query
    cursor.execute(query)
  File "pymssql.pyx", line 445, in pymssql.Cursor.execute (pymssql.c:6242)
  File "_mssql.pyx", line 998, in _mssql.MSSQLConnection.execute_query (_mssql.c:10085)
  File "_mssql.pyx", line 1029, in _mssql.MSSQLConnection.execute_query (_mssql.c:9964)
  File "_mssql.pyx", line 1149, in _mssql.MSSQLConnection.format_and_run_query (_mssql.c:11030)
  File "_mssql.pyx", line 200, in _mssql.ensure_bytes (_mssql.c:2544)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 13-16: ordinal not in range(128)
```

### Steps to Reproduce

- My user name is "伊藤直也"
- Using mssql query runner
- Querying "select top 100 * from sometable"

When using BigQuery query runner, This error doesn't happen.

### Technical details:

* Redash Version: v0.10.1.b1834,  0.11.0 - RC
* Browser/OS: Google Chrome/OSX / Server: ubuntu Linux 16.04 LTS
* How did you install Redash: used `setup/ubuntu/bootstrap.sh`

### PR DESCRIPTION
**Pull request by kitsuyui**
- Encode the query with connection's charset when its type is unicode(not str).

- Ref: #1101

### CODE REVIEW

**Comment by arikfr** [comment]
Thanks! I think a safer solution will be to disable query annotations for MSSQL query runner. All it requires is to add the following to the query runner class:

```python
    @classmethod
    def annotate_query(cls):
        return False
```

**Comment by kitsuyui** [comment]
@arikfr 
Okay! I will try your suggestion.

> ```python
    @classmethod
    def annotate_query(cls):
        return False
```

**Comment by kitsuyui** [comment]
@arikfr 

> Okay! I will try your suggestion.

I tried.

But it is incomplete.
When unicodes come from query body(not from query annotations), UnicodeEncodeError still occurs.
Because the query will be unicode string eventually.

# Example

## Query like this:

```sql
SELECT 'あいうえお';
```

## Result:

```console
[2016-06-13 10:56:54,335: ERROR/MainProcess] Task redash.tasks.execute_query[3fc57eb9-1fde-4aa3-b176-bdab4e32cbfb] raised unexpected: UnicodeEncodeError('ascii', u"SELECT '\u3042\u3044\u3046\u3048\u304a';
", 8, 13, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/redash/redash.0.11.0.b1903/redash/tasks/base.py", line 13, in __call__
    return super(BaseTask, self).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/redash/redash.0.11.0.b1903/redash/tasks/queries.py", line 445, in execute_query
    return QueryExecutor(self, query, data_source_id, metadata).run()
  File "/opt/redash/redash.0.11.0.b1903/redash/tasks/queries.py", line 395, in run
    data, error = query_runner.run_query(annotated_query)
  File "/opt/redash/redash.0.11.0.b1903/redash/query_runner/mssql.py", line 134, in run_query
    cursor.execute(query)
  File "pymssql.pyx", line 445, in pymssql.Cursor.execute (pymssql.c:6242)
  File "_mssql.pyx", line 998, in _mssql.MSSQLConnection.execute_query (_mssql.c:10085)
  File "_mssql.pyx", line 1029, in _mssql.MSSQLConnection.execute_query (_mssql.c:9964)
  File "_mssql.pyx", line 1149, in _mssql.MSSQLConnection.format_and_run_query (_mssql.c:11030)
  File "_mssql.pyx", line 200, in _mssql.ensure_bytes (_mssql.c:2544)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 8-12: ordinal not in range(128)
[2016-06-13 10:57:29,418: ERROR/MainProcess] Task redash.tasks.execute_query[422329db-3019-46cf-b24e-4e2d5a813e14] raised unexpected: UnicodeEncodeError('ascii', u"SELECT '\u3042\u3044\u3046\u3048\u304a';", 8, 13, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/redash/redash.0.11.0.b1903/redash/tasks/base.py", line 13, in __call__
    return super(BaseTask, self).__call__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/redash/redash.0.11.0.b1903/redash/tasks/queries.py", line 445, in execute_query
    return QueryExecutor(self, query, data_source_id, metadata).run()
  File "/opt/redash/redash.0.11.0.b1903/redash/tasks/queries.py", line 395, in run
    data, error = query_runner.run_query(annotated_query)
  File "/opt/redash/redash.0.11.0.b1903/redash/query_runner/mssql.py", line 134, in run_query
    cursor.execute(query)
  File "pymssql.pyx", line 445, in pymssql.Cursor.execute (pymssql.c:6242)
  File "_mssql.pyx", line 998, in _mssql.MSSQLConnection.execute_query (_mssql.c:10085)
  File "_mssql.pyx", line 1029, in _mssql.MSSQLConnection.execute_query (_mssql.c:9964)
  File "_mssql.pyx", line 1149, in _mssql.MSSQLConnection.format_and_run_query (_mssql.c:11030)
  File "_mssql.pyx", line 200, in _mssql.ensure_bytes (_mssql.c:2544)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 8-12: ordinal not in range(128)
```

**Comment by arikfr** [comment]
@kitsuyui in the case of the example you gave, what is the value of `connection._conn.charset`?

**Comment by kitsuyui** [comment]
In my case, `UTF-8`.

Because

1. pymssql.connect called at [here](
https://github.com/kitsuyui/redash/blob/91e99c42cd0d4c2aeaf49e8ca24c247af3809c65/redash/query_runner/mssql.py#L121) with [default charset parameter](http://pymssql.org/en/latest/ref/pymssql.html#pymssql.connect).

2. `connection` has the property [_conn](https://github.com/pymssql/pymssql/blob/master/src/pymssql.pyx#L229-L238). It is an instance of [_mssql.MSSQLConnection](http://pymssql.org/en/latest/ref/_mssql.html#_mssql.MSSQLConnection). It was [initialized](https://github.com/pymssql/pymssql/blob/master/src/pymssql.pyx#L581-L638) by pymssql with `pymssql.connect`.
3. So it is `UTF-8`.

**Comment by kitsuyui** [comment]
If you were hesitating to add manipulating private parameters, I can suppose another solution.

To add `charset` parameters on [configuration_schema](https://github.com/kitsuyui/redash/blob/91e99c42cd0d4c2aeaf49e8ca24c247af3809c65/redash/query_runner/mssql.py#L34-L59
) and pass it to `pymssql.connect`.

**Comment by arikfr** [comment]
> If you were hesitating to add manipulating private parameters, I can suppose another solution.

I was both hesitant because of the private parameters manipulation, but also because it felt strange that `pymssql` doesn't support `unicode` objects...

Let's do something similar to what you suggested -- pass an explicit charset setting to the connection string (which is `UTF-8`) and use it for encoding. But let's _not_ add another setting.

**Comment by arikfr** [comment]
Btw, thank you for your effort in investigating this.

**Comment by kitsuyui** [comment]
@arikfr 
Thank you.
I updated my Pull Request to fit with latest commits and the decision!

**Comment by arikfr** [comment]
Thanks!

**Pull request merged**
