### PR TITLE
Visualization Editor: consistent styles for control labels

### PR DESCRIPTION
**Pull request by kravets-levko**
## What type of PR is this? (check all applicable)

- [x] Refactor

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

Before/After (checkbox labels):

image

image

### CODE REVIEW

**Comment by gabrieldutra** [comment]
I actually prefer it with `font-weight: normal` :sweat_smile:. It's been changed since [this](https://github.com/getredash/redash/pull/3296#discussion_r248618992). Anyway, I think it makes sense to be a change to the whole application (not only to the Visualization Editor), regardless of the choice.

**Comment by kravets-levko** [comment]
Hm :thinking: For me it looks wrong if some labels have normal font weight and others are bolder (especially when there are both types on the same form). So what you suggest? Make all labels bolder? normal? keep everything as is?

**Comment by arikfr** [comment]
The mental model I have: the non checkbox labels are more like titles while the label for a checkbox is more like regular text. Hence why one is bold and the other isn't.

I vote for keeping as is.

**Comment by arikfr** [comment]
As we don't have a consensus here I'm closing it.

**Pull request closed without merging**
