### PR TITLE
removed explicit object inheritance

### PR DESCRIPTION
**Pull request by AndrewChubatiuk**
## What type of PR is this? 
Removed unneeded explicit inheritance from object

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] New Query Runner (Data Source) 
- [ ] New Alert Destination
- [ ] Other

### CODE REVIEW

**Review by eradman — CHANGES_REQUESTED** [review]
I'm fine with this change. We would also want to add this check to ruff

```diff
+++ b/pyproject.toml
@@ -169,7 +169,7 @@ build-backend = "poetry.core.masonry.api"
 [tool.ruff]
 exclude = [".git", "viz-lib", "node_modules", "migrations"]
 ignore = ["E501"]
-select = ["C9", "E", "F", "W", "I001"]
+select = ["C9", "E", "F", "W", "I001", "UP004"]
```

**Comment by AndrewChubatiuk** [comment]
@eradman  done

**Review by eradman — APPROVED** [review]

**Comment by masayuki038** [comment]
@AndrewChubatiuk Thanks for separating the PR.

**Comment by masayuki038** [comment]
@eradman Thanks for your review. I didn't find that we should update `ruff` settings.

**Review by masayuki038 — APPROVED** [review]
I confirmed this updates all classes to be fixed. I will merge this.

**Pull request merged**
