### PR TITLE
Add: TSV export option

### PR DESCRIPTION
**Pull request by dheerajrav**
Most of the data analysts prefer downloading the data
as tsvs instead of csvs as individual columns themselves
have commas in them. Having download as a TSV solves
this issue.

### CODE REVIEW

**Comment by dheerajrav** [comment]
@arikfr Please have a look and let me know what you think.

**Comment by arikfr** [comment]
@dheerajrav are you planning on rebasing?

**Comment by dheerajrav** [comment]
@arikfr Sorry about this. On rebasing, I was not able to get the code working. You can close this for now. I will re-open it when I have to code working.

**Comment by arikfr** [comment]
It might be simpler to take a recent master branch and apply your changes.

**Pull request closed without merging**
