### PR TITLE
Remove --max-old-space-size=4096 from npm build command

### PR DESCRIPTION
**Pull request by arikfr**
## What type of PR is this? (check all applicable)

- [x] Other

## Description

Looks like it's no longer needed.

Related: #4195.

### CODE REVIEW

**Comment by kravets-levko** [comment]
Seems it does not work: build failed with out of memory error in node

**Comment by arikfr** [comment]
> Seems it does not work: build failed with out of memory error in node

Strange it worked locally after the unused dependencies removal. Will verify again.

**Comment by arikfr** [comment]
Looks like it's also Node version dependent. I wonder if changing this now will break existing environments for people? :-\

I did stumble at [Volta](https://volta.sh/) recently, which makes it easy to run the correct Node version per project so maybe it's not a huge deal.

@kravets-levko @gabrieldutra @rauchy what Node version you have locally?

**Comment by rauchy** [comment]
Locally I'm on v11.9, but I don't do local nowadays :) so it's v8.10

**Comment by arikfr** [comment]
@rauchy 

> Locally I'm on v11.9, but I don't do local nowadays :) so it's v8.10

v8.10 :scream: Just use Volta. Takes a minute and you have whatever version you want.

**Comment by kravets-levko** [comment]
> what Node version you have locally?

v10.13.0

**Comment by gabrieldutra** [comment]
> what Node version you have locally?

v12.13.0, I updated a few days ago :slightly_smiling_face:

**Comment by rauchy** [comment]
> Just use Volta. Takes a minute and you have whatever version you want.

It really did!

**Comment by arikfr** [comment]
I added another npm run command `build:old-node-version`, which has the old max memory setting for those who use an older Node version.

**Pull request merged**
