### PR TITLE
Fixed the fix.

### PR DESCRIPTION
**Pull request by jezdez**
Fix for #2877.

Clicked merge too fast 😬

### CODE REVIEW

**Comment by arikfr** [comment]
that's why I didn't merge immediately, wanted to make sure it actually works ;-)

But we should rename the file to be the same as the component or the component to be the same as the filename.

**Comment by jezdez** [comment]
Dang, admittedly this was me being too eager to fix things in new code, apologies @arikfr!

**Comment by jezdez** [comment]
@arikfr Updated the PR.

**Comment by kocsmy** [comment]
Name is 10/10 :D

**Comment by jezdez** [comment]
Whelp, more fixes. I'm gonna slowly walk back from this keyboard now, but I think the tests should pass now 🤓

**Pull request merged**
