### PR TITLE
Make actions column fixed

### PR DESCRIPTION
**Pull request by kravets-levko**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix

## Description

Possible fix for getredash/redash#3521: make columns with action buttons fixed (see screenshots).

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

image

image

### CODE REVIEW

**Comment by ranbena** [comment]
@kravets-levko Even-though #3545, this could function as a fail-safe in case sth gets messed up. Wdyt?

**Comment by gabrieldutra** [comment]
> @kravets-levko Even-though #3545, this PR could function as a fail-safe in case sth gets messed up. Wdyt?

This is currently being applied to mobiles, even though #3545:
mobile-users

**Comment by kravets-levko** [comment]
@gabrieldutra because, as I mentioned, fixing group labels is not enough - on narrow screens there will be scroll anyway.

**Comment by kravets-levko** [comment]
@ranbena 

> Even-though #3545, this PR could function as a fail-safe in case sth gets messed up. Wdyt?

While it fixes the bug perfectly, design-wise it's unappealing. :grin:

**Comment by ranbena** [comment]
Mobile needs a a different layout. This doesn't work with or without the fixed col.
IMO, if it can be easily turned off for mobile - let's use it, if not - let's withdraw the idea.

**Comment by kravets-levko** [comment]
While this fix was one of possible options, I don't like it that much. Therefore I decided to close this PR. We should find a better solution for lists on small screens.

**Pull request closed without merging**
