### PR TITLE
Adds influxdb v2 query runner as a default query runner.

### PR DESCRIPTION
**Pull request by fabrei**
## What type of PR is this? 

- [x] Bug Fix

## Description

A new query runner for influxdb v2 was added, but forgotten to add as default query runner in redashs' settings. This is a PR which solves it. At the moment it can be added manually by using an environmental variable: `REDASH_ADDITIONAL_QUERY_RUNNERS=redash.query_runner.influx_db_v2`

## How is this tested?

- [x] Manually

With current docker image, InfluxDBv2 query runner does not appear in list of all query runners. I added it manually in redashs' settings and restarted the container. After that, the runner appeared in list.

## Related Tickets & Documents

There is a ticket #5391 and PR https://github.com/getredash/redash/pull/6646

### CODE REVIEW

**Comment by fabrei** [comment]
```
 Container cypress-redis-1  Running
 Container cypress-postgres-1  Running
Traceback (most recent call last):
  File "/app/manage.py", line 6, in <module>
    from redash.cli import manager
  File "/app/redash/__init__.py", line 53, in <module>
    import_query_runners(settings.QUERY_RUNNERS)
  File "/app/redash/query_runner/__init__.py", line 437, in import_query_runners
    __import__(runner_import)
  File "/app/redash/query_runner/influx_db_v2.py", line 41, in <module>
    class InfluxDBv2(BaseQueryRunner):
  File "/app/redash/query_runner/influx_db_v2.py", line 155, in InfluxDBv2
    def _get_data_from_tables(self, tables: TableList) -> Dict:
NameError: name 'TableList' is not defined
```

Why is that happening? Did I miss to add a dependency somewhere? I already added the dependency in `pyproject.toml` and created a new poetry lock file in the PR which added this query runner.

**Comment by masayuki038** [comment]
@fabrei The recent CI has been successful at all, so I think the error is caused by this update.
- https://github.com/getredash/redash/actions/runs/7238652870
- https://github.com/getredash/redash/actions/workflows/ci.yml

Could you investigate this? From a personal point of view, I'm concerned that the class name InfluxDBClient is loaded from different modules.

- https://github.com/getredash/redash/blob/master/redash/query_runner/influx_db.py
- https://github.com/getredash/redash/blob/master/redash/query_runner/influx_db_v2.py

**Comment by fabrei** [comment]
> @fabrei The recent CI has been successful at all, so I think the error is caused by this update.
> 
>     * https://github.com/getredash/redash/actions/runs/7238652870
> 
>     * https://github.com/getredash/redash/actions/workflows/ci.yml

Yeah, the current one fails, because now the new runner is imported on startup. It throws the error at [this point](https://github.com/getredash/redash/actions/runs/7261538944/workflow#L135). 

> Could you investigate this? From a personal point of view, I'm concerned that the class name `InfluxDBClient` is loaded from different modules.
> 
>     * https://github.com/getredash/redash/blob/master/redash/query_runner/influx_db.py
> 
>     * https://github.com/getredash/redash/blob/master/redash/query_runner/influx_db_v2.py

The error says, that the `TableList` is not defined. But it gets [imported](https://github.com/getredash/redash/blob/master/redash/query_runner/influx_db_v2.py#L20). But if the module can't be imported, `TableList` is not defined, as the `ImportError` is caught. So I guess, that in CI the module `influxdb-client` is not installed as a requirement. Even if the code is not used in CI, `TableList` is used in the code for [method definition](https://github.com/getredash/redash/blob/master/redash/query_runner/influx_db_v2.py#L155). 

So, I don't think it is related to the different influxdb modules. If I start redash in a container, with this change, it runs and I can use the new query runner without adding it manually by defining `REDASH_ADDITIONAL_QUERY_RUNNERS`.  And if I call `from redash.cli import manager` from my python shell, as in the traceback is seen, it works in my redash virtual environment as well.

**Comment by masayuki038** [comment]
@fabrei OK. So what do you do with this PR?

**Comment by fabrei** [comment]
> @fabrei OK. So what do you do with this PR?

I would like to understand, why this module is not present at that moment. But I am not familiar with running a CI on github and what happens in the background. Is it possible to run the ci locally? If yes, how?

But what I see is, the error occurs in "frontend-e2e-tests" where cypress test cases are run. So it needs redash. But obviously redash is not setup correctly. Otherwise it would install the influxdb-client dependency and not fail. Or do I miss something?

I think deleting `TableList` from method definition would fix it, but that's not what I want to do.

**Comment by masayuki038** [comment]
@fabrei The way to run e2e test on local is described in https://github.com/getredash/redash/wiki/Testing-your-changes#comprehensive-e2e-testing-cypress.

However, it failed to run `create_db` with docker compose. I don't think this is the cypress issue.

```
Error: Command failed: docker compose -p cypress run server create_db
```

I belive you can do logging the object of `ImportError`.

**Comment by fabrei** [comment]
> @fabrei The way to run e2e test on local is described in https://github.com/getredash/redash/wiki/Testing-your-changes#comprehensive-e2e-testing-cypress.

Thanks, I didn't see this page.
 
> However, it failed to run `create_db` with docker compose. I don't think this is the cypress issue.
> 
> ```
> Error: Command failed: docker compose -p cypress run server create_db

Where did you see this error?

---

Ok, I think I got a better understanding what's happening. In CI container it does not install all dependencies. As you can see [here](https://github.com/getredash/redash/actions/runs/7261538944/job/19784633841#step:6:1062), poetry installs all main dependencies under [tool.poetry.dependencies](https://github.com/fabrei/redash/blob/influxdb-v2-as-default-query-runner/pyproject.toml#L24). But the influxdb-client is not listed there. It is listed under [tool.poetry.group.all_ds.dependencies](https://github.com/fabrei/redash/blob/influxdb-v2-as-default-query-runner/pyproject.toml#L107). I added it there, because the other influxdb dependency was listed there. 

I see two options here. 

1. Put the dependency entry under `tool.poetry.dependencies` instead of `tool.poetry.group.all_ds.dependencies`. But I don't know, if this is be the right way. I understand this dependencies as the main ones which is needed for the core of redash. But the influxdb-client is just an "add on"; in my opinion.
2. I delete the usage of `TableList`, because it is not needed for the query runners' function. It is "only" used for typing. The dependency stays where it is now.

What do you think @masayuki038 ?

**Comment by masayuki038** [comment]
@fabrei 
> Where did you see this error?

On the same page.
image

**Comment by masayuki038** [comment]
@fabrei Thanks for your investigation. I think 2. is reasonable.

**Comment by fabrei** [comment]
> @fabrei Thanks for your investigation. I think 2. is reasonable.

Ok, the CI has passed. Thanks for your help :)

**Pull request merged**
