### PR TITLE
Automatically tag release candidates

### PR DESCRIPTION
**Pull request by eradman**
Format similar to Ubuntu: _YY.MM.N_

Discussion thread: https://github.com/getredash/redash/discussions/6411

## What type of PR is this? 

- [x] Feature

## How is this tested?

Replace github `schedule` with `workflow_dispatch` to trigger manually

```yaml
on: workflow_dispatch
```

### CODE REVIEW

**Review by guidopetri — APPROVED** [review]

**Comment by eradman** [comment]
As far as I can tell yarn will not accept `23.09` as a version, it must be 23.09.0.

I suppose `.0` could be the automatic tag, and `.1`, `.2`, `.3` etc. the release versions

**Comment by guidopetri** [comment]
What about the other way around? `<version>.YY.MM` would let us keep some notion of "upgrade major versions only if you are sure about it".

**Comment by justinclift** [comment]
To me, `23.09.0` seems like it would be the right choice.

That's:

* Major version `23`
* Month being `09`
* Patch / release of the series = `0`

**Comment by eradman** [comment]
@justinclift I adjusted this PR to match scheme you proposed. It makes yarn happy and it's easy to understand.

**Review by justinclift — APPROVED** [review]
Looks good to me. :smile:

**Comment by justinclift** [comment]
Cool, good stuff.  I've just set it to auto-merge as soon as the E2E tests pass. :smile:

**Comment by lucasfcnunes** [comment]
@justinclift are the bump in the Pre-release and Latest tags already planned?

**Comment by justinclift** [comment]
When you say "bump" there, what are you meaning? :smile:

**Comment by lucasfcnunes** [comment]
In this case the labels (Latest, Pre-release, ...) going from version A to version B.
Or simply: version A to version B.

image


https://nvie.com/posts/a-successful-git-branching-model/
https://stackoverflow.com/a/10834954/6446567

**Pull request merged**
