### PR TITLE
Rockset integration: Load collections in all workspaces

### PR DESCRIPTION
**Pull request by ari-e**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] New Query Runner (Data Source)
- [ ] New Alert Destination
- [ ] Other

## Description
Previously the Rockset integration would only load schemas for collections in the default "commons" workspace. This PR fixes that to load all workspaces. This is a high-pri fix as it is blocking customers who want to use Redash + Rockset from making the switch from other visualization tools like Tableau since they are unable to view all of their data in Redash currently.

### CODE REVIEW

**Comment by arikfr** [comment]
Thanks.

**Comment by arikfr** [comment]
@ari-e if you have any users who use our hosted service and experience this issue, please guide them to reach out via support and we will escalate the deployment of this fix.

**Comment by ari-e** [comment]
Thanks @arikfr. When is the next regularly scheduled deploy?

**Comment by ari-e** [comment]
@arikfr we have a customer actively blocked on this in their hosted service. Their red ash.io site is ubiquity6 for reference

**Comment by arikfr** [comment]
@ari-e I expect this to be deployed tomorrow (Sunday). I will post another update when it’s actually deployed.

**Comment by arikfr** [comment]
@ari-e 

1. This was deployed.
2. I realized that now that we use Python 3, we can use your official library.

**Pull request merged**
