### PR TITLE
Python query runner improvements

### PR DESCRIPTION
**Pull request by denisov-vlad**
## What type of PR is this? (check all applicable)

- [ ] Feature

## Description

- Added function which converts pandas dataframe to result dict. It will be added only if pandas is installed.
```
import pandas as pd
df = pd.DataFrame([{"a": 1, "b": "str"}, {"a": 2, "b": "str2"}])
dataframe_to_result(result, df)
```
- Added option to get `execute_query` result as pandas dataframe
```
df = execute_query(data_source_id, query, "dataframe")
```
- Added `inplacevar` (i.e. `+=`, `*=, etc.) support

### CODE REVIEW

**Comment by susodapop** [comment]
What's the status for this PR?

FYI: pandas is installed by default on `master`

**Comment by denisov-vlad** [comment]
@susodapop removed WIP status. 

> FYI: pandas is installed by default on master
I haven't seen it in requirements.txt. If it's a sub-dependency from other package I will remove it my request.

**Comment by susodapop** [comment]
I resolved the merge conflict against `master`.

**Review by susodapop — APPROVED** [review]
LGTM. Just waiting for the CircleCI build to pass before merging.

**Pull request merged**
