### PR TITLE
Change new data source group attachment

### PR DESCRIPTION
**Pull request by leandro-lorenzini**
## What type of PR is this? 

- [x] Refactor

## Description
As both data sources and  new users are automatically added to the default group (at least when using SAML authentication), the creation of more groups would be silly as everyone would have access to all data sources anyway. So an idea would be to attach new data sources to the admin group instead.

## How is this tested?

- [x] Manually

Created a new data source and checked to which group it was assigned to.

### CODE REVIEW

**Comment by susodapop** [comment]
Can we gate this behind an environment variable so that admins can opt-in to this behaviour?

**Review by susodapop — CHANGES_REQUESTED** [review]
Let's control this with an environment variable so that the existing behaviour is still the default, but admins can modify it.

**Comment by susodapop** [comment]
Closing this PR for inactivity. Feel free to reopen if you'd like to pick this up in the future.

**Comment by arikfr** [comment]
This is not related to the Pull Request directly, but I assume that the author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.

**Pull request closed without merging**
