### PR TITLE
LDAP authentication & filter results

### PR DESCRIPTION
**Pull request by ohadmata**
this feature add filter at the top of each dynamic table

### CODE REVIEW

**Comment by ohadmata** [comment]
This is a full replacement for active directory integration to redash
with LDAP library.

After installation you will be able to connect redash only with active
directory users.

this permission mapping will be with active directory groups

**Comment by jeffwidman** [comment]
Hey @ohadmata curious why you did this rather than use the LDAP integration from #1836?

**Comment by ohadmata** [comment]
1. I didnt see this. :-(
2. The most important thing to me is to map active directory groups to redash groups. #1835 dont support this feature

**Comment by arikfr** [comment]
LDAP was already implemented in #1836. You're welcome to submit a pull request for the group sync.

**Pull request closed without merging**
