### PR TITLE
npm audit fixes

### PR DESCRIPTION
**Pull request by ranbena**
## What type of PR is this? (check all applicable)

- [x] Other (Right?) _(right - @kravets-levko :smile:)_

## Description
Since #3405 npm's security audit feature prompts for some vulnerabilities found.

* `less` upgraded
AntD uses some css animation js and since we're importing ant less files directly, had to update a webpack config to allow it. I assume it can be turned off when we officially migrate to AntD? (BOOTSTRAP_REMOVE_ME?).

* `url-loader`upgraded
Used for font fetching, works fine.

* `plotly.js` not upgraded
Although [plotly.js security warning](https://www.npmjs.com/advisories/766), there's [no fix out](https://github.com/plotly/plotly.js/issues/2822).

### CODE REVIEW

**Comment by kravets-levko** [comment]
@ranbena  I'm just curious: why did you decide to not upgrade plotly?

**Comment by ranbena** [comment]
> @ranbena I'm just curious: why did you decide to not upgrade plotly?

Cause it won't fix the security vulnerability.
https://github.com/plotly/plotly.js/issues/2822

**Comment by arikfr** [comment]
@kravets-levko it's common to have some regressions when upgrading Plotly, so I would do it separately and review the changes.

**Comment by arikfr** [comment]
(by I above I meant whoever does the upgrade, not necessarily me 😄 )

**Pull request merged**
