### PR TITLE
Update SQLAlchemy-Utils to 0.36.5

### PR DESCRIPTION
**Pull request by eradman**
## What type of PR is this? 

- [x] Upgrade

## Description

This makes the Python unit tests compatible with Python 3.10 while maintaining compatibility with 3.8.

## How is this tested?

- [x] Unit tests (pytest, jest)

### CODE REVIEW

**Review by guidopetri — APPROVED** [review]

**Comment by denisov-vlad** [comment]
Hi!

@eradman @guidopetri @justinclift 

This PR breaks existing Redash deployments - nothing works after the upgrade. Downgrading to 0.34.2 will help.

```
[2023-09-19 17:42:17,458][PID:10][ERROR][redash.app] Exception on /api/data_sources [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask_login/utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/app/redash/handlers/base.py", line 31, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/redash/permissions.py", line 71, in decorated
    return fn(*args, **kwargs)
  File "/app/redash/handlers/data_sources.py", line 110, in get
    for ds in data_sources:
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 100, in instances
    cursor.close()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 80, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 80, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 579, in _instance
    _populate_full(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 725, in _populate_full
    dict_[key] = getter(row)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/type_api.py", line 1283, in process
    return process_value(value, dialect)
  File "/app/redash/models/types.py", line 30, in process_result_value
    super(EncryptedConfiguration, self).process_result_value(value, dialect)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 414, in process_result_value
    decrypted_value = self.engine.decrypt(value)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 218, in decrypt
    decrypted = self.fernet.decrypt(value.encode())
AttributeError: 'memoryview' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_login/utils.py", line 279, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/app/redash/handlers/base.py", line 31, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/redash/permissions.py", line 71, in decorated
    return fn(*args, **kwargs)
  File "/app/redash/handlers/data_sources.py", line 110, in get
    for ds in data_sources:
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 100, in instances
    cursor.close()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 80, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 80, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 636, in _instance
    to_load = _populate_partial(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 782, in _populate_partial
    dict_[key] = getter(row)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/type_api.py", line 1283, in process
    return process_value(value, dialect)
  File "/app/redash/models/types.py", line 30, in process_result_value
    super(EncryptedConfiguration, self).process_result_value(value, dialect)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 414, in process_result_value
    decrypted_value = self.engine.decrypt(value)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/types/encrypted/encrypted_type.py", line 218, in decrypt
    decrypted = self.fernet.decrypt(value.encode())
AttributeError: 'memoryview' object has no attribute 'encode'
```

**Comment by eradman** [comment]
@denisov-vlad what is the best way to reproduce this problem?

**Comment by justinclift** [comment]
Ok.  We'd better revert this commit for now, and it can be re-applied later on along with whatever is needed to make it work properly.

**Comment by justinclift** [comment]
I've created PR #6466 for reverting this.  I'm not super familiar with poetry yet, so would appreciate someone looking over that PR to confirm it's ok. :smile:

**Comment by eradman** [comment]
I able to reproduce this problem. Steps:

1. Revert SQLAlchemy-Utils (Edit `pyproject.toml`, run `poetry update sqlalchemy-utils`)
2. Build docker image (`make`)
3. Run `make up`, `make create_database`
4. Confirm the correct library using `docker exec`, `ls /usr/local/lib/python3.8/site-packages/SQLAlchemy_Utils-0.34.2.dist-info/`
5. Add datasource and sample query
6. Kill the server, worker, scheduler, and redis (`docker ps`, `docker kill`)
7. Build redash with the latest checkout
8. Run `make up`
9. Try to refresh a query
10. Use `docker logs` to show server messages

I thought there might be some stale state in Redis causing this, but it seems not

```
docker exec -it 036f458f94d4 redis-cli
127.0.0.1:6379> FLUSHALL SYNC
OK
```

**Comment by justinclift** [comment]
> Build redash with the latest checkout

@eradman Just for clarity, are you saying the latest source code still has the problem?  It shouldn't, as the `master` branch was reverted to the older version of `sqlalchemy-utils`.

**Comment by eradman** [comment]
@justinclift I was testing with commit b84587931f720ab94c7de17842ed3db0e25c937e (Sep 12), so you're right this is not the latest

**Comment by justinclift** [comment]
No worries. :smile:

**Pull request merged**
