### PR TITLE
Query page layout improvements for small screens

### PR DESCRIPTION
**Pull request by kravets-levko**
Issue getredash/redash#2796 (items related to query page).

1. Change layout with fixed blocks to scrollable; some blocks (header, footer) kept fixed; editor, query metadata and results are scrollable (see screenshots).
2. Query metadata block now is a bit smaller and compact (to save some space), but still well-readable.

Screenshots:

image
image
image
image
image

### CODE REVIEW

**Comment by arikfr** [comment]
How does it look like in the following cases:

- Longer title? Try: "Latest Queries Executed By a User", "Where People Click on Get Started"
- Long title with 2-3 tags?
- Longer user name (like: "Arik Fraimovich" 😬)

Also:
- We should hide the "+ New Visualization" button, I doubt anyone will use it on mobile.
- Same goes with "Publish" button.
- There needs to be padding between the button and the data source selector.

**Comment by arikfr** [comment]
Btw, how does the data only view looks like after these changes?

**Comment by kravets-levko** [comment]
There are two screenshots with data-only  views (in portrait and landscape orientations)

**Comment by kravets-levko** [comment]
1. Long title:
image

2. Tags are hidden on small screens (it was already implemented in this way, I didn't change anything).

3. (Very) long user name:
image


Other fixes will do ASAP and ping you. Also noticed that header looks not well in non-mobile layout:
image
I'm not sure - is it intentional or a bug? If the second -  I think I'll fix it too.

**Comment by arikfr** [comment]
> Tags are hidden on small screens (it was already implemented in this way, I didn't change anything).

@kocsmy why?

> I'm not sure - is it intentional or a bug? If the second - I think I'll fix it too.

Worth fixing. Maybe always show the tags in the row below the title? 

Also, once we remove the publish button, we can give more space to the title on mobile.

**Comment by kocsmy** [comment]
> Tags are hidden on small screens (it was already implemented in this way, I didn't change anything). Why?

I'm not sure if this is intentional. We can show them.

**Comment by arikfr** [comment]
> I'm not sure if this is intentional. We can show them.

We should show them :)

**Comment by kravets-levko** [comment]
1. Hide "New visualization" and "Publish" buttons in mobile mode.

2. Fix paddings: between the button and the data source selector (in mobile mode), between icon ant text in buttons (in desktop mode):
image
image


3. Fix "Execute" button appearance when running query:
image

4. Show tags in mobile mode and fix header layout: now tags are placed under the title on all screens:
image
image
image
image
image
image

**Comment by kocsmy** [comment]
LGTM2

**Comment by arikfr** [comment]
🙌

**Pull request merged**
