### PR TITLE
Align numbers right in table

### PR DESCRIPTION
**Pull request by kyoshidajp**
I'd like to align numbers right in result list.

Numbers are integer and float. Other types are same as before.

# Screenshot

## before
align_before

## after
align_after

### CODE REVIEW

**Comment by kravets-levko** [comment]
Hi @kyoshidajp! We're already working on improving table viz - first step of issue getredash/redash#1356 is waiting for merge, and this functionality is already implemented there.

**Comment by kyoshidajp** [comment]
Thanks @kravets-levko. I’m looking forward to merge the PR.

**Comment by kravets-levko** [comment]
Hi @kyoshidajp! New table viz is merged into master, you can check it out and try. Just decided to notify you :-)

**Comment by kyoshidajp** [comment]
@kravets-levko Great! I have already checked the behavior. Many thanks 👍

**Pull request closed without merging**
