### PR TITLE
Fix: Query editor duplicates keystrokes (#2972)

### LINKED ISSUE #2972: Query editor duplicates keystrokes
### Issue Summary

When typing in the query editor seemingly random keystrokes are duplicated, this makes it almost impossible to use.

Imgur

### Technical details:

* Redash Version: 5.0.0+b4754
* Browser/OS: Chrome Version 69.0.3497.100 (Official Build) (64-bit) & Firefox 62.0.3 (64-bit). Windows 10 Pro
* How did you install Redash: Self hosted running on Kubernetes

### PR DESCRIPTION
**Pull request by ranbena**
Bug in code caused js error which messed up the query editor.
`keywords` was set to empty array instead of the `table/column/tableColumn` structure.

Closes #2972.

### CODE REVIEW

**Comment by gabrieldutra** [comment]
I don't think #2972 was caused due to this (since this was not in that version). However, I did miss it and this could cause a similar issue at some flow 😅

**Comment by ranbena** [comment]
> I don't think #2972 was caused due to this (since this was not in that version). However, I did miss it and this could cause a similar issue at some flow 😅

Hmm.. yeah if such a generic breakage in the flow causes this, it could be caused by other bugs as well. FYI, I'm able to consistently reproduce this on latest and this definitely fixes it.

**Comment by arikfr** [comment]
👍

**Comment by arikfr** [comment]
@gabrieldutra you're right that the original issue was probably due to something else, but I doubt it still exists.

**Pull request merged**
