### PR TITLE
Create sqlalchemy_searchable expressions

### PR DESCRIPTION
**Pull request by azundo**
The required sql expressions for sqlalchemy_searchable are only created on the sqlalchemy pre_create hook. When upgrading from a previous redash version, there may be no CREATE statements in any applicable migrations, so these sql expressions are never created.

In a fresh install the hook runs properly so there's no issue with the search functionality.

Add a migration to manually execute the sql_expressions DDL from sqlalchemy_searchable.

## What type of PR is this? 

- [x] Bug Fix

## Description

The required sql expressions for sqlalchemy_searchable are only created on the sqlalchemy pre_create hook. When upgrading from a previous redash version no CREATE statements may be run, so these expressions are never created.

## How is this tested?

- [x] Manually

1. Created a fresh install of redash from the current master branch and deleted the custom sql expressions created by sqlalchemy_searchable. This mimics the state of an installation that was upgraded from a version prior to the version bump of sqlalchemy_searchable.
2. Confirmed that search is broken.
3. Deployed fix and ran migrations.
4. Confirmed search is fixed.

## Related Tickets & Documents

Fixes https://github.com/getredash/redash/issues/6381

### CODE REVIEW

**Comment by justinclift** [comment]
Thanks @azundo, this looks useful.  I'm trying to solve a different problem this weekend (Trino related), but this shouldn't be too hard to test too anyway.

**Comment by eradman** [comment]
@azundo do you think this would also solve https://github.com/getredash/redash/pull/6448?

When we tried switching to SQLAlchemy-Utils to 0.36.5 we hit errors when upgrading an existing install.

**Comment by azundo** [comment]
@justinclift I was finally able to manually test it so I have at least run the migration code and confirmed it works as expected, but probably worth having someone else confirm as well. It's a bit awkward to reproduce the exact scenario of installing an older version and then upgrading. I simulated this instead by deleting all the SQL expressions created by sqlalchemy searchable so search would fail again, and then running the redash migration to confirm the fix.

@eradman that issue doesn't look related to me at first glance

**Comment by justinclift** [comment]
Sorry for the delay in reviewing this.  I have this on my ToDo list for the next few days though.  It's not forgotten. :smile:

**Comment by azundo** [comment]
No worries at all! The workaround I shared in the bug report is an easy fix for anyone running into this so I wouldn't say it's urgent.

**Comment by denisov-vlad** [comment]
Hi!

@azundo @justinclift I've tested it both on my dev server and production cluster, and everything works fine.

@eradman Also tested updating to `SQLAlchemy-Utils==0.36.5`, the same error as before. :(

**Comment by Krikooo** [comment]
I tested this PR, it's work just like a charm.
Thank you for your work @azundo 👍

**Comment by justinclift** [comment]
Awesome.  Thanks for verifying it @Krikooo.  Merging it now. :smile:

**Review by justinclift — APPROVED** [review]

**Comment by pinophyta** [comment]
What's the proper way to run this migration after upgrading redash?

**Comment by eradman** [comment]
@pinophyta try
```
docker compose run --rm server manage db upgrade
```

or if not using docker
```
$REDASH_DIR/bin/manage db upgrade
```

**Comment by pinophyta** [comment]
Thank you very much @eradman. That worked and I was able to upgrade to latest dev tag 🥳

**Pull request merged**
