### PR TITLE
[Data Source] Adds a Google Spreadsheet OAuth User

### PR DESCRIPTION
**Pull request by akiray03**
Adds a Google Spreadsheet DataSource connecting by OAuth User (NOT Service Account).

## Motivation

Some G Suite users, Restrict sharing of files outside the organization. They cannot grant permissions to users in different domains. The service accounts domain is different G Suite domains, it could not be accessed.
https://support.google.com/a/answer/60781?hl=en

## Screen Capture

redash-datasource-google-spreadsheet-oauth-user

### CODE REVIEW

**Comment by denisov-vlad** [comment]
I think it will be good to add this option for all Google data sources used in redash. But the way with **new** datasource with different login type looks bad for me.

**Comment by akiray03** [comment]
@denisov-vlad  Thanks. My idea is as follows. What do you think?

1. adds GoogleOAuth model.
1. adds google_oauth_id columns (nullable) to data_sources.
1. For a data source that uses Google authentication, let's choose the service account and Google OAuth.

image

**Comment by denisov-vlad** [comment]
@akiray03 that's a good idea but i can't imagine how to make it in redash user interface.
It's possible to add google_oauth_credetials to redash user's profile. Then you can add datasource for Spreadsheets/Analytics/etc using service account or your redash user's oauth credentials. It looks better for me.

**Comment by denisov-vlad** [comment]
maybe @arikfr knows a better solution

**Comment by akiray03** [comment]
@denisov-vlad  Thanks. sounds good.
The idea I suggested for the first time was that we do not need to give permission to Redash's end users. But in many cases it can be realized with a service account.
I think that I will implement it with the idea you presented.

1. adds UserGoogleCredential model. (It has user_id, org_id, scopes, and credentials.)
2. adds the Service Account and the executor account selection settings to DataSource
3. adds account selection function to QueryRunner
4. add a mechanism to request authentication 
5. and other ..

**Comment by akiray03** [comment]
@arikfr What do you think with this approach?

**Comment by arikfr** [comment]
Apologies for leaving this untouched for so long... :-(

I have a few comments about the code, but my main concern is more a conceptual one: data sources in Redash are shared among users. Does it really make sense for a user to give access to all his spreadsheets in such environment?

It does make sense to have a flow where the user can easily import a spreadsheet into Redash but on a per spreadsheet basis (maybe using something like the [Picker API](https://developers.google.com/picker/docs/)?); without the need to create a special data source first. It does require changing some concepts in Redash a bit. :\

What was your use case for this?

--- 

As for the other discussion you had here, due to the need to authorize specific scopes when adding different data sources, I'm not sure what we gain by storing OAuth credentials in a central store (while adding complexity to the implementation).

---

Apologies again for the long period of silence. Will try to be more responsive now.

**Comment by arikfr** [comment]
Hi,

(This is a template message, but I mean every word of it. Also you're welcome to reply)

Thank you for making this contribution. While we couldn't bring it to completion and merge, it's still very much appreciated. 🙇

In the past year the Redash code base gone under massive updates: on the backend we moved to Python 3 & RQ instead of Celery and on the frontend we replaced Angular with React. It's very likely this makes this PR irrelevant without significant changes. :-( 

I'm closing this PR now. But if you're still interested in making it happen, let me know and I will reopen.

Thanks.

**Pull request closed without merging**
